// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/coreos/go-oidc/v3/oidc"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenVerifier creates a new instance of MockTokenVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenVerifier {
	mock := &MockTokenVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenVerifier is an autogenerated mock type for the tokenVerifier type
type MockTokenVerifier struct {
	mock.Mock
}

type MockTokenVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenVerifier) EXPECT() *MockTokenVerifier_Expecter {
	return &MockTokenVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockTokenVerifier
func (_mock *MockTokenVerifier) Verify(ctx context.Context, rawIDToken string) (*oidc.IDToken, error) {
	ret := _mock.Called(ctx, rawIDToken)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *oidc.IDToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*oidc.IDToken, error)); ok {
		return returnFunc(ctx, rawIDToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *oidc.IDToken); ok {
		r0 = returnFunc(ctx, rawIDToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oidc.IDToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, rawIDToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockTokenVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - rawIDToken string
func (_e *MockTokenVerifier_Expecter) Verify(ctx any, rawIDToken any) *MockTokenVerifier_Verify_Call {
	return &MockTokenVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, rawIDToken)}
}

func (_c *MockTokenVerifier_Verify_Call) Run(run func(ctx context.Context, rawIDToken string)) *MockTokenVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenVerifier_Verify_Call) Return(iDToken *oidc.IDToken, err error) *MockTokenVerifier_Verify_Call {
	_c.Call.Return(iDToken, err)
	return _c
}

func (_c *MockTokenVerifier_Verify_Call) RunAndReturn(run func(ctx context.Context, rawIDToken string) (*oidc.IDToken, error)) *MockTokenVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}
