template: testify
packages:
  github.com/rogueserenity/kbdb/internal/auth:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      filename: 'mock_{{.InterfaceName}}.go'
      pkgname: 'mocks'
      structname: 'MockTokenVerifier'
    interfaces:
      tokenVerifier:
  github.com/rogueserenity/kbdb/internal/repository:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      filename: 'mock_{{.InterfaceName}}.go'
      pkgname: 'mocks'
    interfaces:
      SwitchRepository:
        config:
          structname: 'MockSwitchRepository'
      KeyboardRepository:
        config:
          structname: 'MockKeyboardRepository'
      KeycapSetRepository:
        config:
          structname: 'MockKeycapSetRepository'
      KeycapKitImageStore:
        config:
          structname: 'MockKeycapKitImageStore'
      BuildRepository:
        config:
          structname: 'MockBuildRepository'
      BuildImageStore:
        config:
          structname: 'MockBuildImageStore'
      KeyboardImageStore:
        config:
          structname: 'MockKeyboardImageStore'
      SwitchImageStore:
        config:
          structname: 'MockSwitchImageStore'
      ProfileRepository:
        config:
          structname: 'MockProfileRepository'
      ProfileImageStore:
        config:
          structname: 'MockProfileImageStore'
  github.com/rogueserenity/kbdb/internal/repository/dynamo:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      filename: 'mock_{{.InterfaceName}}.go'
      pkgname: 'mocks'
      structname: 'MockDynamoAPI'
    interfaces:
      dynamoAPI:
  github.com/rogueserenity/kbdb/internal/repository/s3:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      filename: 'mock_{{.InterfaceName}}.go'
      pkgname: 'mocks'
    interfaces:
      s3API:
        config:
          structname: 'MockS3API'
      s3PresignAPI:
        config:
          structname: 'MockS3PresignAPI'
