template: testify
packages:
  github.com/rogueserenity/kbdb/internal/auth:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      filename: 'mock_{{.InterfaceName}}.go'
      pkgname: 'mocks'
      structname: 'MockTokenVerifier'
    interfaces:
      tokenVerifier:
  github.com/rogueserenity/kbdb/internal/repository:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      filename: 'mock_{{.InterfaceName}}.go'
      pkgname: 'mocks'
    interfaces:
      LookupRepository:
        config:
          structname: 'MockLookupRepository'
      SwitchRepository:
        config:
          structname: 'MockSwitchRepository'
      KeyboardRepository:
        config:
          structname: 'MockKeyboardRepository'
      KeycapSetRepository:
        config:
          structname: 'MockKeycapSetRepository'
  github.com/rogueserenity/kbdb/internal/repository/dynamo:
    config:
      dir: '{{.InterfaceDir}}/mocks'
      filename: 'mock_{{.InterfaceName}}.go'
      pkgname: 'mocks'
      structname: 'MockDynamoAPI'
    interfaces:
      dynamoAPI:
