// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rogueserenity/kbdb/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeyboardImageStore creates a new instance of MockKeyboardImageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyboardImageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyboardImageStore {
	mock := &MockKeyboardImageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeyboardImageStore is an autogenerated mock type for the KeyboardImageStore type
type MockKeyboardImageStore struct {
	mock.Mock
}

type MockKeyboardImageStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyboardImageStore) EXPECT() *MockKeyboardImageStore_Expecter {
	return &MockKeyboardImageStore_Expecter{mock: &_m.Mock}
}

// BestEffortDelete provides a mock function for the type MockKeyboardImageStore
func (_mock *MockKeyboardImageStore) BestEffortDelete(ctx context.Context, keys []repository.KeyboardImageKey) {
	_mock.Called(ctx, keys)
	return
}

// MockKeyboardImageStore_BestEffortDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BestEffortDelete'
type MockKeyboardImageStore_BestEffortDelete_Call struct {
	*mock.Call
}

// BestEffortDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []repository.KeyboardImageKey
func (_e *MockKeyboardImageStore_Expecter) BestEffortDelete(ctx any, keys any) *MockKeyboardImageStore_BestEffortDelete_Call {
	return &MockKeyboardImageStore_BestEffortDelete_Call{Call: _e.mock.On("BestEffortDelete", ctx, keys)}
}

func (_c *MockKeyboardImageStore_BestEffortDelete_Call) Run(run func(ctx context.Context, keys []repository.KeyboardImageKey)) *MockKeyboardImageStore_BestEffortDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []repository.KeyboardImageKey
		if args[1] != nil {
			arg1 = args[1].([]repository.KeyboardImageKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyboardImageStore_BestEffortDelete_Call) Return() *MockKeyboardImageStore_BestEffortDelete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockKeyboardImageStore_BestEffortDelete_Call) RunAndReturn(run func(ctx context.Context, keys []repository.KeyboardImageKey)) *MockKeyboardImageStore_BestEffortDelete_Call {
	_c.Run(run)
	return _c
}

// DeleteKeyboardImage provides a mock function for the type MockKeyboardImageStore
func (_mock *MockKeyboardImageStore) DeleteKeyboardImage(ctx context.Context, key repository.KeyboardImageKey) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKeyboardImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.KeyboardImageKey) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyboardImageStore_DeleteKeyboardImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKeyboardImage'
type MockKeyboardImageStore_DeleteKeyboardImage_Call struct {
	*mock.Call
}

// DeleteKeyboardImage is a helper method to define mock.On call
//   - ctx context.Context
//   - key repository.KeyboardImageKey
func (_e *MockKeyboardImageStore_Expecter) DeleteKeyboardImage(ctx any, key any) *MockKeyboardImageStore_DeleteKeyboardImage_Call {
	return &MockKeyboardImageStore_DeleteKeyboardImage_Call{Call: _e.mock.On("DeleteKeyboardImage", ctx, key)}
}

func (_c *MockKeyboardImageStore_DeleteKeyboardImage_Call) Run(run func(ctx context.Context, key repository.KeyboardImageKey)) *MockKeyboardImageStore_DeleteKeyboardImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.KeyboardImageKey
		if args[1] != nil {
			arg1 = args[1].(repository.KeyboardImageKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyboardImageStore_DeleteKeyboardImage_Call) Return(err error) *MockKeyboardImageStore_DeleteKeyboardImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyboardImageStore_DeleteKeyboardImage_Call) RunAndReturn(run func(ctx context.Context, key repository.KeyboardImageKey) error) *MockKeyboardImageStore_DeleteKeyboardImage_Call {
	_c.Call.Return(run)
	return _c
}

// PresignGetKeyboardImage provides a mock function for the type MockKeyboardImageStore
func (_mock *MockKeyboardImageStore) PresignGetKeyboardImage(ctx context.Context, key repository.KeyboardImageKey) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for PresignGetKeyboardImage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.KeyboardImageKey) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.KeyboardImageKey) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.KeyboardImageKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardImageStore_PresignGetKeyboardImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignGetKeyboardImage'
type MockKeyboardImageStore_PresignGetKeyboardImage_Call struct {
	*mock.Call
}

// PresignGetKeyboardImage is a helper method to define mock.On call
//   - ctx context.Context
//   - key repository.KeyboardImageKey
func (_e *MockKeyboardImageStore_Expecter) PresignGetKeyboardImage(ctx any, key any) *MockKeyboardImageStore_PresignGetKeyboardImage_Call {
	return &MockKeyboardImageStore_PresignGetKeyboardImage_Call{Call: _e.mock.On("PresignGetKeyboardImage", ctx, key)}
}

func (_c *MockKeyboardImageStore_PresignGetKeyboardImage_Call) Run(run func(ctx context.Context, key repository.KeyboardImageKey)) *MockKeyboardImageStore_PresignGetKeyboardImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.KeyboardImageKey
		if args[1] != nil {
			arg1 = args[1].(repository.KeyboardImageKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyboardImageStore_PresignGetKeyboardImage_Call) Return(url string, err error) *MockKeyboardImageStore_PresignGetKeyboardImage_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockKeyboardImageStore_PresignGetKeyboardImage_Call) RunAndReturn(run func(ctx context.Context, key repository.KeyboardImageKey) (string, error)) *MockKeyboardImageStore_PresignGetKeyboardImage_Call {
	_c.Call.Return(run)
	return _c
}

// PresignPutKeyboardImage provides a mock function for the type MockKeyboardImageStore
func (_mock *MockKeyboardImageStore) PresignPutKeyboardImage(ctx context.Context, key repository.KeyboardImageKey, contentType string) (string, error) {
	ret := _mock.Called(ctx, key, contentType)

	if len(ret) == 0 {
		panic("no return value specified for PresignPutKeyboardImage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.KeyboardImageKey, string) (string, error)); ok {
		return returnFunc(ctx, key, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.KeyboardImageKey, string) string); ok {
		r0 = returnFunc(ctx, key, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.KeyboardImageKey, string) error); ok {
		r1 = returnFunc(ctx, key, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardImageStore_PresignPutKeyboardImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignPutKeyboardImage'
type MockKeyboardImageStore_PresignPutKeyboardImage_Call struct {
	*mock.Call
}

// PresignPutKeyboardImage is a helper method to define mock.On call
//   - ctx context.Context
//   - key repository.KeyboardImageKey
//   - contentType string
func (_e *MockKeyboardImageStore_Expecter) PresignPutKeyboardImage(ctx any, key any, contentType any) *MockKeyboardImageStore_PresignPutKeyboardImage_Call {
	return &MockKeyboardImageStore_PresignPutKeyboardImage_Call{Call: _e.mock.On("PresignPutKeyboardImage", ctx, key, contentType)}
}

func (_c *MockKeyboardImageStore_PresignPutKeyboardImage_Call) Run(run func(ctx context.Context, key repository.KeyboardImageKey, contentType string)) *MockKeyboardImageStore_PresignPutKeyboardImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.KeyboardImageKey
		if args[1] != nil {
			arg1 = args[1].(repository.KeyboardImageKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyboardImageStore_PresignPutKeyboardImage_Call) Return(url string, err error) *MockKeyboardImageStore_PresignPutKeyboardImage_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockKeyboardImageStore_PresignPutKeyboardImage_Call) RunAndReturn(run func(ctx context.Context, key repository.KeyboardImageKey, contentType string) (string, error)) *MockKeyboardImageStore_PresignPutKeyboardImage_Call {
	_c.Call.Return(run)
	return _c
}
