// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLookupRepository creates a new instance of MockLookupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLookupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLookupRepository {
	mock := &MockLookupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLookupRepository is an autogenerated mock type for the LookupRepository type
type MockLookupRepository struct {
	mock.Mock
}

type MockLookupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLookupRepository) EXPECT() *MockLookupRepository_Expecter {
	return &MockLookupRepository_Expecter{mock: &_m.Mock}
}

// ListCategories provides a mock function for the type MockLookupRepository
func (_mock *MockLookupRepository) ListCategories(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLookupRepository_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type MockLookupRepository_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLookupRepository_Expecter) ListCategories(ctx any) *MockLookupRepository_ListCategories_Call {
	return &MockLookupRepository_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx)}
}

func (_c *MockLookupRepository_ListCategories_Call) Run(run func(ctx context.Context)) *MockLookupRepository_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLookupRepository_ListCategories_Call) Return(strings []string, err error) *MockLookupRepository_ListCategories_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockLookupRepository_ListCategories_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockLookupRepository_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}
