// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rogueserenity/kbdb/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeyboardRepository creates a new instance of MockKeyboardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyboardRepository {
	mock := &MockKeyboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeyboardRepository is an autogenerated mock type for the KeyboardRepository type
type MockKeyboardRepository struct {
	mock.Mock
}

type MockKeyboardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyboardRepository) EXPECT() *MockKeyboardRepository_Expecter {
	return &MockKeyboardRepository_Expecter{mock: &_m.Mock}
}

// AddImage provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) AddImage(ctx context.Context, keyboardID string, image repository.KeyboardImage) (*repository.KeyboardImage, error) {
	ret := _mock.Called(ctx, keyboardID, image)

	if len(ret) == 0 {
		panic("no return value specified for AddImage")
	}

	var r0 *repository.KeyboardImage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeyboardImage) (*repository.KeyboardImage, error)); ok {
		return returnFunc(ctx, keyboardID, image)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeyboardImage) *repository.KeyboardImage); ok {
		r0 = returnFunc(ctx, keyboardID, image)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeyboardImage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, repository.KeyboardImage) error); ok {
		r1 = returnFunc(ctx, keyboardID, image)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_AddImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddImage'
type MockKeyboardRepository_AddImage_Call struct {
	*mock.Call
}

// AddImage is a helper method to define mock.On call
//   - ctx context.Context
//   - keyboardID string
//   - image repository.KeyboardImage
func (_e *MockKeyboardRepository_Expecter) AddImage(ctx any, keyboardID any, image any) *MockKeyboardRepository_AddImage_Call {
	return &MockKeyboardRepository_AddImage_Call{Call: _e.mock.On("AddImage", ctx, keyboardID, image)}
}

func (_c *MockKeyboardRepository_AddImage_Call) Run(run func(ctx context.Context, keyboardID string, image repository.KeyboardImage)) *MockKeyboardRepository_AddImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 repository.KeyboardImage
		if args[2] != nil {
			arg2 = args[2].(repository.KeyboardImage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_AddImage_Call) Return(keyboardImage *repository.KeyboardImage, err error) *MockKeyboardRepository_AddImage_Call {
	_c.Call.Return(keyboardImage, err)
	return _c
}

func (_c *MockKeyboardRepository_AddImage_Call) RunAndReturn(run func(ctx context.Context, keyboardID string, image repository.KeyboardImage) (*repository.KeyboardImage, error)) *MockKeyboardRepository_AddImage_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) Create(ctx context.Context, kb repository.Keyboard) (*repository.Keyboard, error) {
	ret := _mock.Called(ctx, kb)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.Keyboard
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Keyboard) (*repository.Keyboard, error)); ok {
		return returnFunc(ctx, kb)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Keyboard) *repository.Keyboard); ok {
		r0 = returnFunc(ctx, kb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Keyboard)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Keyboard) error); ok {
		r1 = returnFunc(ctx, kb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKeyboardRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - kb repository.Keyboard
func (_e *MockKeyboardRepository_Expecter) Create(ctx any, kb any) *MockKeyboardRepository_Create_Call {
	return &MockKeyboardRepository_Create_Call{Call: _e.mock.On("Create", ctx, kb)}
}

func (_c *MockKeyboardRepository_Create_Call) Run(run func(ctx context.Context, kb repository.Keyboard)) *MockKeyboardRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Keyboard
		if args[1] != nil {
			arg1 = args[1].(repository.Keyboard)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_Create_Call) Return(keyboard *repository.Keyboard, err error) *MockKeyboardRepository_Create_Call {
	_c.Call.Return(keyboard, err)
	return _c
}

func (_c *MockKeyboardRepository_Create_Call) RunAndReturn(run func(ctx context.Context, kb repository.Keyboard) (*repository.Keyboard, error)) *MockKeyboardRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyboardRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockKeyboardRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockKeyboardRepository_Expecter) Delete(ctx any, id any) *MockKeyboardRepository_Delete_Call {
	return &MockKeyboardRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockKeyboardRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockKeyboardRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_Delete_Call) Return(err error) *MockKeyboardRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyboardRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockKeyboardRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteImage provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) DeleteImage(ctx context.Context, keyboardID string, imageID string) (*repository.KeyboardImageKey, error) {
	ret := _mock.Called(ctx, keyboardID, imageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImage")
	}

	var r0 *repository.KeyboardImageKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*repository.KeyboardImageKey, error)); ok {
		return returnFunc(ctx, keyboardID, imageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *repository.KeyboardImageKey); ok {
		r0 = returnFunc(ctx, keyboardID, imageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeyboardImageKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, keyboardID, imageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_DeleteImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImage'
type MockKeyboardRepository_DeleteImage_Call struct {
	*mock.Call
}

// DeleteImage is a helper method to define mock.On call
//   - ctx context.Context
//   - keyboardID string
//   - imageID string
func (_e *MockKeyboardRepository_Expecter) DeleteImage(ctx any, keyboardID any, imageID any) *MockKeyboardRepository_DeleteImage_Call {
	return &MockKeyboardRepository_DeleteImage_Call{Call: _e.mock.On("DeleteImage", ctx, keyboardID, imageID)}
}

func (_c *MockKeyboardRepository_DeleteImage_Call) Run(run func(ctx context.Context, keyboardID string, imageID string)) *MockKeyboardRepository_DeleteImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_DeleteImage_Call) Return(keyboardImageKey *repository.KeyboardImageKey, err error) *MockKeyboardRepository_DeleteImage_Call {
	_c.Call.Return(keyboardImageKey, err)
	return _c
}

func (_c *MockKeyboardRepository_DeleteImage_Call) RunAndReturn(run func(ctx context.Context, keyboardID string, imageID string) (*repository.KeyboardImageKey, error)) *MockKeyboardRepository_DeleteImage_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) Get(ctx context.Context, ownerID string, id string) (*repository.Keyboard, error) {
	ret := _mock.Called(ctx, ownerID, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repository.Keyboard
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*repository.Keyboard, error)); ok {
		return returnFunc(ctx, ownerID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *repository.Keyboard); ok {
		r0 = returnFunc(ctx, ownerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Keyboard)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ownerID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockKeyboardRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - id string
func (_e *MockKeyboardRepository_Expecter) Get(ctx any, ownerID any, id any) *MockKeyboardRepository_Get_Call {
	return &MockKeyboardRepository_Get_Call{Call: _e.mock.On("Get", ctx, ownerID, id)}
}

func (_c *MockKeyboardRepository_Get_Call) Run(run func(ctx context.Context, ownerID string, id string)) *MockKeyboardRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_Get_Call) Return(keyboard *repository.Keyboard, err error) *MockKeyboardRepository_Get_Call {
	_c.Call.Return(keyboard, err)
	return _c
}

func (_c *MockKeyboardRepository_Get_Call) RunAndReturn(run func(ctx context.Context, ownerID string, id string) (*repository.Keyboard, error)) *MockKeyboardRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) List(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string) ([]repository.Keyboard, string, error) {
	ret := _mock.Called(ctx, ownerID, visibilities, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []repository.Keyboard
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []repository.Visibility, int, string) ([]repository.Keyboard, string, error)); ok {
		return returnFunc(ctx, ownerID, visibilities, limit, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []repository.Visibility, int, string) []repository.Keyboard); ok {
		r0 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Keyboard)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []repository.Visibility, int, string) string); ok {
		r1 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []repository.Visibility, int, string) error); ok {
		r2 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockKeyboardRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockKeyboardRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - visibilities []repository.Visibility
//   - limit int
//   - cursor string
func (_e *MockKeyboardRepository_Expecter) List(ctx any, ownerID any, visibilities any, limit any, cursor any) *MockKeyboardRepository_List_Call {
	return &MockKeyboardRepository_List_Call{Call: _e.mock.On("List", ctx, ownerID, visibilities, limit, cursor)}
}

func (_c *MockKeyboardRepository_List_Call) Run(run func(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string)) *MockKeyboardRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []repository.Visibility
		if args[2] != nil {
			arg2 = args[2].([]repository.Visibility)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_List_Call) Return(keyboards []repository.Keyboard, nextCursor string, err error) *MockKeyboardRepository_List_Call {
	_c.Call.Return(keyboards, nextCursor, err)
	return _c
}

func (_c *MockKeyboardRepository_List_Call) RunAndReturn(run func(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string) ([]repository.Keyboard, string, error)) *MockKeyboardRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) Update(ctx context.Context, kb repository.Keyboard) (*repository.Keyboard, error) {
	ret := _mock.Called(ctx, kb)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.Keyboard
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Keyboard) (*repository.Keyboard, error)); ok {
		return returnFunc(ctx, kb)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Keyboard) *repository.Keyboard); ok {
		r0 = returnFunc(ctx, kb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Keyboard)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Keyboard) error); ok {
		r1 = returnFunc(ctx, kb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockKeyboardRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - kb repository.Keyboard
func (_e *MockKeyboardRepository_Expecter) Update(ctx any, kb any) *MockKeyboardRepository_Update_Call {
	return &MockKeyboardRepository_Update_Call{Call: _e.mock.On("Update", ctx, kb)}
}

func (_c *MockKeyboardRepository_Update_Call) Run(run func(ctx context.Context, kb repository.Keyboard)) *MockKeyboardRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Keyboard
		if args[1] != nil {
			arg1 = args[1].(repository.Keyboard)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_Update_Call) Return(keyboard *repository.Keyboard, err error) *MockKeyboardRepository_Update_Call {
	_c.Call.Return(keyboard, err)
	return _c
}

func (_c *MockKeyboardRepository_Update_Call) RunAndReturn(run func(ctx context.Context, kb repository.Keyboard) (*repository.Keyboard, error)) *MockKeyboardRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
