// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKeycapKitImageStore creates a new instance of MockKeycapKitImageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeycapKitImageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeycapKitImageStore {
	mock := &MockKeycapKitImageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeycapKitImageStore is an autogenerated mock type for the KeycapKitImageStore type
type MockKeycapKitImageStore struct {
	mock.Mock
}

type MockKeycapKitImageStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeycapKitImageStore) EXPECT() *MockKeycapKitImageStore_Expecter {
	return &MockKeycapKitImageStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockKeycapKitImageStore
func (_mock *MockKeycapKitImageStore) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeycapKitImageStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockKeycapKitImageStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockKeycapKitImageStore_Expecter) Delete(ctx any, key any) *MockKeycapKitImageStore_Delete_Call {
	return &MockKeycapKitImageStore_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockKeycapKitImageStore_Delete_Call) Run(run func(ctx context.Context, key string)) *MockKeycapKitImageStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeycapKitImageStore_Delete_Call) Return(err error) *MockKeycapKitImageStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeycapKitImageStore_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockKeycapKitImageStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// PresignGet provides a mock function for the type MockKeycapKitImageStore
func (_mock *MockKeycapKitImageStore) PresignGet(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for PresignGet")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeycapKitImageStore_PresignGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignGet'
type MockKeycapKitImageStore_PresignGet_Call struct {
	*mock.Call
}

// PresignGet is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockKeycapKitImageStore_Expecter) PresignGet(ctx any, key any) *MockKeycapKitImageStore_PresignGet_Call {
	return &MockKeycapKitImageStore_PresignGet_Call{Call: _e.mock.On("PresignGet", ctx, key)}
}

func (_c *MockKeycapKitImageStore_PresignGet_Call) Run(run func(ctx context.Context, key string)) *MockKeycapKitImageStore_PresignGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeycapKitImageStore_PresignGet_Call) Return(url string, err error) *MockKeycapKitImageStore_PresignGet_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockKeycapKitImageStore_PresignGet_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockKeycapKitImageStore_PresignGet_Call {
	_c.Call.Return(run)
	return _c
}

// PresignPut provides a mock function for the type MockKeycapKitImageStore
func (_mock *MockKeycapKitImageStore) PresignPut(ctx context.Context, key string, contentType string) (string, error) {
	ret := _mock.Called(ctx, key, contentType)

	if len(ret) == 0 {
		panic("no return value specified for PresignPut")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, key, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, key, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, key, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeycapKitImageStore_PresignPut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignPut'
type MockKeycapKitImageStore_PresignPut_Call struct {
	*mock.Call
}

// PresignPut is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - contentType string
func (_e *MockKeycapKitImageStore_Expecter) PresignPut(ctx any, key any, contentType any) *MockKeycapKitImageStore_PresignPut_Call {
	return &MockKeycapKitImageStore_PresignPut_Call{Call: _e.mock.On("PresignPut", ctx, key, contentType)}
}

func (_c *MockKeycapKitImageStore_PresignPut_Call) Run(run func(ctx context.Context, key string, contentType string)) *MockKeycapKitImageStore_PresignPut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeycapKitImageStore_PresignPut_Call) Return(url string, err error) *MockKeycapKitImageStore_PresignPut_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockKeycapKitImageStore_PresignPut_Call) RunAndReturn(run func(ctx context.Context, key string, contentType string) (string, error)) *MockKeycapKitImageStore_PresignPut_Call {
	_c.Call.Return(run)
	return _c
}
