// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rogueserenity/kbdb/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLookupRepository creates a new instance of MockLookupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLookupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLookupRepository {
	mock := &MockLookupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLookupRepository is an autogenerated mock type for the LookupRepository type
type MockLookupRepository struct {
	mock.Mock
}

type MockLookupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLookupRepository) EXPECT() *MockLookupRepository_Expecter {
	return &MockLookupRepository_Expecter{mock: &_m.Mock}
}

// CreateCategory provides a mock function for the type MockLookupRepository
func (_mock *MockLookupRepository) CreateCategory(ctx context.Context, category string, values []any) (*repository.Lookup, error) {
	ret := _mock.Called(ctx, category, values)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *repository.Lookup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []any) (*repository.Lookup, error)); ok {
		return returnFunc(ctx, category, values)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []any) *repository.Lookup); ok {
		r0 = returnFunc(ctx, category, values)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Lookup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []any) error); ok {
		r1 = returnFunc(ctx, category, values)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLookupRepository_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type MockLookupRepository_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - category string
//   - values []any
func (_e *MockLookupRepository_Expecter) CreateCategory(ctx any, category any, values any) *MockLookupRepository_CreateCategory_Call {
	return &MockLookupRepository_CreateCategory_Call{Call: _e.mock.On("CreateCategory", ctx, category, values)}
}

func (_c *MockLookupRepository_CreateCategory_Call) Run(run func(ctx context.Context, category string, values []any)) *MockLookupRepository_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		if args[2] != nil {
			arg2 = args[2].([]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLookupRepository_CreateCategory_Call) Return(lookup *repository.Lookup, err error) *MockLookupRepository_CreateCategory_Call {
	_c.Call.Return(lookup, err)
	return _c
}

func (_c *MockLookupRepository_CreateCategory_Call) RunAndReturn(run func(ctx context.Context, category string, values []any) (*repository.Lookup, error)) *MockLookupRepository_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCategory provides a mock function for the type MockLookupRepository
func (_mock *MockLookupRepository) DeleteCategory(ctx context.Context, category string) error {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLookupRepository_DeleteCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCategory'
type MockLookupRepository_DeleteCategory_Call struct {
	*mock.Call
}

// DeleteCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - category string
func (_e *MockLookupRepository_Expecter) DeleteCategory(ctx any, category any) *MockLookupRepository_DeleteCategory_Call {
	return &MockLookupRepository_DeleteCategory_Call{Call: _e.mock.On("DeleteCategory", ctx, category)}
}

func (_c *MockLookupRepository_DeleteCategory_Call) Run(run func(ctx context.Context, category string)) *MockLookupRepository_DeleteCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLookupRepository_DeleteCategory_Call) Return(err error) *MockLookupRepository_DeleteCategory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLookupRepository_DeleteCategory_Call) RunAndReturn(run func(ctx context.Context, category string) error) *MockLookupRepository_DeleteCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategory provides a mock function for the type MockLookupRepository
func (_mock *MockLookupRepository) GetCategory(ctx context.Context, category string) (*repository.Lookup, error) {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for GetCategory")
	}

	var r0 *repository.Lookup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*repository.Lookup, error)); ok {
		return returnFunc(ctx, category)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *repository.Lookup); ok {
		r0 = returnFunc(ctx, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Lookup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, category)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLookupRepository_GetCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategory'
type MockLookupRepository_GetCategory_Call struct {
	*mock.Call
}

// GetCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - category string
func (_e *MockLookupRepository_Expecter) GetCategory(ctx any, category any) *MockLookupRepository_GetCategory_Call {
	return &MockLookupRepository_GetCategory_Call{Call: _e.mock.On("GetCategory", ctx, category)}
}

func (_c *MockLookupRepository_GetCategory_Call) Run(run func(ctx context.Context, category string)) *MockLookupRepository_GetCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLookupRepository_GetCategory_Call) Return(lookup *repository.Lookup, err error) *MockLookupRepository_GetCategory_Call {
	_c.Call.Return(lookup, err)
	return _c
}

func (_c *MockLookupRepository_GetCategory_Call) RunAndReturn(run func(ctx context.Context, category string) (*repository.Lookup, error)) *MockLookupRepository_GetCategory_Call {
	_c.Call.Return(run)
	return _c
}

// ListCategories provides a mock function for the type MockLookupRepository
func (_mock *MockLookupRepository) ListCategories(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLookupRepository_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type MockLookupRepository_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLookupRepository_Expecter) ListCategories(ctx any) *MockLookupRepository_ListCategories_Call {
	return &MockLookupRepository_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx)}
}

func (_c *MockLookupRepository_ListCategories_Call) Run(run func(ctx context.Context)) *MockLookupRepository_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLookupRepository_ListCategories_Call) Return(strings []string, err error) *MockLookupRepository_ListCategories_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockLookupRepository_ListCategories_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockLookupRepository_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceCategory provides a mock function for the type MockLookupRepository
func (_mock *MockLookupRepository) ReplaceCategory(ctx context.Context, category string, values []any) (*repository.Lookup, error) {
	ret := _mock.Called(ctx, category, values)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceCategory")
	}

	var r0 *repository.Lookup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []any) (*repository.Lookup, error)); ok {
		return returnFunc(ctx, category, values)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []any) *repository.Lookup); ok {
		r0 = returnFunc(ctx, category, values)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Lookup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []any) error); ok {
		r1 = returnFunc(ctx, category, values)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLookupRepository_ReplaceCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceCategory'
type MockLookupRepository_ReplaceCategory_Call struct {
	*mock.Call
}

// ReplaceCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - category string
//   - values []any
func (_e *MockLookupRepository_Expecter) ReplaceCategory(ctx any, category any, values any) *MockLookupRepository_ReplaceCategory_Call {
	return &MockLookupRepository_ReplaceCategory_Call{Call: _e.mock.On("ReplaceCategory", ctx, category, values)}
}

func (_c *MockLookupRepository_ReplaceCategory_Call) Run(run func(ctx context.Context, category string, values []any)) *MockLookupRepository_ReplaceCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		if args[2] != nil {
			arg2 = args[2].([]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLookupRepository_ReplaceCategory_Call) Return(lookup *repository.Lookup, err error) *MockLookupRepository_ReplaceCategory_Call {
	_c.Call.Return(lookup, err)
	return _c
}

func (_c *MockLookupRepository_ReplaceCategory_Call) RunAndReturn(run func(ctx context.Context, category string, values []any) (*repository.Lookup, error)) *MockLookupRepository_ReplaceCategory_Call {
	_c.Call.Return(run)
	return _c
}
