// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rogueserenity/kbdb/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfileRepository creates a new instance of MockProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileRepository {
	mock := &MockProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileRepository is an autogenerated mock type for the ProfileRepository type
type MockProfileRepository struct {
	mock.Mock
}

type MockProfileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileRepository) EXPECT() *MockProfileRepository_Expecter {
	return &MockProfileRepository_Expecter{mock: &_m.Mock}
}

// ClearAvatarPath provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) ClearAvatarPath(ctx context.Context) (*repository.ProfileImageKey, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearAvatarPath")
	}

	var r0 *repository.ProfileImageKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*repository.ProfileImageKey, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *repository.ProfileImageKey); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ProfileImageKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_ClearAvatarPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAvatarPath'
type MockProfileRepository_ClearAvatarPath_Call struct {
	*mock.Call
}

// ClearAvatarPath is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfileRepository_Expecter) ClearAvatarPath(ctx any) *MockProfileRepository_ClearAvatarPath_Call {
	return &MockProfileRepository_ClearAvatarPath_Call{Call: _e.mock.On("ClearAvatarPath", ctx)}
}

func (_c *MockProfileRepository_ClearAvatarPath_Call) Run(run func(ctx context.Context)) *MockProfileRepository_ClearAvatarPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfileRepository_ClearAvatarPath_Call) Return(profileImageKey *repository.ProfileImageKey, err error) *MockProfileRepository_ClearAvatarPath_Call {
	_c.Call.Return(profileImageKey, err)
	return _c
}

func (_c *MockProfileRepository_ClearAvatarPath_Call) RunAndReturn(run func(ctx context.Context) (*repository.ProfileImageKey, error)) *MockProfileRepository_ClearAvatarPath_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) Create(ctx context.Context, p repository.Profile) (*repository.Profile, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Profile) (*repository.Profile, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Profile) *repository.Profile); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Profile) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProfileRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p repository.Profile
func (_e *MockProfileRepository_Expecter) Create(ctx any, p any) *MockProfileRepository_Create_Call {
	return &MockProfileRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockProfileRepository_Create_Call) Run(run func(ctx context.Context, p repository.Profile)) *MockProfileRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Profile
		if args[1] != nil {
			arg1 = args[1].(repository.Profile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_Create_Call) Return(profile *repository.Profile, err error) *MockProfileRepository_Create_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockProfileRepository_Create_Call) RunAndReturn(run func(ctx context.Context, p repository.Profile) (*repository.Profile, error)) *MockProfileRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) Delete(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProfileRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfileRepository_Expecter) Delete(ctx any) *MockProfileRepository_Delete_Call {
	return &MockProfileRepository_Delete_Call{Call: _e.mock.On("Delete", ctx)}
}

func (_c *MockProfileRepository_Delete_Call) Run(run func(ctx context.Context)) *MockProfileRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfileRepository_Delete_Call) Return(err error) *MockProfileRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileRepository_Delete_Call) RunAndReturn(run func(ctx context.Context) error) *MockProfileRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) Get(ctx context.Context, stytchUserID string) (*repository.Profile, error) {
	ret := _mock.Called(ctx, stytchUserID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repository.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*repository.Profile, error)); ok {
		return returnFunc(ctx, stytchUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *repository.Profile); ok {
		r0 = returnFunc(ctx, stytchUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, stytchUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProfileRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - stytchUserID string
func (_e *MockProfileRepository_Expecter) Get(ctx any, stytchUserID any) *MockProfileRepository_Get_Call {
	return &MockProfileRepository_Get_Call{Call: _e.mock.On("Get", ctx, stytchUserID)}
}

func (_c *MockProfileRepository_Get_Call) Run(run func(ctx context.Context, stytchUserID string)) *MockProfileRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_Get_Call) Return(profile *repository.Profile, err error) *MockProfileRepository_Get_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockProfileRepository_Get_Call) RunAndReturn(run func(ctx context.Context, stytchUserID string) (*repository.Profile, error)) *MockProfileRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublic provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) ListPublic(ctx context.Context, usernamePrefix string, discordPrefix string, limit int, cursor string) ([]repository.Profile, string, error) {
	ret := _mock.Called(ctx, usernamePrefix, discordPrefix, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for ListPublic")
	}

	var r0 []repository.Profile
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, string) ([]repository.Profile, string, error)); ok {
		return returnFunc(ctx, usernamePrefix, discordPrefix, limit, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, string) []repository.Profile); ok {
		r0 = returnFunc(ctx, usernamePrefix, discordPrefix, limit, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, string) string); ok {
		r1 = returnFunc(ctx, usernamePrefix, discordPrefix, limit, cursor)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, int, string) error); ok {
		r2 = returnFunc(ctx, usernamePrefix, discordPrefix, limit, cursor)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProfileRepository_ListPublic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublic'
type MockProfileRepository_ListPublic_Call struct {
	*mock.Call
}

// ListPublic is a helper method to define mock.On call
//   - ctx context.Context
//   - usernamePrefix string
//   - discordPrefix string
//   - limit int
//   - cursor string
func (_e *MockProfileRepository_Expecter) ListPublic(ctx any, usernamePrefix any, discordPrefix any, limit any, cursor any) *MockProfileRepository_ListPublic_Call {
	return &MockProfileRepository_ListPublic_Call{Call: _e.mock.On("ListPublic", ctx, usernamePrefix, discordPrefix, limit, cursor)}
}

func (_c *MockProfileRepository_ListPublic_Call) Run(run func(ctx context.Context, usernamePrefix string, discordPrefix string, limit int, cursor string)) *MockProfileRepository_ListPublic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockProfileRepository_ListPublic_Call) Return(profiles []repository.Profile, s string, err error) *MockProfileRepository_ListPublic_Call {
	_c.Call.Return(profiles, s, err)
	return _c
}

func (_c *MockProfileRepository_ListPublic_Call) RunAndReturn(run func(ctx context.Context, usernamePrefix string, discordPrefix string, limit int, cursor string) ([]repository.Profile, string, error)) *MockProfileRepository_ListPublic_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveUsername provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) ResolveUsername(ctx context.Context, username string) (string, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for ResolveUsername")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_ResolveUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveUsername'
type MockProfileRepository_ResolveUsername_Call struct {
	*mock.Call
}

// ResolveUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockProfileRepository_Expecter) ResolveUsername(ctx any, username any) *MockProfileRepository_ResolveUsername_Call {
	return &MockProfileRepository_ResolveUsername_Call{Call: _e.mock.On("ResolveUsername", ctx, username)}
}

func (_c *MockProfileRepository_ResolveUsername_Call) Run(run func(ctx context.Context, username string)) *MockProfileRepository_ResolveUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_ResolveUsername_Call) Return(stytchUserID string, err error) *MockProfileRepository_ResolveUsername_Call {
	_c.Call.Return(stytchUserID, err)
	return _c
}

func (_c *MockProfileRepository_ResolveUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (string, error)) *MockProfileRepository_ResolveUsername_Call {
	_c.Call.Return(run)
	return _c
}

// SetAvatarPath provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) SetAvatarPath(ctx context.Context, key repository.ProfileImageKey) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for SetAvatarPath")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.ProfileImageKey) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileRepository_SetAvatarPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAvatarPath'
type MockProfileRepository_SetAvatarPath_Call struct {
	*mock.Call
}

// SetAvatarPath is a helper method to define mock.On call
//   - ctx context.Context
//   - key repository.ProfileImageKey
func (_e *MockProfileRepository_Expecter) SetAvatarPath(ctx any, key any) *MockProfileRepository_SetAvatarPath_Call {
	return &MockProfileRepository_SetAvatarPath_Call{Call: _e.mock.On("SetAvatarPath", ctx, key)}
}

func (_c *MockProfileRepository_SetAvatarPath_Call) Run(run func(ctx context.Context, key repository.ProfileImageKey)) *MockProfileRepository_SetAvatarPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.ProfileImageKey
		if args[1] != nil {
			arg1 = args[1].(repository.ProfileImageKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_SetAvatarPath_Call) Return(err error) *MockProfileRepository_SetAvatarPath_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileRepository_SetAvatarPath_Call) RunAndReturn(run func(ctx context.Context, key repository.ProfileImageKey) error) *MockProfileRepository_SetAvatarPath_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) Update(ctx context.Context, p repository.Profile) (*repository.Profile, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Profile) (*repository.Profile, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Profile) *repository.Profile); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Profile) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProfileRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p repository.Profile
func (_e *MockProfileRepository_Expecter) Update(ctx any, p any) *MockProfileRepository_Update_Call {
	return &MockProfileRepository_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockProfileRepository_Update_Call) Run(run func(ctx context.Context, p repository.Profile)) *MockProfileRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Profile
		if args[1] != nil {
			arg1 = args[1].(repository.Profile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_Update_Call) Return(profile *repository.Profile, err error) *MockProfileRepository_Update_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockProfileRepository_Update_Call) RunAndReturn(run func(ctx context.Context, p repository.Profile) (*repository.Profile, error)) *MockProfileRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
