// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rogueserenity/kbdb/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBuildImageStore creates a new instance of MockBuildImageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBuildImageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBuildImageStore {
	mock := &MockBuildImageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBuildImageStore is an autogenerated mock type for the BuildImageStore type
type MockBuildImageStore struct {
	mock.Mock
}

type MockBuildImageStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBuildImageStore) EXPECT() *MockBuildImageStore_Expecter {
	return &MockBuildImageStore_Expecter{mock: &_m.Mock}
}

// DeleteBuildImage provides a mock function for the type MockBuildImageStore
func (_mock *MockBuildImageStore) DeleteBuildImage(ctx context.Context, key repository.BuildImageKey) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBuildImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.BuildImageKey) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBuildImageStore_DeleteBuildImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBuildImage'
type MockBuildImageStore_DeleteBuildImage_Call struct {
	*mock.Call
}

// DeleteBuildImage is a helper method to define mock.On call
//   - ctx context.Context
//   - key repository.BuildImageKey
func (_e *MockBuildImageStore_Expecter) DeleteBuildImage(ctx any, key any) *MockBuildImageStore_DeleteBuildImage_Call {
	return &MockBuildImageStore_DeleteBuildImage_Call{Call: _e.mock.On("DeleteBuildImage", ctx, key)}
}

func (_c *MockBuildImageStore_DeleteBuildImage_Call) Run(run func(ctx context.Context, key repository.BuildImageKey)) *MockBuildImageStore_DeleteBuildImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.BuildImageKey
		if args[1] != nil {
			arg1 = args[1].(repository.BuildImageKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBuildImageStore_DeleteBuildImage_Call) Return(err error) *MockBuildImageStore_DeleteBuildImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBuildImageStore_DeleteBuildImage_Call) RunAndReturn(run func(ctx context.Context, key repository.BuildImageKey) error) *MockBuildImageStore_DeleteBuildImage_Call {
	_c.Call.Return(run)
	return _c
}

// PresignGetBuildImage provides a mock function for the type MockBuildImageStore
func (_mock *MockBuildImageStore) PresignGetBuildImage(ctx context.Context, key repository.BuildImageKey) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for PresignGetBuildImage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.BuildImageKey) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.BuildImageKey) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.BuildImageKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBuildImageStore_PresignGetBuildImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignGetBuildImage'
type MockBuildImageStore_PresignGetBuildImage_Call struct {
	*mock.Call
}

// PresignGetBuildImage is a helper method to define mock.On call
//   - ctx context.Context
//   - key repository.BuildImageKey
func (_e *MockBuildImageStore_Expecter) PresignGetBuildImage(ctx any, key any) *MockBuildImageStore_PresignGetBuildImage_Call {
	return &MockBuildImageStore_PresignGetBuildImage_Call{Call: _e.mock.On("PresignGetBuildImage", ctx, key)}
}

func (_c *MockBuildImageStore_PresignGetBuildImage_Call) Run(run func(ctx context.Context, key repository.BuildImageKey)) *MockBuildImageStore_PresignGetBuildImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.BuildImageKey
		if args[1] != nil {
			arg1 = args[1].(repository.BuildImageKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBuildImageStore_PresignGetBuildImage_Call) Return(url string, err error) *MockBuildImageStore_PresignGetBuildImage_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockBuildImageStore_PresignGetBuildImage_Call) RunAndReturn(run func(ctx context.Context, key repository.BuildImageKey) (string, error)) *MockBuildImageStore_PresignGetBuildImage_Call {
	_c.Call.Return(run)
	return _c
}

// PresignPutBuildImage provides a mock function for the type MockBuildImageStore
func (_mock *MockBuildImageStore) PresignPutBuildImage(ctx context.Context, key repository.BuildImageKey, contentType string) (string, error) {
	ret := _mock.Called(ctx, key, contentType)

	if len(ret) == 0 {
		panic("no return value specified for PresignPutBuildImage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.BuildImageKey, string) (string, error)); ok {
		return returnFunc(ctx, key, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.BuildImageKey, string) string); ok {
		r0 = returnFunc(ctx, key, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.BuildImageKey, string) error); ok {
		r1 = returnFunc(ctx, key, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBuildImageStore_PresignPutBuildImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignPutBuildImage'
type MockBuildImageStore_PresignPutBuildImage_Call struct {
	*mock.Call
}

// PresignPutBuildImage is a helper method to define mock.On call
//   - ctx context.Context
//   - key repository.BuildImageKey
//   - contentType string
func (_e *MockBuildImageStore_Expecter) PresignPutBuildImage(ctx any, key any, contentType any) *MockBuildImageStore_PresignPutBuildImage_Call {
	return &MockBuildImageStore_PresignPutBuildImage_Call{Call: _e.mock.On("PresignPutBuildImage", ctx, key, contentType)}
}

func (_c *MockBuildImageStore_PresignPutBuildImage_Call) Run(run func(ctx context.Context, key repository.BuildImageKey, contentType string)) *MockBuildImageStore_PresignPutBuildImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.BuildImageKey
		if args[1] != nil {
			arg1 = args[1].(repository.BuildImageKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBuildImageStore_PresignPutBuildImage_Call) Return(url string, err error) *MockBuildImageStore_PresignPutBuildImage_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockBuildImageStore_PresignPutBuildImage_Call) RunAndReturn(run func(ctx context.Context, key repository.BuildImageKey, contentType string) (string, error)) *MockBuildImageStore_PresignPutBuildImage_Call {
	_c.Call.Return(run)
	return _c
}
