// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rogueserenity/kbdb/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfileImageStore creates a new instance of MockProfileImageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileImageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileImageStore {
	mock := &MockProfileImageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileImageStore is an autogenerated mock type for the ProfileImageStore type
type MockProfileImageStore struct {
	mock.Mock
}

type MockProfileImageStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileImageStore) EXPECT() *MockProfileImageStore_Expecter {
	return &MockProfileImageStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockProfileImageStore
func (_mock *MockProfileImageStore) Delete(ctx context.Context, key repository.ProfileImageKey) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.ProfileImageKey) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileImageStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProfileImageStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key repository.ProfileImageKey
func (_e *MockProfileImageStore_Expecter) Delete(ctx any, key any) *MockProfileImageStore_Delete_Call {
	return &MockProfileImageStore_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockProfileImageStore_Delete_Call) Run(run func(ctx context.Context, key repository.ProfileImageKey)) *MockProfileImageStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.ProfileImageKey
		if args[1] != nil {
			arg1 = args[1].(repository.ProfileImageKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileImageStore_Delete_Call) Return(err error) *MockProfileImageStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileImageStore_Delete_Call) RunAndReturn(run func(ctx context.Context, key repository.ProfileImageKey) error) *MockProfileImageStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// PresignGet provides a mock function for the type MockProfileImageStore
func (_mock *MockProfileImageStore) PresignGet(ctx context.Context, key repository.ProfileImageKey) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for PresignGet")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.ProfileImageKey) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.ProfileImageKey) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.ProfileImageKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileImageStore_PresignGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignGet'
type MockProfileImageStore_PresignGet_Call struct {
	*mock.Call
}

// PresignGet is a helper method to define mock.On call
//   - ctx context.Context
//   - key repository.ProfileImageKey
func (_e *MockProfileImageStore_Expecter) PresignGet(ctx any, key any) *MockProfileImageStore_PresignGet_Call {
	return &MockProfileImageStore_PresignGet_Call{Call: _e.mock.On("PresignGet", ctx, key)}
}

func (_c *MockProfileImageStore_PresignGet_Call) Run(run func(ctx context.Context, key repository.ProfileImageKey)) *MockProfileImageStore_PresignGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.ProfileImageKey
		if args[1] != nil {
			arg1 = args[1].(repository.ProfileImageKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileImageStore_PresignGet_Call) Return(url string, err error) *MockProfileImageStore_PresignGet_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockProfileImageStore_PresignGet_Call) RunAndReturn(run func(ctx context.Context, key repository.ProfileImageKey) (string, error)) *MockProfileImageStore_PresignGet_Call {
	_c.Call.Return(run)
	return _c
}

// PresignPut provides a mock function for the type MockProfileImageStore
func (_mock *MockProfileImageStore) PresignPut(ctx context.Context, key repository.ProfileImageKey, contentType string) (string, error) {
	ret := _mock.Called(ctx, key, contentType)

	if len(ret) == 0 {
		panic("no return value specified for PresignPut")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.ProfileImageKey, string) (string, error)); ok {
		return returnFunc(ctx, key, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.ProfileImageKey, string) string); ok {
		r0 = returnFunc(ctx, key, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.ProfileImageKey, string) error); ok {
		r1 = returnFunc(ctx, key, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileImageStore_PresignPut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignPut'
type MockProfileImageStore_PresignPut_Call struct {
	*mock.Call
}

// PresignPut is a helper method to define mock.On call
//   - ctx context.Context
//   - key repository.ProfileImageKey
//   - contentType string
func (_e *MockProfileImageStore_Expecter) PresignPut(ctx any, key any, contentType any) *MockProfileImageStore_PresignPut_Call {
	return &MockProfileImageStore_PresignPut_Call{Call: _e.mock.On("PresignPut", ctx, key, contentType)}
}

func (_c *MockProfileImageStore_PresignPut_Call) Run(run func(ctx context.Context, key repository.ProfileImageKey, contentType string)) *MockProfileImageStore_PresignPut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.ProfileImageKey
		if args[1] != nil {
			arg1 = args[1].(repository.ProfileImageKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProfileImageStore_PresignPut_Call) Return(url string, err error) *MockProfileImageStore_PresignPut_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockProfileImageStore_PresignPut_Call) RunAndReturn(run func(ctx context.Context, key repository.ProfileImageKey, contentType string) (string, error)) *MockProfileImageStore_PresignPut_Call {
	_c.Call.Return(run)
	return _c
}
