// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rogueserenity/kbdb/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSwitchImageStore creates a new instance of MockSwitchImageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSwitchImageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSwitchImageStore {
	mock := &MockSwitchImageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSwitchImageStore is an autogenerated mock type for the SwitchImageStore type
type MockSwitchImageStore struct {
	mock.Mock
}

type MockSwitchImageStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSwitchImageStore) EXPECT() *MockSwitchImageStore_Expecter {
	return &MockSwitchImageStore_Expecter{mock: &_m.Mock}
}

// BestEffortDelete provides a mock function for the type MockSwitchImageStore
func (_mock *MockSwitchImageStore) BestEffortDelete(ctx context.Context, keys []repository.SwitchImageKey) {
	_mock.Called(ctx, keys)
	return
}

// MockSwitchImageStore_BestEffortDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BestEffortDelete'
type MockSwitchImageStore_BestEffortDelete_Call struct {
	*mock.Call
}

// BestEffortDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []repository.SwitchImageKey
func (_e *MockSwitchImageStore_Expecter) BestEffortDelete(ctx any, keys any) *MockSwitchImageStore_BestEffortDelete_Call {
	return &MockSwitchImageStore_BestEffortDelete_Call{Call: _e.mock.On("BestEffortDelete", ctx, keys)}
}

func (_c *MockSwitchImageStore_BestEffortDelete_Call) Run(run func(ctx context.Context, keys []repository.SwitchImageKey)) *MockSwitchImageStore_BestEffortDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []repository.SwitchImageKey
		if args[1] != nil {
			arg1 = args[1].([]repository.SwitchImageKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSwitchImageStore_BestEffortDelete_Call) Return() *MockSwitchImageStore_BestEffortDelete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSwitchImageStore_BestEffortDelete_Call) RunAndReturn(run func(ctx context.Context, keys []repository.SwitchImageKey)) *MockSwitchImageStore_BestEffortDelete_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function for the type MockSwitchImageStore
func (_mock *MockSwitchImageStore) Delete(ctx context.Context, key repository.SwitchImageKey) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.SwitchImageKey) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSwitchImageStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSwitchImageStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key repository.SwitchImageKey
func (_e *MockSwitchImageStore_Expecter) Delete(ctx any, key any) *MockSwitchImageStore_Delete_Call {
	return &MockSwitchImageStore_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockSwitchImageStore_Delete_Call) Run(run func(ctx context.Context, key repository.SwitchImageKey)) *MockSwitchImageStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.SwitchImageKey
		if args[1] != nil {
			arg1 = args[1].(repository.SwitchImageKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSwitchImageStore_Delete_Call) Return(err error) *MockSwitchImageStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSwitchImageStore_Delete_Call) RunAndReturn(run func(ctx context.Context, key repository.SwitchImageKey) error) *MockSwitchImageStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// PresignGet provides a mock function for the type MockSwitchImageStore
func (_mock *MockSwitchImageStore) PresignGet(ctx context.Context, key repository.SwitchImageKey) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for PresignGet")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.SwitchImageKey) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.SwitchImageKey) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.SwitchImageKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSwitchImageStore_PresignGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignGet'
type MockSwitchImageStore_PresignGet_Call struct {
	*mock.Call
}

// PresignGet is a helper method to define mock.On call
//   - ctx context.Context
//   - key repository.SwitchImageKey
func (_e *MockSwitchImageStore_Expecter) PresignGet(ctx any, key any) *MockSwitchImageStore_PresignGet_Call {
	return &MockSwitchImageStore_PresignGet_Call{Call: _e.mock.On("PresignGet", ctx, key)}
}

func (_c *MockSwitchImageStore_PresignGet_Call) Run(run func(ctx context.Context, key repository.SwitchImageKey)) *MockSwitchImageStore_PresignGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.SwitchImageKey
		if args[1] != nil {
			arg1 = args[1].(repository.SwitchImageKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSwitchImageStore_PresignGet_Call) Return(url string, err error) *MockSwitchImageStore_PresignGet_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockSwitchImageStore_PresignGet_Call) RunAndReturn(run func(ctx context.Context, key repository.SwitchImageKey) (string, error)) *MockSwitchImageStore_PresignGet_Call {
	_c.Call.Return(run)
	return _c
}

// PresignPut provides a mock function for the type MockSwitchImageStore
func (_mock *MockSwitchImageStore) PresignPut(ctx context.Context, key repository.SwitchImageKey, contentType string) (string, error) {
	ret := _mock.Called(ctx, key, contentType)

	if len(ret) == 0 {
		panic("no return value specified for PresignPut")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.SwitchImageKey, string) (string, error)); ok {
		return returnFunc(ctx, key, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.SwitchImageKey, string) string); ok {
		r0 = returnFunc(ctx, key, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.SwitchImageKey, string) error); ok {
		r1 = returnFunc(ctx, key, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSwitchImageStore_PresignPut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignPut'
type MockSwitchImageStore_PresignPut_Call struct {
	*mock.Call
}

// PresignPut is a helper method to define mock.On call
//   - ctx context.Context
//   - key repository.SwitchImageKey
//   - contentType string
func (_e *MockSwitchImageStore_Expecter) PresignPut(ctx any, key any, contentType any) *MockSwitchImageStore_PresignPut_Call {
	return &MockSwitchImageStore_PresignPut_Call{Call: _e.mock.On("PresignPut", ctx, key, contentType)}
}

func (_c *MockSwitchImageStore_PresignPut_Call) Run(run func(ctx context.Context, key repository.SwitchImageKey, contentType string)) *MockSwitchImageStore_PresignPut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.SwitchImageKey
		if args[1] != nil {
			arg1 = args[1].(repository.SwitchImageKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSwitchImageStore_PresignPut_Call) Return(url string, err error) *MockSwitchImageStore_PresignPut_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockSwitchImageStore_PresignPut_Call) RunAndReturn(run func(ctx context.Context, key repository.SwitchImageKey, contentType string) (string, error)) *MockSwitchImageStore_PresignPut_Call {
	_c.Call.Return(run)
	return _c
}
