// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rogueserenity/kbdb/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeycapSetRepository creates a new instance of MockKeycapSetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeycapSetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeycapSetRepository {
	mock := &MockKeycapSetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeycapSetRepository is an autogenerated mock type for the KeycapSetRepository type
type MockKeycapSetRepository struct {
	mock.Mock
}

type MockKeycapSetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeycapSetRepository) EXPECT() *MockKeycapSetRepository_Expecter {
	return &MockKeycapSetRepository_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockKeycapSetRepository
func (_mock *MockKeycapSetRepository) List(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string) ([]repository.KeycapSet, string, error) {
	ret := _mock.Called(ctx, ownerID, visibilities, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []repository.KeycapSet
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []repository.Visibility, int, string) ([]repository.KeycapSet, string, error)); ok {
		return returnFunc(ctx, ownerID, visibilities, limit, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []repository.Visibility, int, string) []repository.KeycapSet); ok {
		r0 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.KeycapSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []repository.Visibility, int, string) string); ok {
		r1 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []repository.Visibility, int, string) error); ok {
		r2 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockKeycapSetRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockKeycapSetRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - visibilities []repository.Visibility
//   - limit int
//   - cursor string
func (_e *MockKeycapSetRepository_Expecter) List(ctx any, ownerID any, visibilities any, limit any, cursor any) *MockKeycapSetRepository_List_Call {
	return &MockKeycapSetRepository_List_Call{Call: _e.mock.On("List", ctx, ownerID, visibilities, limit, cursor)}
}

func (_c *MockKeycapSetRepository_List_Call) Run(run func(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string)) *MockKeycapSetRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []repository.Visibility
		if args[2] != nil {
			arg2 = args[2].([]repository.Visibility)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockKeycapSetRepository_List_Call) Return(sets []repository.KeycapSet, nextCursor string, err error) *MockKeycapSetRepository_List_Call {
	_c.Call.Return(sets, nextCursor, err)
	return _c
}

func (_c *MockKeycapSetRepository_List_Call) RunAndReturn(run func(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string) ([]repository.KeycapSet, string, error)) *MockKeycapSetRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
