// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/rogueserenity/kbdb/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeyboardRepository creates a new instance of MockKeyboardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyboardRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockKeyboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockKeyboardRepository is an autogenerated mock type for the KeyboardRepository type
type MockKeyboardRepository struct {
	mock.Mock
}

type MockKeyboardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyboardRepository) EXPECT() *MockKeyboardRepository_Expecter {
	return &MockKeyboardRepository_Expecter{mock: &_m.Mock}
}

// AddImage provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) AddImage(ctx context.Context, keyboardID string, image repository.KeyboardImage) error {
	ret := _mock.Called(ctx, keyboardID, image)

	if len(ret) == 0 {
		panic("no return value specified for AddImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeyboardImage) error); ok {
		r0 = returnFunc(ctx, keyboardID, image)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyboardRepository_AddImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddImage'
type MockKeyboardRepository_AddImage_Call struct {
	*mock.Call
}

// AddImage is a helper method to define mock.On call
//   - ctx context.Context
//   - keyboardID string
//   - image repository.KeyboardImage
func (_e *MockKeyboardRepository_Expecter) AddImage(ctx any, keyboardID any, image any) *MockKeyboardRepository_AddImage_Call {
	return &MockKeyboardRepository_AddImage_Call{Call: _e.mock.On("AddImage", ctx, keyboardID, image)}
}

func (_c *MockKeyboardRepository_AddImage_Call) Run(run func(ctx context.Context, keyboardID string, image repository.KeyboardImage)) *MockKeyboardRepository_AddImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 repository.KeyboardImage
		if args[2] != nil {
			arg2 = args[2].(repository.KeyboardImage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_AddImage_Call) Return(err error) *MockKeyboardRepository_AddImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyboardRepository_AddImage_Call) RunAndReturn(run func(ctx context.Context, keyboardID string, image repository.KeyboardImage) error) *MockKeyboardRepository_AddImage_Call {
	_c.Call.Return(run)
	return _c
}

// AddPCB provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) AddPCB(ctx context.Context, keyboardID string, pcb repository.KeyboardPCB) (*repository.KeyboardPCB, error) {
	ret := _mock.Called(ctx, keyboardID, pcb)

	if len(ret) == 0 {
		panic("no return value specified for AddPCB")
	}

	var r0 *repository.KeyboardPCB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeyboardPCB) (*repository.KeyboardPCB, error)); ok {
		return returnFunc(ctx, keyboardID, pcb)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeyboardPCB) *repository.KeyboardPCB); ok {
		r0 = returnFunc(ctx, keyboardID, pcb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeyboardPCB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, repository.KeyboardPCB) error); ok {
		r1 = returnFunc(ctx, keyboardID, pcb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_AddPCB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPCB'
type MockKeyboardRepository_AddPCB_Call struct {
	*mock.Call
}

// AddPCB is a helper method to define mock.On call
//   - ctx context.Context
//   - keyboardID string
//   - pcb repository.KeyboardPCB
func (_e *MockKeyboardRepository_Expecter) AddPCB(ctx any, keyboardID any, pcb any) *MockKeyboardRepository_AddPCB_Call {
	return &MockKeyboardRepository_AddPCB_Call{Call: _e.mock.On("AddPCB", ctx, keyboardID, pcb)}
}

func (_c *MockKeyboardRepository_AddPCB_Call) Run(run func(ctx context.Context, keyboardID string, pcb repository.KeyboardPCB)) *MockKeyboardRepository_AddPCB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 repository.KeyboardPCB
		if args[2] != nil {
			arg2 = args[2].(repository.KeyboardPCB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_AddPCB_Call) Return(keyboardPCB *repository.KeyboardPCB, err error) *MockKeyboardRepository_AddPCB_Call {
	_c.Call.Return(keyboardPCB, err)
	return _c
}

func (_c *MockKeyboardRepository_AddPCB_Call) RunAndReturn(run func(ctx context.Context, keyboardID string, pcb repository.KeyboardPCB) (*repository.KeyboardPCB, error)) *MockKeyboardRepository_AddPCB_Call {
	_c.Call.Return(run)
	return _c
}

// AddPlate provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) AddPlate(ctx context.Context, keyboardID string, plate repository.KeyboardPlate) (*repository.KeyboardPlate, error) {
	ret := _mock.Called(ctx, keyboardID, plate)

	if len(ret) == 0 {
		panic("no return value specified for AddPlate")
	}

	var r0 *repository.KeyboardPlate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeyboardPlate) (*repository.KeyboardPlate, error)); ok {
		return returnFunc(ctx, keyboardID, plate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeyboardPlate) *repository.KeyboardPlate); ok {
		r0 = returnFunc(ctx, keyboardID, plate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeyboardPlate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, repository.KeyboardPlate) error); ok {
		r1 = returnFunc(ctx, keyboardID, plate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_AddPlate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPlate'
type MockKeyboardRepository_AddPlate_Call struct {
	*mock.Call
}

// AddPlate is a helper method to define mock.On call
//   - ctx context.Context
//   - keyboardID string
//   - plate repository.KeyboardPlate
func (_e *MockKeyboardRepository_Expecter) AddPlate(ctx any, keyboardID any, plate any) *MockKeyboardRepository_AddPlate_Call {
	return &MockKeyboardRepository_AddPlate_Call{Call: _e.mock.On("AddPlate", ctx, keyboardID, plate)}
}

func (_c *MockKeyboardRepository_AddPlate_Call) Run(run func(ctx context.Context, keyboardID string, plate repository.KeyboardPlate)) *MockKeyboardRepository_AddPlate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 repository.KeyboardPlate
		if args[2] != nil {
			arg2 = args[2].(repository.KeyboardPlate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_AddPlate_Call) Return(keyboardPlate *repository.KeyboardPlate, err error) *MockKeyboardRepository_AddPlate_Call {
	_c.Call.Return(keyboardPlate, err)
	return _c
}

func (_c *MockKeyboardRepository_AddPlate_Call) RunAndReturn(run func(ctx context.Context, keyboardID string, plate repository.KeyboardPlate) (*repository.KeyboardPlate, error)) *MockKeyboardRepository_AddPlate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) Create(ctx context.Context, kb repository.Keyboard) (*repository.Keyboard, error) {
	ret := _mock.Called(ctx, kb)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.Keyboard
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Keyboard) (*repository.Keyboard, error)); ok {
		return returnFunc(ctx, kb)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Keyboard) *repository.Keyboard); ok {
		r0 = returnFunc(ctx, kb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Keyboard)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Keyboard) error); ok {
		r1 = returnFunc(ctx, kb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKeyboardRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - kb repository.Keyboard
func (_e *MockKeyboardRepository_Expecter) Create(ctx any, kb any) *MockKeyboardRepository_Create_Call {
	return &MockKeyboardRepository_Create_Call{Call: _e.mock.On("Create", ctx, kb)}
}

func (_c *MockKeyboardRepository_Create_Call) Run(run func(ctx context.Context, kb repository.Keyboard)) *MockKeyboardRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Keyboard
		if args[1] != nil {
			arg1 = args[1].(repository.Keyboard)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_Create_Call) Return(keyboard *repository.Keyboard, err error) *MockKeyboardRepository_Create_Call {
	_c.Call.Return(keyboard, err)
	return _c
}

func (_c *MockKeyboardRepository_Create_Call) RunAndReturn(run func(ctx context.Context, kb repository.Keyboard) (*repository.Keyboard, error)) *MockKeyboardRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyboardRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockKeyboardRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockKeyboardRepository_Expecter) Delete(ctx any, id any) *MockKeyboardRepository_Delete_Call {
	return &MockKeyboardRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockKeyboardRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockKeyboardRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_Delete_Call) Return(err error) *MockKeyboardRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyboardRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockKeyboardRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteImage provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) DeleteImage(ctx context.Context, keyboardID string, imageID string) (*repository.KeyboardImageKey, error) {
	ret := _mock.Called(ctx, keyboardID, imageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImage")
	}

	var r0 *repository.KeyboardImageKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*repository.KeyboardImageKey, error)); ok {
		return returnFunc(ctx, keyboardID, imageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *repository.KeyboardImageKey); ok {
		r0 = returnFunc(ctx, keyboardID, imageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeyboardImageKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, keyboardID, imageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_DeleteImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImage'
type MockKeyboardRepository_DeleteImage_Call struct {
	*mock.Call
}

// DeleteImage is a helper method to define mock.On call
//   - ctx context.Context
//   - keyboardID string
//   - imageID string
func (_e *MockKeyboardRepository_Expecter) DeleteImage(ctx any, keyboardID any, imageID any) *MockKeyboardRepository_DeleteImage_Call {
	return &MockKeyboardRepository_DeleteImage_Call{Call: _e.mock.On("DeleteImage", ctx, keyboardID, imageID)}
}

func (_c *MockKeyboardRepository_DeleteImage_Call) Run(run func(ctx context.Context, keyboardID string, imageID string)) *MockKeyboardRepository_DeleteImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_DeleteImage_Call) Return(keyboardImageKey *repository.KeyboardImageKey, err error) *MockKeyboardRepository_DeleteImage_Call {
	_c.Call.Return(keyboardImageKey, err)
	return _c
}

func (_c *MockKeyboardRepository_DeleteImage_Call) RunAndReturn(run func(ctx context.Context, keyboardID string, imageID string) (*repository.KeyboardImageKey, error)) *MockKeyboardRepository_DeleteImage_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePCB provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) DeletePCB(ctx context.Context, keyboardID string, pcbID string) error {
	ret := _mock.Called(ctx, keyboardID, pcbID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePCB")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, keyboardID, pcbID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyboardRepository_DeletePCB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePCB'
type MockKeyboardRepository_DeletePCB_Call struct {
	*mock.Call
}

// DeletePCB is a helper method to define mock.On call
//   - ctx context.Context
//   - keyboardID string
//   - pcbID string
func (_e *MockKeyboardRepository_Expecter) DeletePCB(ctx any, keyboardID any, pcbID any) *MockKeyboardRepository_DeletePCB_Call {
	return &MockKeyboardRepository_DeletePCB_Call{Call: _e.mock.On("DeletePCB", ctx, keyboardID, pcbID)}
}

func (_c *MockKeyboardRepository_DeletePCB_Call) Run(run func(ctx context.Context, keyboardID string, pcbID string)) *MockKeyboardRepository_DeletePCB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_DeletePCB_Call) Return(err error) *MockKeyboardRepository_DeletePCB_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyboardRepository_DeletePCB_Call) RunAndReturn(run func(ctx context.Context, keyboardID string, pcbID string) error) *MockKeyboardRepository_DeletePCB_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePlate provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) DeletePlate(ctx context.Context, keyboardID string, plateID string) error {
	ret := _mock.Called(ctx, keyboardID, plateID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, keyboardID, plateID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyboardRepository_DeletePlate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlate'
type MockKeyboardRepository_DeletePlate_Call struct {
	*mock.Call
}

// DeletePlate is a helper method to define mock.On call
//   - ctx context.Context
//   - keyboardID string
//   - plateID string
func (_e *MockKeyboardRepository_Expecter) DeletePlate(ctx any, keyboardID any, plateID any) *MockKeyboardRepository_DeletePlate_Call {
	return &MockKeyboardRepository_DeletePlate_Call{Call: _e.mock.On("DeletePlate", ctx, keyboardID, plateID)}
}

func (_c *MockKeyboardRepository_DeletePlate_Call) Run(run func(ctx context.Context, keyboardID string, plateID string)) *MockKeyboardRepository_DeletePlate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_DeletePlate_Call) Return(err error) *MockKeyboardRepository_DeletePlate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyboardRepository_DeletePlate_Call) RunAndReturn(run func(ctx context.Context, keyboardID string, plateID string) error) *MockKeyboardRepository_DeletePlate_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) Get(ctx context.Context, ownerID string, id string) (*repository.Keyboard, error) {
	ret := _mock.Called(ctx, ownerID, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repository.Keyboard
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*repository.Keyboard, error)); ok {
		return returnFunc(ctx, ownerID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *repository.Keyboard); ok {
		r0 = returnFunc(ctx, ownerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Keyboard)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ownerID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockKeyboardRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - id string
func (_e *MockKeyboardRepository_Expecter) Get(ctx any, ownerID any, id any) *MockKeyboardRepository_Get_Call {
	return &MockKeyboardRepository_Get_Call{Call: _e.mock.On("Get", ctx, ownerID, id)}
}

func (_c *MockKeyboardRepository_Get_Call) Run(run func(ctx context.Context, ownerID string, id string)) *MockKeyboardRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_Get_Call) Return(keyboard *repository.Keyboard, err error) *MockKeyboardRepository_Get_Call {
	_c.Call.Return(keyboard, err)
	return _c
}

func (_c *MockKeyboardRepository_Get_Call) RunAndReturn(run func(ctx context.Context, ownerID string, id string) (*repository.Keyboard, error)) *MockKeyboardRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) List(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string) ([]repository.Keyboard, string, error) {
	ret := _mock.Called(ctx, ownerID, visibilities, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []repository.Keyboard
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []repository.Visibility, int, string) ([]repository.Keyboard, string, error)); ok {
		return returnFunc(ctx, ownerID, visibilities, limit, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []repository.Visibility, int, string) []repository.Keyboard); ok {
		r0 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Keyboard)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []repository.Visibility, int, string) string); ok {
		r1 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []repository.Visibility, int, string) error); ok {
		r2 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockKeyboardRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockKeyboardRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - visibilities []repository.Visibility
//   - limit int
//   - cursor string
func (_e *MockKeyboardRepository_Expecter) List(ctx any, ownerID any, visibilities any, limit any, cursor any) *MockKeyboardRepository_List_Call {
	return &MockKeyboardRepository_List_Call{Call: _e.mock.On("List", ctx, ownerID, visibilities, limit, cursor)}
}

func (_c *MockKeyboardRepository_List_Call) Run(run func(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string)) *MockKeyboardRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []repository.Visibility
		if args[2] != nil {
			arg2 = args[2].([]repository.Visibility)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_List_Call) Return(keyboards []repository.Keyboard, nextCursor string, err error) *MockKeyboardRepository_List_Call {
	_c.Call.Return(keyboards, nextCursor, err)
	return _c
}

func (_c *MockKeyboardRepository_List_Call) RunAndReturn(run func(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string) ([]repository.Keyboard, string, error)) *MockKeyboardRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SetImageGetCache provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) SetImageGetCache(ctx context.Context, ownerID string, keyboardID string, imageID string, forPath repository.KeyboardImageKey, url string, expiresAt time.Time) (bool, error) {
	ret := _mock.Called(ctx, ownerID, keyboardID, imageID, forPath, url, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for SetImageGetCache")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, repository.KeyboardImageKey, string, time.Time) (bool, error)); ok {
		return returnFunc(ctx, ownerID, keyboardID, imageID, forPath, url, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, repository.KeyboardImageKey, string, time.Time) bool); ok {
		r0 = returnFunc(ctx, ownerID, keyboardID, imageID, forPath, url, expiresAt)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, repository.KeyboardImageKey, string, time.Time) error); ok {
		r1 = returnFunc(ctx, ownerID, keyboardID, imageID, forPath, url, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_SetImageGetCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetImageGetCache'
type MockKeyboardRepository_SetImageGetCache_Call struct {
	*mock.Call
}

// SetImageGetCache is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - keyboardID string
//   - imageID string
//   - forPath repository.KeyboardImageKey
//   - url string
//   - expiresAt time.Time
func (_e *MockKeyboardRepository_Expecter) SetImageGetCache(ctx any, ownerID any, keyboardID any, imageID any, forPath any, url any, expiresAt any) *MockKeyboardRepository_SetImageGetCache_Call {
	return &MockKeyboardRepository_SetImageGetCache_Call{Call: _e.mock.On("SetImageGetCache", ctx, ownerID, keyboardID, imageID, forPath, url, expiresAt)}
}

func (_c *MockKeyboardRepository_SetImageGetCache_Call) Run(run func(ctx context.Context, ownerID string, keyboardID string, imageID string, forPath repository.KeyboardImageKey, url string, expiresAt time.Time)) *MockKeyboardRepository_SetImageGetCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 repository.KeyboardImageKey
		if args[4] != nil {
			arg4 = args[4].(repository.KeyboardImageKey)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 time.Time
		if args[6] != nil {
			arg6 = args[6].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_SetImageGetCache_Call) Return(ok bool, err error) *MockKeyboardRepository_SetImageGetCache_Call {
	_c.Call.Return(ok, err)
	return _c
}

func (_c *MockKeyboardRepository_SetImageGetCache_Call) RunAndReturn(run func(ctx context.Context, ownerID string, keyboardID string, imageID string, forPath repository.KeyboardImageKey, url string, expiresAt time.Time) (bool, error)) *MockKeyboardRepository_SetImageGetCache_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) Update(ctx context.Context, kb repository.Keyboard) (*repository.Keyboard, error) {
	ret := _mock.Called(ctx, kb)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.Keyboard
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Keyboard) (*repository.Keyboard, error)); ok {
		return returnFunc(ctx, kb)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Keyboard) *repository.Keyboard); ok {
		r0 = returnFunc(ctx, kb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Keyboard)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Keyboard) error); ok {
		r1 = returnFunc(ctx, kb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockKeyboardRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - kb repository.Keyboard
func (_e *MockKeyboardRepository_Expecter) Update(ctx any, kb any) *MockKeyboardRepository_Update_Call {
	return &MockKeyboardRepository_Update_Call{Call: _e.mock.On("Update", ctx, kb)}
}

func (_c *MockKeyboardRepository_Update_Call) Run(run func(ctx context.Context, kb repository.Keyboard)) *MockKeyboardRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Keyboard
		if args[1] != nil {
			arg1 = args[1].(repository.Keyboard)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_Update_Call) Return(keyboard *repository.Keyboard, err error) *MockKeyboardRepository_Update_Call {
	_c.Call.Return(keyboard, err)
	return _c
}

func (_c *MockKeyboardRepository_Update_Call) RunAndReturn(run func(ctx context.Context, kb repository.Keyboard) (*repository.Keyboard, error)) *MockKeyboardRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePCB provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) UpdatePCB(ctx context.Context, keyboardID string, pcb repository.KeyboardPCB) (*repository.KeyboardPCB, error) {
	ret := _mock.Called(ctx, keyboardID, pcb)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePCB")
	}

	var r0 *repository.KeyboardPCB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeyboardPCB) (*repository.KeyboardPCB, error)); ok {
		return returnFunc(ctx, keyboardID, pcb)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeyboardPCB) *repository.KeyboardPCB); ok {
		r0 = returnFunc(ctx, keyboardID, pcb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeyboardPCB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, repository.KeyboardPCB) error); ok {
		r1 = returnFunc(ctx, keyboardID, pcb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_UpdatePCB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePCB'
type MockKeyboardRepository_UpdatePCB_Call struct {
	*mock.Call
}

// UpdatePCB is a helper method to define mock.On call
//   - ctx context.Context
//   - keyboardID string
//   - pcb repository.KeyboardPCB
func (_e *MockKeyboardRepository_Expecter) UpdatePCB(ctx any, keyboardID any, pcb any) *MockKeyboardRepository_UpdatePCB_Call {
	return &MockKeyboardRepository_UpdatePCB_Call{Call: _e.mock.On("UpdatePCB", ctx, keyboardID, pcb)}
}

func (_c *MockKeyboardRepository_UpdatePCB_Call) Run(run func(ctx context.Context, keyboardID string, pcb repository.KeyboardPCB)) *MockKeyboardRepository_UpdatePCB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 repository.KeyboardPCB
		if args[2] != nil {
			arg2 = args[2].(repository.KeyboardPCB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_UpdatePCB_Call) Return(keyboardPCB *repository.KeyboardPCB, err error) *MockKeyboardRepository_UpdatePCB_Call {
	_c.Call.Return(keyboardPCB, err)
	return _c
}

func (_c *MockKeyboardRepository_UpdatePCB_Call) RunAndReturn(run func(ctx context.Context, keyboardID string, pcb repository.KeyboardPCB) (*repository.KeyboardPCB, error)) *MockKeyboardRepository_UpdatePCB_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlate provides a mock function for the type MockKeyboardRepository
func (_mock *MockKeyboardRepository) UpdatePlate(ctx context.Context, keyboardID string, plate repository.KeyboardPlate) (*repository.KeyboardPlate, error) {
	ret := _mock.Called(ctx, keyboardID, plate)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlate")
	}

	var r0 *repository.KeyboardPlate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeyboardPlate) (*repository.KeyboardPlate, error)); ok {
		return returnFunc(ctx, keyboardID, plate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeyboardPlate) *repository.KeyboardPlate); ok {
		r0 = returnFunc(ctx, keyboardID, plate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeyboardPlate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, repository.KeyboardPlate) error); ok {
		r1 = returnFunc(ctx, keyboardID, plate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyboardRepository_UpdatePlate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlate'
type MockKeyboardRepository_UpdatePlate_Call struct {
	*mock.Call
}

// UpdatePlate is a helper method to define mock.On call
//   - ctx context.Context
//   - keyboardID string
//   - plate repository.KeyboardPlate
func (_e *MockKeyboardRepository_Expecter) UpdatePlate(ctx any, keyboardID any, plate any) *MockKeyboardRepository_UpdatePlate_Call {
	return &MockKeyboardRepository_UpdatePlate_Call{Call: _e.mock.On("UpdatePlate", ctx, keyboardID, plate)}
}

func (_c *MockKeyboardRepository_UpdatePlate_Call) Run(run func(ctx context.Context, keyboardID string, plate repository.KeyboardPlate)) *MockKeyboardRepository_UpdatePlate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 repository.KeyboardPlate
		if args[2] != nil {
			arg2 = args[2].(repository.KeyboardPlate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyboardRepository_UpdatePlate_Call) Return(keyboardPlate *repository.KeyboardPlate, err error) *MockKeyboardRepository_UpdatePlate_Call {
	_c.Call.Return(keyboardPlate, err)
	return _c
}

func (_c *MockKeyboardRepository_UpdatePlate_Call) RunAndReturn(run func(ctx context.Context, keyboardID string, plate repository.KeyboardPlate) (*repository.KeyboardPlate, error)) *MockKeyboardRepository_UpdatePlate_Call {
	_c.Call.Return(run)
	return _c
}
