// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rogueserenity/kbdb/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeycapSetRepository creates a new instance of MockKeycapSetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeycapSetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeycapSetRepository {
	mock := &MockKeycapSetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeycapSetRepository is an autogenerated mock type for the KeycapSetRepository type
type MockKeycapSetRepository struct {
	mock.Mock
}

type MockKeycapSetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeycapSetRepository) EXPECT() *MockKeycapSetRepository_Expecter {
	return &MockKeycapSetRepository_Expecter{mock: &_m.Mock}
}

// AddKit provides a mock function for the type MockKeycapSetRepository
func (_mock *MockKeycapSetRepository) AddKit(ctx context.Context, setID string, kit repository.KeycapKit) (*repository.KeycapKit, error) {
	ret := _mock.Called(ctx, setID, kit)

	if len(ret) == 0 {
		panic("no return value specified for AddKit")
	}

	var r0 *repository.KeycapKit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeycapKit) (*repository.KeycapKit, error)); ok {
		return returnFunc(ctx, setID, kit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeycapKit) *repository.KeycapKit); ok {
		r0 = returnFunc(ctx, setID, kit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeycapKit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, repository.KeycapKit) error); ok {
		r1 = returnFunc(ctx, setID, kit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeycapSetRepository_AddKit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddKit'
type MockKeycapSetRepository_AddKit_Call struct {
	*mock.Call
}

// AddKit is a helper method to define mock.On call
//   - ctx context.Context
//   - setID string
//   - kit repository.KeycapKit
func (_e *MockKeycapSetRepository_Expecter) AddKit(ctx any, setID any, kit any) *MockKeycapSetRepository_AddKit_Call {
	return &MockKeycapSetRepository_AddKit_Call{Call: _e.mock.On("AddKit", ctx, setID, kit)}
}

func (_c *MockKeycapSetRepository_AddKit_Call) Run(run func(ctx context.Context, setID string, kit repository.KeycapKit)) *MockKeycapSetRepository_AddKit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 repository.KeycapKit
		if args[2] != nil {
			arg2 = args[2].(repository.KeycapKit)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeycapSetRepository_AddKit_Call) Return(keycapKit *repository.KeycapKit, err error) *MockKeycapSetRepository_AddKit_Call {
	_c.Call.Return(keycapKit, err)
	return _c
}

func (_c *MockKeycapSetRepository_AddKit_Call) RunAndReturn(run func(ctx context.Context, setID string, kit repository.KeycapKit) (*repository.KeycapKit, error)) *MockKeycapSetRepository_AddKit_Call {
	_c.Call.Return(run)
	return _c
}

// ClearKitImagePath provides a mock function for the type MockKeycapSetRepository
func (_mock *MockKeycapSetRepository) ClearKitImagePath(ctx context.Context, setID string, kitID string) (*repository.KeycapKitImageKey, error) {
	ret := _mock.Called(ctx, setID, kitID)

	if len(ret) == 0 {
		panic("no return value specified for ClearKitImagePath")
	}

	var r0 *repository.KeycapKitImageKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*repository.KeycapKitImageKey, error)); ok {
		return returnFunc(ctx, setID, kitID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *repository.KeycapKitImageKey); ok {
		r0 = returnFunc(ctx, setID, kitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeycapKitImageKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, setID, kitID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeycapSetRepository_ClearKitImagePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearKitImagePath'
type MockKeycapSetRepository_ClearKitImagePath_Call struct {
	*mock.Call
}

// ClearKitImagePath is a helper method to define mock.On call
//   - ctx context.Context
//   - setID string
//   - kitID string
func (_e *MockKeycapSetRepository_Expecter) ClearKitImagePath(ctx any, setID any, kitID any) *MockKeycapSetRepository_ClearKitImagePath_Call {
	return &MockKeycapSetRepository_ClearKitImagePath_Call{Call: _e.mock.On("ClearKitImagePath", ctx, setID, kitID)}
}

func (_c *MockKeycapSetRepository_ClearKitImagePath_Call) Run(run func(ctx context.Context, setID string, kitID string)) *MockKeycapSetRepository_ClearKitImagePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeycapSetRepository_ClearKitImagePath_Call) Return(keycapKitImageKey *repository.KeycapKitImageKey, err error) *MockKeycapSetRepository_ClearKitImagePath_Call {
	_c.Call.Return(keycapKitImageKey, err)
	return _c
}

func (_c *MockKeycapSetRepository_ClearKitImagePath_Call) RunAndReturn(run func(ctx context.Context, setID string, kitID string) (*repository.KeycapKitImageKey, error)) *MockKeycapSetRepository_ClearKitImagePath_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockKeycapSetRepository
func (_mock *MockKeycapSetRepository) Create(ctx context.Context, ks repository.KeycapSet) (*repository.KeycapSet, error) {
	ret := _mock.Called(ctx, ks)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.KeycapSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.KeycapSet) (*repository.KeycapSet, error)); ok {
		return returnFunc(ctx, ks)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.KeycapSet) *repository.KeycapSet); ok {
		r0 = returnFunc(ctx, ks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeycapSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.KeycapSet) error); ok {
		r1 = returnFunc(ctx, ks)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeycapSetRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKeycapSetRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ks repository.KeycapSet
func (_e *MockKeycapSetRepository_Expecter) Create(ctx any, ks any) *MockKeycapSetRepository_Create_Call {
	return &MockKeycapSetRepository_Create_Call{Call: _e.mock.On("Create", ctx, ks)}
}

func (_c *MockKeycapSetRepository_Create_Call) Run(run func(ctx context.Context, ks repository.KeycapSet)) *MockKeycapSetRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.KeycapSet
		if args[1] != nil {
			arg1 = args[1].(repository.KeycapSet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeycapSetRepository_Create_Call) Return(keycapSet *repository.KeycapSet, err error) *MockKeycapSetRepository_Create_Call {
	_c.Call.Return(keycapSet, err)
	return _c
}

func (_c *MockKeycapSetRepository_Create_Call) RunAndReturn(run func(ctx context.Context, ks repository.KeycapSet) (*repository.KeycapSet, error)) *MockKeycapSetRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockKeycapSetRepository
func (_mock *MockKeycapSetRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeycapSetRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockKeycapSetRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockKeycapSetRepository_Expecter) Delete(ctx any, id any) *MockKeycapSetRepository_Delete_Call {
	return &MockKeycapSetRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockKeycapSetRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockKeycapSetRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeycapSetRepository_Delete_Call) Return(err error) *MockKeycapSetRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeycapSetRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockKeycapSetRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteKit provides a mock function for the type MockKeycapSetRepository
func (_mock *MockKeycapSetRepository) DeleteKit(ctx context.Context, setID string, kitID string) error {
	ret := _mock.Called(ctx, setID, kitID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, setID, kitID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeycapSetRepository_DeleteKit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKit'
type MockKeycapSetRepository_DeleteKit_Call struct {
	*mock.Call
}

// DeleteKit is a helper method to define mock.On call
//   - ctx context.Context
//   - setID string
//   - kitID string
func (_e *MockKeycapSetRepository_Expecter) DeleteKit(ctx any, setID any, kitID any) *MockKeycapSetRepository_DeleteKit_Call {
	return &MockKeycapSetRepository_DeleteKit_Call{Call: _e.mock.On("DeleteKit", ctx, setID, kitID)}
}

func (_c *MockKeycapSetRepository_DeleteKit_Call) Run(run func(ctx context.Context, setID string, kitID string)) *MockKeycapSetRepository_DeleteKit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeycapSetRepository_DeleteKit_Call) Return(err error) *MockKeycapSetRepository_DeleteKit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeycapSetRepository_DeleteKit_Call) RunAndReturn(run func(ctx context.Context, setID string, kitID string) error) *MockKeycapSetRepository_DeleteKit_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockKeycapSetRepository
func (_mock *MockKeycapSetRepository) Get(ctx context.Context, ownerID string, id string) (*repository.KeycapSet, error) {
	ret := _mock.Called(ctx, ownerID, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repository.KeycapSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*repository.KeycapSet, error)); ok {
		return returnFunc(ctx, ownerID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *repository.KeycapSet); ok {
		r0 = returnFunc(ctx, ownerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeycapSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ownerID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeycapSetRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockKeycapSetRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - id string
func (_e *MockKeycapSetRepository_Expecter) Get(ctx any, ownerID any, id any) *MockKeycapSetRepository_Get_Call {
	return &MockKeycapSetRepository_Get_Call{Call: _e.mock.On("Get", ctx, ownerID, id)}
}

func (_c *MockKeycapSetRepository_Get_Call) Run(run func(ctx context.Context, ownerID string, id string)) *MockKeycapSetRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeycapSetRepository_Get_Call) Return(keycapSet *repository.KeycapSet, err error) *MockKeycapSetRepository_Get_Call {
	_c.Call.Return(keycapSet, err)
	return _c
}

func (_c *MockKeycapSetRepository_Get_Call) RunAndReturn(run func(ctx context.Context, ownerID string, id string) (*repository.KeycapSet, error)) *MockKeycapSetRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockKeycapSetRepository
func (_mock *MockKeycapSetRepository) List(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string) ([]repository.KeycapSet, string, error) {
	ret := _mock.Called(ctx, ownerID, visibilities, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []repository.KeycapSet
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []repository.Visibility, int, string) ([]repository.KeycapSet, string, error)); ok {
		return returnFunc(ctx, ownerID, visibilities, limit, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []repository.Visibility, int, string) []repository.KeycapSet); ok {
		r0 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.KeycapSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []repository.Visibility, int, string) string); ok {
		r1 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []repository.Visibility, int, string) error); ok {
		r2 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockKeycapSetRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockKeycapSetRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - visibilities []repository.Visibility
//   - limit int
//   - cursor string
func (_e *MockKeycapSetRepository_Expecter) List(ctx any, ownerID any, visibilities any, limit any, cursor any) *MockKeycapSetRepository_List_Call {
	return &MockKeycapSetRepository_List_Call{Call: _e.mock.On("List", ctx, ownerID, visibilities, limit, cursor)}
}

func (_c *MockKeycapSetRepository_List_Call) Run(run func(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string)) *MockKeycapSetRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []repository.Visibility
		if args[2] != nil {
			arg2 = args[2].([]repository.Visibility)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockKeycapSetRepository_List_Call) Return(sets []repository.KeycapSet, nextCursor string, err error) *MockKeycapSetRepository_List_Call {
	_c.Call.Return(sets, nextCursor, err)
	return _c
}

func (_c *MockKeycapSetRepository_List_Call) RunAndReturn(run func(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string) ([]repository.KeycapSet, string, error)) *MockKeycapSetRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SetKitImagePath provides a mock function for the type MockKeycapSetRepository
func (_mock *MockKeycapSetRepository) SetKitImagePath(ctx context.Context, setID string, kitID string, key repository.KeycapKitImageKey) (*repository.KeycapKit, error) {
	ret := _mock.Called(ctx, setID, kitID, key)

	if len(ret) == 0 {
		panic("no return value specified for SetKitImagePath")
	}

	var r0 *repository.KeycapKit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, repository.KeycapKitImageKey) (*repository.KeycapKit, error)); ok {
		return returnFunc(ctx, setID, kitID, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, repository.KeycapKitImageKey) *repository.KeycapKit); ok {
		r0 = returnFunc(ctx, setID, kitID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeycapKit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, repository.KeycapKitImageKey) error); ok {
		r1 = returnFunc(ctx, setID, kitID, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeycapSetRepository_SetKitImagePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetKitImagePath'
type MockKeycapSetRepository_SetKitImagePath_Call struct {
	*mock.Call
}

// SetKitImagePath is a helper method to define mock.On call
//   - ctx context.Context
//   - setID string
//   - kitID string
//   - key repository.KeycapKitImageKey
func (_e *MockKeycapSetRepository_Expecter) SetKitImagePath(ctx any, setID any, kitID any, key any) *MockKeycapSetRepository_SetKitImagePath_Call {
	return &MockKeycapSetRepository_SetKitImagePath_Call{Call: _e.mock.On("SetKitImagePath", ctx, setID, kitID, key)}
}

func (_c *MockKeycapSetRepository_SetKitImagePath_Call) Run(run func(ctx context.Context, setID string, kitID string, key repository.KeycapKitImageKey)) *MockKeycapSetRepository_SetKitImagePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 repository.KeycapKitImageKey
		if args[3] != nil {
			arg3 = args[3].(repository.KeycapKitImageKey)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockKeycapSetRepository_SetKitImagePath_Call) Return(keycapKit *repository.KeycapKit, err error) *MockKeycapSetRepository_SetKitImagePath_Call {
	_c.Call.Return(keycapKit, err)
	return _c
}

func (_c *MockKeycapSetRepository_SetKitImagePath_Call) RunAndReturn(run func(ctx context.Context, setID string, kitID string, key repository.KeycapKitImageKey) (*repository.KeycapKit, error)) *MockKeycapSetRepository_SetKitImagePath_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockKeycapSetRepository
func (_mock *MockKeycapSetRepository) Update(ctx context.Context, ks repository.KeycapSet) (*repository.KeycapSet, error) {
	ret := _mock.Called(ctx, ks)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.KeycapSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.KeycapSet) (*repository.KeycapSet, error)); ok {
		return returnFunc(ctx, ks)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.KeycapSet) *repository.KeycapSet); ok {
		r0 = returnFunc(ctx, ks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeycapSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.KeycapSet) error); ok {
		r1 = returnFunc(ctx, ks)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeycapSetRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockKeycapSetRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ks repository.KeycapSet
func (_e *MockKeycapSetRepository_Expecter) Update(ctx any, ks any) *MockKeycapSetRepository_Update_Call {
	return &MockKeycapSetRepository_Update_Call{Call: _e.mock.On("Update", ctx, ks)}
}

func (_c *MockKeycapSetRepository_Update_Call) Run(run func(ctx context.Context, ks repository.KeycapSet)) *MockKeycapSetRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.KeycapSet
		if args[1] != nil {
			arg1 = args[1].(repository.KeycapSet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeycapSetRepository_Update_Call) Return(keycapSet *repository.KeycapSet, err error) *MockKeycapSetRepository_Update_Call {
	_c.Call.Return(keycapSet, err)
	return _c
}

func (_c *MockKeycapSetRepository_Update_Call) RunAndReturn(run func(ctx context.Context, ks repository.KeycapSet) (*repository.KeycapSet, error)) *MockKeycapSetRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateKit provides a mock function for the type MockKeycapSetRepository
func (_mock *MockKeycapSetRepository) UpdateKit(ctx context.Context, setID string, kit repository.KeycapKit) (*repository.KeycapKit, error) {
	ret := _mock.Called(ctx, setID, kit)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKit")
	}

	var r0 *repository.KeycapKit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeycapKit) (*repository.KeycapKit, error)); ok {
		return returnFunc(ctx, setID, kit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, repository.KeycapKit) *repository.KeycapKit); ok {
		r0 = returnFunc(ctx, setID, kit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.KeycapKit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, repository.KeycapKit) error); ok {
		r1 = returnFunc(ctx, setID, kit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeycapSetRepository_UpdateKit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateKit'
type MockKeycapSetRepository_UpdateKit_Call struct {
	*mock.Call
}

// UpdateKit is a helper method to define mock.On call
//   - ctx context.Context
//   - setID string
//   - kit repository.KeycapKit
func (_e *MockKeycapSetRepository_Expecter) UpdateKit(ctx any, setID any, kit any) *MockKeycapSetRepository_UpdateKit_Call {
	return &MockKeycapSetRepository_UpdateKit_Call{Call: _e.mock.On("UpdateKit", ctx, setID, kit)}
}

func (_c *MockKeycapSetRepository_UpdateKit_Call) Run(run func(ctx context.Context, setID string, kit repository.KeycapKit)) *MockKeycapSetRepository_UpdateKit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 repository.KeycapKit
		if args[2] != nil {
			arg2 = args[2].(repository.KeycapKit)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeycapSetRepository_UpdateKit_Call) Return(keycapKit *repository.KeycapKit, err error) *MockKeycapSetRepository_UpdateKit_Call {
	_c.Call.Return(keycapKit, err)
	return _c
}

func (_c *MockKeycapSetRepository_UpdateKit_Call) RunAndReturn(run func(ctx context.Context, setID string, kit repository.KeycapKit) (*repository.KeycapKit, error)) *MockKeycapSetRepository_UpdateKit_Call {
	_c.Call.Return(run)
	return _c
}
