// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rogueserenity/kbdb/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSwitchRepository creates a new instance of MockSwitchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSwitchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSwitchRepository {
	mock := &MockSwitchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSwitchRepository is an autogenerated mock type for the SwitchRepository type
type MockSwitchRepository struct {
	mock.Mock
}

type MockSwitchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSwitchRepository) EXPECT() *MockSwitchRepository_Expecter {
	return &MockSwitchRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSwitchRepository
func (_mock *MockSwitchRepository) Create(ctx context.Context, sw repository.Switch) (*repository.Switch, error) {
	ret := _mock.Called(ctx, sw)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.Switch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Switch) (*repository.Switch, error)); ok {
		return returnFunc(ctx, sw)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Switch) *repository.Switch); ok {
		r0 = returnFunc(ctx, sw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Switch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Switch) error); ok {
		r1 = returnFunc(ctx, sw)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSwitchRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSwitchRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sw repository.Switch
func (_e *MockSwitchRepository_Expecter) Create(ctx any, sw any) *MockSwitchRepository_Create_Call {
	return &MockSwitchRepository_Create_Call{Call: _e.mock.On("Create", ctx, sw)}
}

func (_c *MockSwitchRepository_Create_Call) Run(run func(ctx context.Context, sw repository.Switch)) *MockSwitchRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Switch
		if args[1] != nil {
			arg1 = args[1].(repository.Switch)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSwitchRepository_Create_Call) Return(switchParam *repository.Switch, err error) *MockSwitchRepository_Create_Call {
	_c.Call.Return(switchParam, err)
	return _c
}

func (_c *MockSwitchRepository_Create_Call) RunAndReturn(run func(ctx context.Context, sw repository.Switch) (*repository.Switch, error)) *MockSwitchRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSwitchRepository
func (_mock *MockSwitchRepository) Get(ctx context.Context, ownerID string, id string) (*repository.Switch, error) {
	ret := _mock.Called(ctx, ownerID, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repository.Switch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*repository.Switch, error)); ok {
		return returnFunc(ctx, ownerID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *repository.Switch); ok {
		r0 = returnFunc(ctx, ownerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Switch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ownerID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSwitchRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSwitchRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - id string
func (_e *MockSwitchRepository_Expecter) Get(ctx any, ownerID any, id any) *MockSwitchRepository_Get_Call {
	return &MockSwitchRepository_Get_Call{Call: _e.mock.On("Get", ctx, ownerID, id)}
}

func (_c *MockSwitchRepository_Get_Call) Run(run func(ctx context.Context, ownerID string, id string)) *MockSwitchRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSwitchRepository_Get_Call) Return(switchParam *repository.Switch, err error) *MockSwitchRepository_Get_Call {
	_c.Call.Return(switchParam, err)
	return _c
}

func (_c *MockSwitchRepository_Get_Call) RunAndReturn(run func(ctx context.Context, ownerID string, id string) (*repository.Switch, error)) *MockSwitchRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSwitchRepository
func (_mock *MockSwitchRepository) List(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string) ([]repository.Switch, string, error) {
	ret := _mock.Called(ctx, ownerID, visibilities, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []repository.Switch
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []repository.Visibility, int, string) ([]repository.Switch, string, error)); ok {
		return returnFunc(ctx, ownerID, visibilities, limit, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []repository.Visibility, int, string) []repository.Switch); ok {
		r0 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Switch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []repository.Visibility, int, string) string); ok {
		r1 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []repository.Visibility, int, string) error); ok {
		r2 = returnFunc(ctx, ownerID, visibilities, limit, cursor)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSwitchRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSwitchRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - visibilities []repository.Visibility
//   - limit int
//   - cursor string
func (_e *MockSwitchRepository_Expecter) List(ctx any, ownerID any, visibilities any, limit any, cursor any) *MockSwitchRepository_List_Call {
	return &MockSwitchRepository_List_Call{Call: _e.mock.On("List", ctx, ownerID, visibilities, limit, cursor)}
}

func (_c *MockSwitchRepository_List_Call) Run(run func(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string)) *MockSwitchRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []repository.Visibility
		if args[2] != nil {
			arg2 = args[2].([]repository.Visibility)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSwitchRepository_List_Call) Return(switches []repository.Switch, nextCursor string, err error) *MockSwitchRepository_List_Call {
	_c.Call.Return(switches, nextCursor, err)
	return _c
}

func (_c *MockSwitchRepository_List_Call) RunAndReturn(run func(ctx context.Context, ownerID string, visibilities []repository.Visibility, limit int, cursor string) ([]repository.Switch, string, error)) *MockSwitchRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
