// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Visibility.
const (
	Authenticated Visibility = "authenticated"
	Private       Visibility = "private"
	Public        Visibility = "public"
)

// Valid indicates whether the value is a known member of the Visibility enum.
func (e Visibility) Valid() bool {
	switch e {
	case Authenticated:
		return true
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// Defines values for CreateBuildImageJSONBodyContentType.
const (
	CreateBuildImageJSONBodyContentTypeImagejpeg CreateBuildImageJSONBodyContentType = "image/jpeg"
	CreateBuildImageJSONBodyContentTypeImagepng  CreateBuildImageJSONBodyContentType = "image/png"
	CreateBuildImageJSONBodyContentTypeImagewebp CreateBuildImageJSONBodyContentType = "image/webp"
)

// Valid indicates whether the value is a known member of the CreateBuildImageJSONBodyContentType enum.
func (e CreateBuildImageJSONBodyContentType) Valid() bool {
	switch e {
	case CreateBuildImageJSONBodyContentTypeImagejpeg:
		return true
	case CreateBuildImageJSONBodyContentTypeImagepng:
		return true
	case CreateBuildImageJSONBodyContentTypeImagewebp:
		return true
	default:
		return false
	}
}

// Defines values for SetKeycapKitImageJSONBodyContentType.
const (
	SetKeycapKitImageJSONBodyContentTypeImagejpeg SetKeycapKitImageJSONBodyContentType = "image/jpeg"
	SetKeycapKitImageJSONBodyContentTypeImagepng  SetKeycapKitImageJSONBodyContentType = "image/png"
	SetKeycapKitImageJSONBodyContentTypeImagewebp SetKeycapKitImageJSONBodyContentType = "image/webp"
)

// Valid indicates whether the value is a known member of the SetKeycapKitImageJSONBodyContentType enum.
func (e SetKeycapKitImageJSONBodyContentType) Valid() bool {
	switch e {
	case SetKeycapKitImageJSONBodyContentTypeImagejpeg:
		return true
	case SetKeycapKitImageJSONBodyContentTypeImagepng:
		return true
	case SetKeycapKitImageJSONBodyContentTypeImagewebp:
		return true
	default:
		return false
	}
}

// Build defines model for Build.
type Build struct {
	BuildDate     *openapi_types.Date `json:"build_date,omitempty"`
	CaseMountType *BuildCaseMountType `json:"case_mount_type,omitempty"`
	Foam          *bool               `json:"foam,omitempty"`
	Id            string              `json:"id"`

	// Images Managed via the dedicated image endpoints below, not via PUT on the build itself — see POST/DELETE .../builds/{id}/images[/{imageId}].
	Images *[]BuildImage `json:"images,omitempty"`

	// Keyboard ID of a Keyboard resource.
	Keyboard   string                 `json:"keyboard"`
	KeycapKits *[]BuildKeycapKitEntry `json:"keycap_kits,omitempty"`
	Notes      *string                `json:"notes,omitempty"`

	// Plate Which of the keyboard's design.plates options is installed.
	Plate    *string             `json:"plate,omitempty"`
	Stabs    *BuildStabs         `json:"stabs,omitempty"`
	Switches *[]BuildSwitchEntry `json:"switches,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility *Visibility `json:"visibility,omitempty"`
}

// BuildCaseMountType defines model for BuildCaseMountType.
type BuildCaseMountType struct {
	// Durometer Open vocabulary — validated against the "build_durometer" lookup at request time. Only meaningful when the chosen mount type supports it (see the build_case_mount_type lookup's supports_durometer flag).
	Durometer *string `json:"durometer,omitempty"`

	// Type Open vocabulary — validated against the "build_case_mount_type" lookup at request time.
	Type *string `json:"type,omitempty"`
}

// BuildImage defines model for BuildImage.
type BuildImage struct {
	// ImageId Server-generated identifier for this image, unique within the build.
	ImageId string `json:"image_id"`

	// Url A freshly-minted, short-lived presigned S3 GET URL. Generated new on every fetch of the build — do not cache or persist this value, it expires.
	Url string `json:"url"`
}

// BuildInput defines model for BuildInput.
type BuildInput struct {
	BuildDate     *openapi_types.Date `json:"build_date,omitempty"`
	CaseMountType *BuildCaseMountType `json:"case_mount_type,omitempty"`
	Foam          *bool               `json:"foam,omitempty"`

	// Keyboard ID of a Keyboard resource.
	Keyboard   string                 `json:"keyboard"`
	KeycapKits *[]BuildKeycapKitEntry `json:"keycap_kits,omitempty"`
	Notes      *string                `json:"notes,omitempty"`

	// Plate Which of the keyboard's design.plates options is installed.
	Plate    *string             `json:"plate,omitempty"`
	Stabs    *BuildStabs         `json:"stabs,omitempty"`
	Switches *[]BuildSwitchEntry `json:"switches,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility *Visibility `json:"visibility,omitempty"`
}

// BuildKeycapKitEntry defines model for BuildKeycapKitEntry.
type BuildKeycapKitEntry struct {
	// KeycapSet ID of a KeycapSet resource.
	KeycapSet string `json:"keycap_set"`

	// Kit kit_id of one of that keycap set's kits (see KeycapKit.kit_id).
	Kit string `json:"kit"`
}

// BuildListPage defines model for BuildListPage.
type BuildListPage struct {
	Items      *[]BuildSummary `json:"items,omitempty"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// BuildStabs defines model for BuildStabs.
type BuildStabs struct {
	// MountType Open vocabulary — validated against the "build_stabilizer_mount_type" lookup at request time.
	MountType *string `json:"mount_type,omitempty"`

	// Name Open vocabulary — validated against the "stabs" lookup at request time.
	Name *string `json:"name,omitempty"`

	// Price A price in the collection's tracking currency.
	Price *Money `json:"price,omitempty"`
}

// BuildSummary Includes a denormalized keyboard brand/name so a build is recognizable in a list view without a follow-up request.
type BuildSummary struct {
	BuildDate *openapi_types.Date `json:"build_date,omitempty"`
	Id        *string             `json:"id,omitempty"`

	// Image First entry of images, if any (a freshly-minted presigned URL, same as on the full Build resource).
	Image    *BuildImage `json:"image,omitempty"`
	Keyboard *struct {
		Brand *string `json:"brand,omitempty"`
		Name  *string `json:"name,omitempty"`
	} `json:"keyboard,omitempty"`
}

// BuildSwitchEntry defines model for BuildSwitchEntry.
type BuildSwitchEntry struct {
	Count int `json:"count"`

	// Switch ID of a Switch resource.
	Switch string `json:"switch"`
}

// Keyboard defines model for Keyboard.
type Keyboard struct {
	Brand  string          `json:"brand"`
	Design *KeyboardDesign `json:"design,omitempty"`
	Id     string          `json:"id"`

	// Layout Open vocabulary — validated against the "layout" lookup at request time, including that the chosen layout is valid for the keyboard's size.
	Layout *string      `json:"layout,omitempty"`
	Name   string       `json:"name"`
	Notes  *string      `json:"notes,omitempty"`
	Pcb    *KeyboardPcb `json:"pcb,omitempty"`

	// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
	Purchase *Purchase `json:"purchase,omitempty"`

	// Size Open vocabulary — validated against the "size" lookup at request time.
	Size *string `json:"size,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility *Visibility `json:"visibility,omitempty"`
}

// KeyboardDesign defines model for KeyboardDesign.
type KeyboardDesign struct {
	// BottomCase A physical part described by material and color.
	BottomCase *MaterialColor `json:"bottom_case,omitempty"`
	Plates     *[]string      `json:"plates,omitempty"`

	// TopCase A physical part described by material and color.
	TopCase *MaterialColor `json:"top_case,omitempty"`

	// Weight A physical part described by material and color.
	Weight *MaterialColor `json:"weight,omitempty"`
}

// KeyboardInput defines model for KeyboardInput.
type KeyboardInput struct {
	Brand  string          `json:"brand"`
	Design *KeyboardDesign `json:"design,omitempty"`

	// Layout Open vocabulary — validated against the "layout" lookup at request time, including that the chosen layout is valid for the keyboard's size.
	Layout *string      `json:"layout,omitempty"`
	Name   string       `json:"name"`
	Notes  *string      `json:"notes,omitempty"`
	Pcb    *KeyboardPcb `json:"pcb,omitempty"`

	// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
	Purchase *Purchase `json:"purchase,omitempty"`

	// Size Open vocabulary — validated against the "size" lookup at request time.
	Size *string `json:"size,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility *Visibility `json:"visibility,omitempty"`
}

// KeyboardListPage defines model for KeyboardListPage.
type KeyboardListPage struct {
	Items      *[]KeyboardSummary `json:"items,omitempty"`
	NextCursor *string            `json:"next_cursor,omitempty"`
}

// KeyboardPcb defines model for KeyboardPcb.
type KeyboardPcb struct {
	// Assembly Open vocabulary — validated against the "keyboard_pcb_assembly_type" lookup at request time.
	Assembly *string `json:"assembly,omitempty"`

	// Connectivity Open vocabulary — validated against the "keyboard_pcb_connectivity_type" lookup at request time.
	Connectivity *string `json:"connectivity,omitempty"`

	// Firmware Open vocabulary — validated against the "firmware" lookup at request time.
	Firmware  *string  `json:"firmware,omitempty"`
	Thickness *float64 `json:"thickness,omitempty"`
}

// KeyboardSummary Reduced shape returned in list responses.
type KeyboardSummary struct {
	Brand       *string `json:"brand,omitempty"`
	Id          *string `json:"id,omitempty"`
	Layout      *string `json:"layout,omitempty"`
	Name        *string `json:"name,omitempty"`
	OrderStatus *string `json:"order_status,omitempty"`
	Size        *string `json:"size,omitempty"`
}

// KeycapKit defines model for KeycapKit.
type KeycapKit struct {
	// Image Managed via the dedicated image endpoint, not via PUT on the kit itself — see POST/DELETE .../keycap-sets/{id}/kits/{kitId}/image.
	Image *KeycapKitImage `json:"image,omitempty"`

	// KitId Server-generated identifier for this kit, unique within the keycap set.
	KitId string `json:"kit_id"`

	// Name e.g. "Base", "Extension", "Accents".
	Name string `json:"name"`

	// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
	Purchase *Purchase `json:"purchase,omitempty"`
}

// KeycapKitImage defines model for KeycapKitImage.
type KeycapKitImage struct {
	// Url A freshly-minted, short-lived presigned S3 GET URL. Generated new on every fetch — do not cache or persist this value, it expires. A kit has at most one image (its vendor render/product shot) — see POST/DELETE .../kits/{kitId}/image.
	Url string `json:"url"`
}

// KeycapKitInput defines model for KeycapKitInput.
type KeycapKitInput struct {
	// Name e.g. "Base", "Extension", "Accents".
	Name string `json:"name"`

	// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
	Purchase *Purchase `json:"purchase,omitempty"`
}

// KeycapKitListPage Not paginated (limit/cursor) like the top-level entity list endpoints — a keycap set's kits are few enough in practice that the full list is always returned in one response.
type KeycapKitListPage struct {
	Items *[]KeycapKit `json:"items,omitempty"`
}

// KeycapSet defines model for KeycapSet.
type KeycapSet struct {
	Brand string `json:"brand"`
	Id    string `json:"id"`

	// Kits Managed via the dedicated kit endpoints below, not via PUT on the set itself — see POST/GET/PUT/DELETE .../keycap-sets/{id}/kits[/{kitId}].
	Kits *[]KeycapKit `json:"kits,omitempty"`

	// Material Open vocabulary — validated against the "keycap_material" lookup at request time.
	Material *string `json:"material,omitempty"`
	Name     string  `json:"name"`
	Notes    *string `json:"notes,omitempty"`

	// Profile Open vocabulary — validated against the "keycap_profile" lookup at request time.
	Profile *string `json:"profile,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility *Visibility `json:"visibility,omitempty"`
}

// KeycapSetInput defines model for KeycapSetInput.
type KeycapSetInput struct {
	Brand string `json:"brand"`

	// Material Open vocabulary — validated against the "keycap_material" lookup at request time.
	Material *string `json:"material,omitempty"`
	Name     string  `json:"name"`
	Notes    *string `json:"notes,omitempty"`

	// Profile Open vocabulary — validated against the "keycap_profile" lookup at request time.
	Profile *string `json:"profile,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility *Visibility `json:"visibility,omitempty"`
}

// KeycapSetListPage defines model for KeycapSetListPage.
type KeycapSetListPage struct {
	Items      *[]KeycapSetSummary `json:"items,omitempty"`
	NextCursor *string             `json:"next_cursor,omitempty"`
}

// KeycapSetSummary defines model for KeycapSetSummary.
type KeycapSetSummary struct {
	Brand   *string `json:"brand,omitempty"`
	Id      *string `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Profile *string `json:"profile,omitempty"`
}

// Lookup A lookup category's approved values. "values" is usually an array of plain strings, but some categories (layout, case_mount_type) use objects to attach per-value constraints/flags — see model/lookup_seed.json.
type Lookup struct {
	Category string        `json:"category"`
	Values   []interface{} `json:"values"`
}

// LookupInput defines model for LookupInput.
type LookupInput struct {
	Values []interface{} `json:"values"`
}

// MaterialColor A physical part described by material and color.
type MaterialColor struct {
	// Color Free text.
	Color *string `json:"color,omitempty"`

	// Material Open vocabulary — validated against the relevant *_material lookup at request time.
	Material *string `json:"material,omitempty"`
}

// Money A price in the collection's tracking currency.
type Money = float64

// Problem RFC 9457 Problem Details.
type Problem struct {
	Detail        *string `json:"detail,omitempty"`
	Instance      *string `json:"instance,omitempty"`
	InvalidParams *[]struct {
		AllowedValues *[]string `json:"allowed_values,omitempty"`
		Name          *string   `json:"name,omitempty"`
		Reason        *string   `json:"reason,omitempty"`
	} `json:"invalid_params,omitempty"`
	Status int    `json:"status"`
	Title  string `json:"title"`
	Type   string `json:"type"`
}

// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
type Purchase struct {
	DeliveryDate *openapi_types.Date `json:"delivery_date,omitempty"`
	OrderDate    *openapi_types.Date `json:"order_date,omitempty"`

	// OrderStatus Open vocabulary — validated against the "order_status" lookup at request time.
	OrderStatus *string `json:"order_status,omitempty"`

	// Price A price in the collection's tracking currency.
	Price *Money `json:"price,omitempty"`

	// Vendor Open vocabulary — validated against the "vendor" lookup at request time.
	Vendor *string `json:"vendor,omitempty"`
}

// Switch defines model for Switch.
type Switch struct {
	Brand        string          `json:"brand"`
	FactoryLubed *bool           `json:"factory_lubed,omitempty"`
	Force        *SwitchForce    `json:"force,omitempty"`
	Id           string          `json:"id"`
	Manufacturer *string         `json:"manufacturer,omitempty"`
	Material     *SwitchMaterial `json:"material,omitempty"`
	Name         string          `json:"name"`
	Notes        *string         `json:"notes,omitempty"`

	// Pins PCB mount pin count.
	Pins *int `json:"pins,omitempty"`

	// Purchase Simpler purchase shape than Purchase — switches aren't tracked with order/delivery dates.
	Purchase *SwitchPurchase `json:"purchase,omitempty"`
	Spring   *SwitchSpring   `json:"spring,omitempty"`

	// Type Open vocabulary — validated against the "switch_type" lookup at request time.
	Type string `json:"type"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// SwitchForce defines model for SwitchForce.
type SwitchForce struct {
	// Actuation Actuation force in grams (nominal value).
	Actuation *float64 `json:"actuation,omitempty"`

	// BottomOut Bottom-out force in grams (nominal value).
	BottomOut *float64 `json:"bottom_out,omitempty"`
}

// SwitchInput defines model for SwitchInput.
type SwitchInput struct {
	Brand        string          `json:"brand"`
	FactoryLubed *bool           `json:"factory_lubed,omitempty"`
	Force        *SwitchForce    `json:"force,omitempty"`
	Manufacturer *string         `json:"manufacturer,omitempty"`
	Material     *SwitchMaterial `json:"material,omitempty"`
	Name         string          `json:"name"`
	Notes        *string         `json:"notes,omitempty"`

	// Pins PCB mount pin count.
	Pins *int `json:"pins,omitempty"`

	// Purchase Simpler purchase shape than Purchase — switches aren't tracked with order/delivery dates.
	Purchase *SwitchPurchase `json:"purchase,omitempty"`
	Spring   *SwitchSpring   `json:"spring,omitempty"`

	// Type Open vocabulary — validated against the "switch_type" lookup at request time.
	Type string `json:"type"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// SwitchListPage defines model for SwitchListPage.
type SwitchListPage struct {
	Items      *[]SwitchSummary `json:"items,omitempty"`
	NextCursor *string          `json:"next_cursor,omitempty"`
}

// SwitchMaterial defines model for SwitchMaterial.
type SwitchMaterial struct {
	// BottomHousing Open vocabulary — validated against the "switch_material" lookup at request time.
	BottomHousing *string `json:"bottom_housing,omitempty"`

	// Stem Open vocabulary — validated against the "switch_material" lookup at request time.
	Stem *string `json:"stem,omitempty"`

	// TopHousing Open vocabulary — validated against the "switch_material" lookup at request time.
	TopHousing *string `json:"top_housing,omitempty"`
}

// SwitchPurchase Simpler purchase shape than Purchase — switches aren't tracked with order/delivery dates.
type SwitchPurchase struct {
	// Price A price in the collection's tracking currency.
	Price    *Money `json:"price,omitempty"`
	Quantity *int   `json:"quantity,omitempty"`

	// Vendor Open vocabulary — validated against the "vendor" lookup at request time.
	Vendor *string `json:"vendor,omitempty"`
}

// SwitchSpring defines model for SwitchSpring.
type SwitchSpring struct {
	// Material Open vocabulary — validated against the "switch_spring_material" lookup at request time.
	Material *string `json:"material,omitempty"`

	// PreTravel Pre-travel distance in mm.
	PreTravel *float64 `json:"pre_travel,omitempty"`

	// TotalTravel Total travel distance in mm.
	TotalTravel *float64 `json:"total_travel,omitempty"`
}

// SwitchSummary defines model for SwitchSummary.
type SwitchSummary struct {
	Brand *string `json:"brand,omitempty"`
	Id    *string `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`

	// Type Open vocabulary — validated against the "switch_type" lookup at request time.
	Type *string `json:"type,omitempty"`
}

// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
type Visibility string

// Cursor defines model for Cursor.
type Cursor = string

// Id defines model for Id.
type Id = string

// Limit defines model for Limit.
type Limit = int

// UserId defines model for UserId.
type UserId = openapi_types.UUID

// ConflictResponse RFC 9457 Problem Details.
type ConflictResponse = Problem

// ForbiddenResponse RFC 9457 Problem Details.
type ForbiddenResponse = Problem

// NotFoundResponse RFC 9457 Problem Details.
type NotFoundResponse = Problem

// ProblemResponse RFC 9457 Problem Details.
type ProblemResponse = Problem

// ListBuildsParams defines parameters for ListBuilds.
type ListBuildsParams struct {
	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateBuildImageJSONBody defines parameters for CreateBuildImage.
type CreateBuildImageJSONBody struct {
	ContentType CreateBuildImageJSONBodyContentType `json:"content_type"`
}

// CreateBuildImageJSONBodyContentType defines parameters for CreateBuildImage.
type CreateBuildImageJSONBodyContentType string

// ListKeyboardsParams defines parameters for ListKeyboards.
type ListKeyboardsParams struct {
	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListKeycapSetsParams defines parameters for ListKeycapSets.
type ListKeycapSetsParams struct {
	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// SetKeycapKitImageJSONBody defines parameters for SetKeycapKitImage.
type SetKeycapKitImageJSONBody struct {
	ContentType SetKeycapKitImageJSONBodyContentType `json:"content_type"`
}

// SetKeycapKitImageJSONBodyContentType defines parameters for SetKeycapKitImage.
type SetKeycapKitImageJSONBodyContentType string

// ListSwitchesParams defines parameters for ListSwitches.
type ListSwitchesParams struct {
	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateLookupJSONRequestBody defines body for CreateLookup for application/json ContentType.
type CreateLookupJSONRequestBody = LookupInput

// ReplaceLookupJSONRequestBody defines body for ReplaceLookup for application/json ContentType.
type ReplaceLookupJSONRequestBody = LookupInput

// CreateBuildJSONRequestBody defines body for CreateBuild for application/json ContentType.
type CreateBuildJSONRequestBody = BuildInput

// UpdateBuildJSONRequestBody defines body for UpdateBuild for application/json ContentType.
type UpdateBuildJSONRequestBody = BuildInput

// CreateBuildImageJSONRequestBody defines body for CreateBuildImage for application/json ContentType.
type CreateBuildImageJSONRequestBody CreateBuildImageJSONBody

// CreateKeyboardJSONRequestBody defines body for CreateKeyboard for application/json ContentType.
type CreateKeyboardJSONRequestBody = KeyboardInput

// UpdateKeyboardJSONRequestBody defines body for UpdateKeyboard for application/json ContentType.
type UpdateKeyboardJSONRequestBody = KeyboardInput

// CreateKeycapSetJSONRequestBody defines body for CreateKeycapSet for application/json ContentType.
type CreateKeycapSetJSONRequestBody = KeycapSetInput

// UpdateKeycapSetJSONRequestBody defines body for UpdateKeycapSet for application/json ContentType.
type UpdateKeycapSetJSONRequestBody = KeycapSetInput

// CreateKeycapKitJSONRequestBody defines body for CreateKeycapKit for application/json ContentType.
type CreateKeycapKitJSONRequestBody = KeycapKitInput

// UpdateKeycapKitJSONRequestBody defines body for UpdateKeycapKit for application/json ContentType.
type UpdateKeycapKitJSONRequestBody = KeycapKitInput

// SetKeycapKitImageJSONRequestBody defines body for SetKeycapKitImage for application/json ContentType.
type SetKeycapKitImageJSONRequestBody SetKeycapKitImageJSONBody

// CreateSwitchJSONRequestBody defines body for CreateSwitch for application/json ContentType.
type CreateSwitchJSONRequestBody = SwitchInput

// UpdateSwitchJSONRequestBody defines body for UpdateSwitch for application/json ContentType.
type UpdateSwitchJSONRequestBody = SwitchInput

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3vcts4su+rdPHeKtv30pJnkr231vMpk2Sy3mQmrtjZ/ZC4XBDZkjAmAQ4A2tGkXHUe4jzheZJTaAAk",
	"JZL6Y8n/9uynxBIJNLobv/4DdOt7lMi8kAKF0dHx96hgiuVoUNFfr0ulpbL/S1EniheGSxEdRx8L9keJ",
	"ULAJF8x+Bgk9CWMlc2BQKLzmstSgUBdSaNzTIPCbuXSPDaI44nacP0pUsyiOBMsxOo7ct1Ec6WSKObPz",
	"mllhv9FGcTGJbm/j6CRt03OG6hrV4QQFKmYwBZ6iMHzMUcFYKjBTtKTIUiVYTV4wM63n5mkURwr/KLnC",
	"NDo2qsTldHzgOTdtUn5l33he5iDKfIQK5Bi4wVyDkaDQlEr0LT6j8ZpzpjhmZWai4x+P4ih340bHPxzZ",
	"v7jwf8WBNC4MTlARbZ81qi4+vZYTwY0EXY5+x8TA/ufPJ28OLJGWQ5bQPQ3yRqAawIn9kGvImUmmqOkJ",
	"VpqpZWxCTE5YlqFyb4QhY8/rP0rUBrgGNmFcaGM/5oqeTGSWYWIpokm4AcsBDQxSPh6jQmGg1KiWDMXc",
	"E3u6MdgxKGSp9lwGKbJZYH14HqZMA34rMp5wk81AT5nCFG64mdJcbkGwL1VMasNAF5jwMU9opNgPOnYj",
	"2o8sWT2j/Nd//CdIM0V1wzUCg5dHL2MQ0tB/X8RWIdi15CkovEaWcTFxwzLhRsZvXBsNo9KuXewZP8/B",
	"T3CjuEEN+4lCZnBYFqn9J8UMDR4Ay27YTMOY8czRRFMDF06cCdMYg+YisUR5WhMmQOA1KshlysczYIJI",
	"D1wmPg7gN6L+9ORkqDEpFTczSKRIUAm7GvxWSI12IgafP30gBiwonAamEKRDD6t72rEkRcWvMXXwgbkl",
	"3bJfzBwHw3aeWSYxYxQflQYHX0X3Vi6d9i/bzmOpcmbssyVt/MXtfWtfdtDlgFCKccYT88l/aD9LpDAo",
	"CAJYYXWKkHBYKDnKMP+/v2u75b43Jv3fCsfRcfS/hjXkDt23enjq3nJTz2/a88YuSDwduqFupaItow0z",
	"GLZyADvYx8FkAKQpxDywW3ci1cwrW2Y3zcwr28Eguo2jX6Qa8TRF8ViLnUcZ2rgZS640FKhyrrW1N0ba",
	"v6wYnVrLwiK//catmKW5VcQkQa0h6IFb32/S/CJLkT6yLDGtpZRK1LQRSA6xVf7qoxFm0mKD7EBgyxta",
	"k5/yMZb0SgAq5SEzZ8bSVaCCT7+8hr++/Mv/h33/MrxBw3imCVr/dn5+Cq9OT0jnbsPWpL32c8kzsl0s",
	"yz6Oo+Mvy0mjx09EUZroNv4eFcqqguFu3/K0w3jHEc/ZxD2waLwFm2AK15wRt1NMPafpDUCRFpILC8uY",
	"yRsHXvbh08/nYLVyijCy9AA3GrMxYaBGhNOPZ+fDN28/vD1/C4PBYEgP6eF3nt4OHTFfht/pPyfp7YVH",
	"Ngu6qwTjVm9ftOvyC2VKsVnkQCwg4BfLi4vqEUl4HN1e3MaO4a+Zxl9lKcw5PbDIyLRUkvzCLmcQBVzL",
	"hI3KjKkZrfmaZTwlxjXsP3yNaN2X1WBfI8ikvCoLYKbCOMNzHMBHa2pzZIKLybjM4GaKjr/JVGoUkFta",
	"wa4GdFkUUhlrpmDfcrsSw6W1dpf06CU96mbb09U7NS0wztjkwLG+pTDGM2XblS/Q07/+DpvUkp2XnJN+",
	"S2KkTZf8Tt4y107hYygFt7baWhve0O9BF5NKlbUnewVjhXqazQ5z66GmMeipVOYwI4NfKNR8IjCFsxfw",
	"7u25dRwG8K6iTOCN3VfWNZnBGE0yDRbObTPL8VTSNkxYMkWLnAUqzYnvXFtxlBhbzcBvBVeonYBr+694",
	"J6vnNk7gpFviRa8gCIRagvA6zwzOeR70QQcXF1RkLQCY37y3dn0sbyDfSMoMmbDfXOFsJJnqUIuTN5a3",
	"DN77J+YiphaZVzhLWHF5xV3cuD5YvacX33PzVhg1a6NWHAlpHOdakxaZ5+I85f+c8loxwgL3NKSkXAN6",
	"y7oI9nFtXXa7L63n263H2rDRems5oyftKzecoqTNWHFGb/Xy4ZprPuIZN7NVo/2jfnJReSt596rtgkBa",
	"+uslrdEs1ZmEFWdoVihNV8R8xc0lT+04UngHlhlws4JGs6fBapmD9orYgXvtYLBy+zbodxT0cuID1+a0",
	"G0yDTDcQbpnnrEfB61RIreZfAv1xJMosiy76Ef8sKOg8kfOgsa2psruAZ/xPVHc0WCEe24YU2oqbTVoo",
	"nqxEzV+lwNkSmxqE11Z4kWRl6rIVKCyWWxalFerASDGRDu3KQUtgwR20QUhig+E/2SjzQXJmrdQ1xxsy",
	"r7K0wfVYZpm8OSyLsFBnr7ayKMuc4PYKf+FKG0CLBZS9Iu80Bj6meHyfLdjzhgn//OlDDNqunOngDY/L",
	"LANiaYUMtGWlwLV9e+/dVkug7UGea9OYLbDIiqFz2UEpV7pX/crRgO3WxIndK43xq7RcMBL9IOrGXYag",
	"C8jmB4z9pF249r7BofXiqfDGRiHVuqFGGPwN6UyH2KQxMic3eeUWZgYVZ9lrmUlVOQfzIH134KHBLnM/",
	"x2YItAj3RhZ3W9EN8snUbPja7RIt6PNQezdLWslpHZXxUr2No4zNZGm2E4Ebo5f1MXDC4ipx2ggO3avg",
	"/H+eVmcADd9Q8z+xJ9jrQYiljmkyWpdJp8mI3ihVMl1DKU7DcxZA+J/b2lP+54Y2fCdOqFMwz9llMLUr",
	"DyyMdz9OWFOULUKZ1piPstl2ggqaelkko8sw5B1csEQKgYnh116AO6KoOewdqBpzld8wtaUyh1E2ROcp",
	"T64EahIWfmN5kWF0/MPg/zWyAqksR1nDl3KHecuxtddl/IRpmWAKesoK9MdTmFoXkBzA6pxh0PbzenG5",
	"x6WrYXd9UJMqRWW9fVN2Y1tAnTXyUVV0tpG74V7p9Te63dR1U7WdOdorblZlaF3UeKjR+DStjUGH36+4",
	"OQk5W2c+1vNk62Uu8WYpor1jvu6Km65sXR1GrxEou/l7PbfmAlqw9zDJvzvk++AViXvKtIWHXGpDeQan",
	"JfvcaLhGkUoFCkWKalgomZaJsZSag3716NGGjRKLfdnEhT3R4nV3XE3nXl+jn5nGr1EMX6O33wwKzaVw",
	"f75KEquSX6PusHljf2RhMctsu1tN07jPk/6bNOEyCaawT1chhs42H0DGr1xK38jiMMNrzGx0ys3M4Wd9",
	"JmNlxToSR0whjPEGUMhyMrXAWyiWGJ5g7ThSnErjcR2O0JtQbVUmIHVXSL6xe+JxsuvQpoeDZ7gxrJ6h",
	"2fBkLORz1wVbu7XWORXT2I24796eD08/r0beL2GzbXI4tpzN6wasTT5uEDqF2HFrrythxR0D0bsEMkqO",
	"eYY7IdqP9UTjDSfWHQYcbsB7izjmh99AEXm6mUPYUIE1XL4PJNou0++FHi6c7GlgRaGktfxkpbW1Vu5/",
	"XyMLu6UuWZbNgAkgnoEcQ5ExLsARoGO6DaVljmFUjhr2ndcbw8LJ2QGUGkH6i0dGAjOGJVPrLxzStJBI",
	"oY1iFrqG44xNdIVNuUwxG7oVXGrEdPC7lqIL+MPy5qKJyLkUnfpNC27q1SpsqmaoXr7olUMPSm0+6ZKZ",
	"5vNNHYIvpjPNE5ZBwZQB9+0IUxjNIOAYMJFCYgdoRz1J97i/KEQw+M10wsYu0FZhhtdMGPg/Fd5udzzv",
	"Thm6OKSs8+Fd9PoK454Go1hyxcXEX+tKZnaqOkr98cXg5V/WCFSrG0Ed4Wi4l7NwLactiJS+6MYUoQ0T",
	"CfZ8Sfy9pLvE8xC6kCrJMnmD6WVbPVcnVXvhSyHzV5vWkNDiqK0wuJG+N9w4VKy3+T+cHnEp4K1S3Rs+",
	"nMfVb02NKfTxcJjPrhBHesDFWA7pDpUeXlcjHqIfcaOQgr4NtFbr6drGpw2Hf2GnWV84xAOHGR9jMksy",
	"rHQztsBK2znkhDTt59rz9ge2N3QuP0EDGq0yGBuv2RgrRRsBqhmkdDJvX3aUHnRBbHh6/RMvl9PY8PFa",
	"9nf3fJoj3d+xZRzsy1a0ujG2vYJ0Vh1qrReYuOfv5XDJDf2LVEmHO8cSUzLHpRYeh69gbN+1uDyxyAX7",
	"QuZcsMz5K3RuuQby+jOszvOPn+m7Q1maXczVL4+No5UxS4xUs8usHGHafXNoHBi7WrxOBmSWRWmHLhWq",
	"lVHS6nGD63HX4IaLjv19+vpnf5uw4ALoKHXO6P4l7jAG66ZLHN1zhzgFkbPWe2fF7i4gusPiOyTrdx+R",
	"xcFMNYa+6NXlXYVonqX3Ep8tqGffufZUltoLf2tB3i0loE2XT/hg0xtZPDoT+uXX7xKdcYsFqvKK/GGO",
	"mTIB4S0XPPqLgMAUij3jfKZQHdTl/LTd7s08gT9KRsnQbp/1qfkJZxX4LVxd20myzCuFQ9g7amih8NIo",
	"do0dtJwqPHTfQcpdAGQNeJ6v6RkYaVjWO/q5/RbuPv4Srt9/0ujR7FPXqv8xZ7GqMkq7s65dCLB4f1hS",
	"CZxClvrb7wZzSmHbOObd23NQsuytuavPC8jeNYsAjYQRtoorY1A4YSrNUGuQY6jN4MEAvkZFOcp48jVy",
	"FY10X5DgQ8hm+Y/1V6mCK7PvzNUFzb06mtHFPXfSdsiFr60clcZVIwopZrkstSeZsnKeUXPjUO3jaEaL",
	"8SWi51NUCFxbygpUh1SqRUF9xrUZ6imzMoIckykTXOcwwpkUlsWoLVcoo8NRubxbzQU3pAGdyAJTy8Sq",
	"DrMuS/Q3+VGUubXSjmlRPM8JAlcn9Isu1Ql1jGcWVkOpH5UsvioNRTUjZArVL2Hz/f2f5y318W8ccq1L",
	"TOHv/zyHffu6VPxP5kpTf6ZR4Gt5dPQiMfIKBf0XD2JAQY41xdOvTk/gHTN4w2Z7uiqetAMyPx4qX+KC",
	"OV1RG8xYnu1p+JsxxauCD6FBvn++vndJBZyU2rS7T1P1zDHIAsVJ+trd6AAS6QgTVmoEZMkUUiwyOUMK",
	"0ZMr2L8apaPDFK9jkvnpJ3h94r7SMTAYl9bZh0LJ9IAOXe0OogLhkAIIy/psteVUSpcMtHLFsbT65F9I",
	"uU4kGcpQTWoa+mZdiAxhzL9hOr+Ezyrzpa5TtLb3kAvL5WuupMhRmEM2EVIbnpBWwZhnaL3+LIVEKoWJ",
	"yWaQYpIxhQM4RXXo1u2SVLBvybZUn6QxkMSVpe+AThnnpAIfS1OUxpe42rn86SWlnZkwmnaQ3bxpzsXX",
	"yOm7o0IXUqSUtc7Rwrue8iIkDFsM3NNhEP01gomSZQH7ulRjlnhBU5qR3jqmrzUkGeP5QVzVRtJNAo+6",
	"VGBcl1T6nUauB8WEpMw1FE+NKVxlIBdjGWoPWWKqewGdKa+oXUp4euIuNIQkKKPDfWnDYg8iCcvqu9bN",
	"4u8qFRVXPljcyEhZ3XRa5m5k+6rwROYjLgih8wF8ciBvJSlchWYpUlQwvP5hSJAz/O5qi2+Hg8GAcMmV",
	"kcFIUqH1XEV8TR1N7WrRG/gFU3aNS8rR8+o0wlLtJoaCmSlUTRpcjUvgYHXNEb+xxIAqs1DulPEEfVmo",
	"r5H+9eTclzPVwplwMy1Hg0TmQyUnJWpUKLiZDe2OH44yORrmjIvhh5PXb387e9vIiUb2CYteNqZDpZ04",
	"fxgcDY4ov1agYAWPjqMXgx8GRxaUmZkS2lrWOq2jPyddRSaf6Bxe16XLrl+ANUhub7neAn6DHvqrItZq",
	"h6GH38O7t4uF/UuOp9z1nrALTtLoOLKx6AdP7kKJ+I9HR0vKbtvltlV+4Ut9WrQQ1UT1DfdLuoXV+Ntf",
	"9bqI186Zd5TuZtniKZ3jLdUUv3QL6opCqoUPFwuPaQ7vb238bsMgR8dfLuJIB8eVGG9di256LRaxiba8",
	"DMpEcXpDuxoq4HPK2FVKdpJiXkgrQTj0F0A0/Hj0Em6mSFtXqqByNQ1UtY1pl8K8oXn8IWlLY162CXAv",
	"pLBv1dRX57ORRmEOvFRerOZsu4R/h3JZcJG+XNzOSeqN94lbktp3Nfl22x50CiwO23+ehe/Q9PFvsx23",
	"LJ72M6ws2V9YlBfJy9VMbXUduK+d8g7dBbeVx+89Mmh2APrSeabd0XKjcUa9fg+dizgqpO6Q+GsKshpC",
	"J+7/LNPZjuXtjyHmk5WW7NuWqv3wQKrmAsw+Rbvr3n959NfVb7aanDwcaDiJA6M7n3cADn/aMa9Gn7DI",
	"WPLE9OihIMtlKHavR48MdSv0yIu8bX3a8LdarbwDseD5u/Ch11k9GQdXnetGJmixS1ZGzZ2sQ+PL1qvH",
	"3PgD+Bh6R4WHKQHT7H3lA5k1GloVUms+ymaAeWFmB32e7c9uaS0b0CWx+pGh64R2G6980LeTsyK7t10x",
	"X8jd5fRCwSZUZ+45/RR83e+We0s1mxzgURBQUFb/QYfdXiEK3yGuaYPn2eSVOC/ttNiryT/VvaW4WGwb",
	"1oyAm1eqNbw8etmlhM4MuAZA94PXzW5BD2v23apWWH3fXOXRNLJtkEdeGC2NW4aOdG97WZi1tnbRAJQK",
	"mlctV1a/nla5iKTWqjVDsMf07dvRVK8c4uVJk0ZLKuq16NqJ6dBPzHGdOo7R9/6EgjK33ppws2hQBvCp",
	"5jjs23j45dGLA9cZMUy32NPM5/Tt8Gk4RwizU37M5/z7uylSUpd6JuqOpomlqOituid2acM7ND2qcPQw",
	"e70OJpu7/bH9qpUGyMaVS9XwbgZotdcQzFS5jZUid3hLHPlMLvVTsk4PpLEhlnh0fa2U0YliK/M0rJsA",
	"3rfmbudgsTR1iutrFo1cW4mBijX9iYYFVzSGDnOpOuvjGdVedTYupEPGWh0PagD2YQ1FIzds1iiskAIH",
	"8CbAfllkkrkTF0e3G/k49CclsVK13XwhqKXo86cPjiEZp27ANJRvQZyYkmV+yNHMIJmylLuDO3eiNteS",
	"Jpxw6cbRiN8yrifghF+jcOeenhOe9GrJGRr39qvTE1BIrZOdxXHHP5jOj1gWMFZSmBhG7kiTWutyrUt/",
	"qDXfMsdaP5ri7EVz9MA/ZsiWij3jejHDjf3ohunakqzwpV3J7t0ha7E+o14qHWT4E3gSyfD3AieRby40",
	"LET9/xscFd2H8HPFLs3B23cCd++y9zdNbPc3JIlcdlY6n3ao8ADOGtXOVpu8TAsl88Jq6zadCGtiutnU",
	"6tLqtozOpCuGHiEKuqxBFyV+au/XanPVU8E+9W09/Xweh97Srx2jD8+t4k+RpaicmjrfDLv2mj/H9up4",
	"YOewAEqeLqeOV1sEQI9tml6l6TxWb2+j6tawO4mpFObyes6kuLb9O4mwaqx5TmHWJ8sSXGTIY3m78fcO",
	"Jyzs/bosvWqJ62i2FoGlqWtq2fULB06HNjui6VbR6rLF/aVBqynWyYTWdUi7S4a+r9b4rPOhrc5KS1Oi",
	"NdefUVb0qiGpsFPrz/61cqNVP7/7CUAXmv89bIa0WtuKJGmQ7ZPKk17VgunSwRU4ev8J0+rS3CYWfU7b",
	"nmXadIVY1kieVox7sPxpNeMTTqH2a8bRg+FBnUhdQIRnkktdqZvPMqO6IdC4TN7TM2sPp8Yhu/oUlLid",
	"YL2rXQstnO41QgiXu9eMEcLju40SXGOe5x8mLDREWhUnVLx/XpFCIHtenytt/ZeLFnzjuHvD1bkucw8e",
	"L/jVrQ4YqiaYTytk8GT1KuNKeH2QwCF0ddkwdGio3nONHVbJZ734IfDvISOIMOfTjiH6VOTo4UBiLoqY",
	"h4nnE0es1tPnGktshj1VNPHkzN4DanQjoHgC+twZUuzG7g1Dt9qVINzoBuxKOulD+qka/xOhZYYamIZJ",
	"A5dgX94IQuYlcGgBuPqdX19jXfUy/gnmfrQqONfLo4n33Oj7h8RmQ+YeRaq59lwA0ZUJtntAPyIw7uby",
	"DzVabt/82Rggm3HBe36/AFk39X+MuIDaPq+IC/h2AcGTuGpQacaOcTU03N5xcEHkdt032CrOCKr8POMM",
	"vl2Awc19G7Vl/nsn648ebjM3/Hf+3Bx3/lgee+cNE/9DnO37JVbDbpgOuNlzv4TgYuMC4B3FDUSjFDsN",
	"IJ6WfXzALVUFEPypRQ58p6Zt2PhtoZ3dqbNE7vnfz96FRi6Yued9v67JnP/x0LddZKDRmO0VbumvI1lP",
	"wE7u8ntcu459oFyRtQZOv64FAl2TNt8Nb8yVNv8uBHgyhQBnDU/t35UA667t8S/7//uG/xMNu10QpQIO",
	"Hqxp1rodlNCs7v7uSYQZ1rkkUbUv3t0NibOwwGd9P2KhFfnSyxEVw5/RzQhdSylob/XRv9adiLPwo+n3",
	"EdjN/brFw2Y9/bpWpDydUJ/UNYjqV+w7FG85Zt7/5Qc300aRWkO/nmU2cpk41shGeo492FUHP98TvubQ",
	"pxBHD7T16wTp3OZ/JjnS5er4LG81bAQqLvf1tIzWQ2luyEM+vt62U5FLrdY6PevoR72d2s63YWYFH8z3",
	"yb6oZlnUxapIkfyjtme05Jxn0EhfVRe629mx4L5vNUHFm/b47xvXsvd9i26ugIuUX/O0ZBmd3x9su74q",
	"DmtT4Lre+VbgPqPmGdLsJd74hTtLUdxD0VoE+TriNi2v5noU+ihtLBWgKPND+iXsMUdL7r5rx6rj6jc1",
	"dQz+p1t1DGiSgWvaIaQ41Cg0N/waYZLJEctA4RgVigQhZYbF87aSiRmty1pelta/a9H3+xM/uYbx9YOu",
	"saI7hGysOnRWvL24/e8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
