// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Visibility.
const (
	Authenticated Visibility = "authenticated"
	Private       Visibility = "private"
	Public        Visibility = "public"
)

// Valid indicates whether the value is a known member of the Visibility enum.
func (e Visibility) Valid() bool {
	switch e {
	case Authenticated:
		return true
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// Defines values for DeleteKeyboardParamsOnDelete.
const (
	DeleteKeyboardParamsOnDeleteBlock   DeleteKeyboardParamsOnDelete = "block"
	DeleteKeyboardParamsOnDeleteCascade DeleteKeyboardParamsOnDelete = "cascade"
	DeleteKeyboardParamsOnDeleteDetach  DeleteKeyboardParamsOnDelete = "detach"
)

// Valid indicates whether the value is a known member of the DeleteKeyboardParamsOnDelete enum.
func (e DeleteKeyboardParamsOnDelete) Valid() bool {
	switch e {
	case DeleteKeyboardParamsOnDeleteBlock:
		return true
	case DeleteKeyboardParamsOnDeleteCascade:
		return true
	case DeleteKeyboardParamsOnDeleteDetach:
		return true
	default:
		return false
	}
}

// Defines values for DeleteKeycapSetParamsOnDelete.
const (
	DeleteKeycapSetParamsOnDeleteBlock   DeleteKeycapSetParamsOnDelete = "block"
	DeleteKeycapSetParamsOnDeleteCascade DeleteKeycapSetParamsOnDelete = "cascade"
	DeleteKeycapSetParamsOnDeleteDetach  DeleteKeycapSetParamsOnDelete = "detach"
)

// Valid indicates whether the value is a known member of the DeleteKeycapSetParamsOnDelete enum.
func (e DeleteKeycapSetParamsOnDelete) Valid() bool {
	switch e {
	case DeleteKeycapSetParamsOnDeleteBlock:
		return true
	case DeleteKeycapSetParamsOnDeleteCascade:
		return true
	case DeleteKeycapSetParamsOnDeleteDetach:
		return true
	default:
		return false
	}
}

// Defines values for DeleteKeycapKitParamsOnDelete.
const (
	DeleteKeycapKitParamsOnDeleteBlock   DeleteKeycapKitParamsOnDelete = "block"
	DeleteKeycapKitParamsOnDeleteCascade DeleteKeycapKitParamsOnDelete = "cascade"
	DeleteKeycapKitParamsOnDeleteDetach  DeleteKeycapKitParamsOnDelete = "detach"
)

// Valid indicates whether the value is a known member of the DeleteKeycapKitParamsOnDelete enum.
func (e DeleteKeycapKitParamsOnDelete) Valid() bool {
	switch e {
	case DeleteKeycapKitParamsOnDeleteBlock:
		return true
	case DeleteKeycapKitParamsOnDeleteCascade:
		return true
	case DeleteKeycapKitParamsOnDeleteDetach:
		return true
	default:
		return false
	}
}

// Defines values for DeleteSwitchParamsOnDelete.
const (
	DeleteSwitchParamsOnDeleteBlock   DeleteSwitchParamsOnDelete = "block"
	DeleteSwitchParamsOnDeleteCascade DeleteSwitchParamsOnDelete = "cascade"
	DeleteSwitchParamsOnDeleteDetach  DeleteSwitchParamsOnDelete = "detach"
)

// Valid indicates whether the value is a known member of the DeleteSwitchParamsOnDelete enum.
func (e DeleteSwitchParamsOnDelete) Valid() bool {
	switch e {
	case DeleteSwitchParamsOnDeleteBlock:
		return true
	case DeleteSwitchParamsOnDeleteCascade:
		return true
	case DeleteSwitchParamsOnDeleteDetach:
		return true
	default:
		return false
	}
}

// Build The read representation of a build. Unlike BuildInput, keyboard, switches[].switch, and keycap_kits[].keycap_set are denormalized into resolved reference objects rather than bare ids, so a client can render a build without follow-up requests.
type Build struct {
	BuildDate     *openapi_types.Date `json:"build_date,omitempty"`
	CaseMountType *BuildCaseMountType `json:"case_mount_type,omitempty"`
	Foam          *bool               `json:"foam,omitempty"`
	Id            string              `json:"id"`

	// Images Managed via the dedicated image endpoints below, not via PUT on the build itself — see POST/DELETE .../builds/{buildId}/images[/{imageId}].
	Images *[]BuildImage `json:"images,omitempty"`

	// Keyboard Omitted if the referenced Keyboard no longer exists (e.g. deleted after the build referenced it).
	Keyboard   *BuildKeyboardRef              `json:"keyboard,omitempty"`
	KeycapKits *[]BuildKeycapKitEntryResolved `json:"keycap_kits,omitempty"`
	Notes      *string                        `json:"notes,omitempty"`

	// Plate Which of the keyboard's design.plates options is installed.
	Plate    *string                     `json:"plate,omitempty"`
	Stabs    *BuildStabs                 `json:"stabs,omitempty"`
	Switches *[]BuildSwitchEntryResolved `json:"switches,omitempty"`

	// TotalCost Total cost of the build's priced components (keyboard, switches, keycap kits, stabs). Components with no known price are excluded rather than treated as zero, so this may undercount.
	TotalCost *Money `json:"total_cost,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// BuildCaseMountType defines model for BuildCaseMountType.
type BuildCaseMountType struct {
	// Durometer Open vocabulary — validated against the "build_durometer" lookup at request time. Only meaningful when the chosen mount type supports it (see the build_case_mount_type lookup's supports_durometer flag).
	Durometer *string `json:"durometer,omitempty"`

	// Type Open vocabulary — validated against the "build_case_mount_type" lookup at request time.
	Type *string `json:"type,omitempty"`
}

// BuildImage defines model for BuildImage.
type BuildImage struct {
	// ImageId Server-generated identifier for this image, unique within the build.
	ImageId string `json:"image_id"`

	// Url A freshly-minted, short-lived presigned S3 GET URL. Generated new on every fetch of the build — do not cache or persist this value, it expires.
	Url string `json:"url"`
}

// BuildImageUpload defines model for BuildImageUpload.
type BuildImageUpload struct {
	// ImageId Server-generated identifier for the newly-created image.
	ImageId string `json:"image_id"`

	// UploadUrl Presigned S3 PUT URL. Short-lived — upload promptly.
	UploadUrl string `json:"upload_url"`
}

// BuildInput defines model for BuildInput.
type BuildInput struct {
	BuildDate     *openapi_types.Date `json:"build_date,omitempty"`
	CaseMountType *BuildCaseMountType `json:"case_mount_type,omitempty"`
	Foam          *bool               `json:"foam,omitempty"`

	// Keyboard ID of a Keyboard resource.
	Keyboard   string                 `json:"keyboard"`
	KeycapKits *[]BuildKeycapKitEntry `json:"keycap_kits,omitempty"`
	Notes      *string                `json:"notes,omitempty"`

	// Plate Which of the keyboard's design.plates options is installed.
	Plate    *string             `json:"plate,omitempty"`
	Stabs    *BuildStabs         `json:"stabs,omitempty"`
	Switches *[]BuildSwitchEntry `json:"switches,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// BuildKeyboardRef A build's denormalized Keyboard reference.
type BuildKeyboardRef struct {
	Brand string `json:"brand"`
	Id    string `json:"id"`

	// ImageUrl A freshly-minted, short-lived presigned S3 GET URL for the referenced keyboard's first image, if it has one. Generated new on every fetch of the build — do not cache or persist this value, it expires.
	ImageUrl *string `json:"image_url,omitempty"`
	Layout   *string `json:"layout,omitempty"`
	Name     string  `json:"name"`
	Size     *string `json:"size,omitempty"`
}

// BuildKeycapKitEntry defines model for BuildKeycapKitEntry.
type BuildKeycapKitEntry struct {
	// KeycapSet ID of a KeycapSet resource.
	KeycapSet string `json:"keycap_set"`

	// Kit kit_id of one of that keycap set's kits (see KeycapKit.kit_id).
	Kit string `json:"kit"`
}

// BuildKeycapKitEntryResolved defines model for BuildKeycapKitEntryResolved.
type BuildKeycapKitEntryResolved struct {
	// KeycapSet Omitted if the referenced KeycapSet (or the kit within it) no longer exists (e.g. deleted after the build referenced it) - in that case kit_name and kit_image_url are omitted too.
	KeycapSet *BuildKeycapSetRef `json:"keycap_set,omitempty"`

	// KitId kit_id of the referenced keycap set's kit (see KeycapKit.kit_id).
	KitId string `json:"kit_id"`

	// KitImageUrl A freshly-minted, short-lived presigned S3 GET URL for the referenced kit's image, if it has one. Generated new on every fetch of the build — do not cache or persist this value, it expires.
	KitImageUrl *string `json:"kit_image_url,omitempty"`

	// KitName Denormalized name of the referenced kit.
	KitName *string `json:"kit_name,omitempty"`
}

// BuildKeycapSetRef A build's denormalized KeycapSet reference.
type BuildKeycapSetRef struct {
	Brand   string  `json:"brand"`
	Id      string  `json:"id"`
	Name    string  `json:"name"`
	Profile *string `json:"profile,omitempty"`
}

// BuildListPage defines model for BuildListPage.
type BuildListPage struct {
	Items      *[]BuildSummary `json:"items,omitempty"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// BuildStabs defines model for BuildStabs.
type BuildStabs struct {
	// MountType Open vocabulary — validated against the "build_stabilizer_mount_type" lookup at request time.
	MountType *string `json:"mount_type,omitempty"`

	// Name Open vocabulary — validated against the "build_stabilizer" lookup at request time.
	Name *string `json:"name,omitempty"`

	// Price A price in the collection's tracking currency.
	Price *Money `json:"price,omitempty"`
}

// BuildSummary Includes a denormalized keyboard brand/name so a build is recognizable in a list view without a follow-up request.
type BuildSummary struct {
	BuildDate *openapi_types.Date `json:"build_date,omitempty"`
	Id        *string             `json:"id,omitempty"`

	// Image First entry of images, if any (a freshly-minted presigned URL, same as on the full Build resource).
	Image *BuildImage `json:"image,omitempty"`

	// Keyboard A build's denormalized keyboard brand/name, for display in a list view.
	Keyboard *BuildSummaryKeyboard `json:"keyboard,omitempty"`

	// TotalCost Total cost of the build's priced components (keyboard, switches, keycap kits, stabs). Components with no known price are excluded rather than treated as zero, so this may undercount. Omitted for a build the caller doesn't own, same as Build.total_cost.
	TotalCost *Money `json:"total_cost,omitempty"`
}

// BuildSummaryKeyboard A build's denormalized keyboard brand/name, for display in a list view.
type BuildSummaryKeyboard struct {
	Brand *string `json:"brand,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// BuildSwitchEntry defines model for BuildSwitchEntry.
type BuildSwitchEntry struct {
	Count int `json:"count"`

	// Switch ID of a Switch resource.
	Switch string `json:"switch"`
}

// BuildSwitchEntryResolved defines model for BuildSwitchEntryResolved.
type BuildSwitchEntryResolved struct {
	Count int `json:"count"`

	// Switch Omitted if the referenced Switch no longer exists (e.g. deleted after the build referenced it).
	Switch *BuildSwitchRef `json:"switch,omitempty"`
}

// BuildSwitchRef A build's denormalized Switch reference.
type BuildSwitchRef struct {
	Brand string `json:"brand"`
	Id    string `json:"id"`

	// ImageUrl A freshly-minted, short-lived presigned S3 GET URL for the referenced switch's image, if it has one. Generated new on every fetch of the build — do not cache or persist this value, it expires.
	ImageUrl     *string `json:"image_url,omitempty"`
	Manufacturer *string `json:"manufacturer,omitempty"`
	Name         string  `json:"name"`
	Type         string  `json:"type"`
}

// CascadeDeleteResult Returned by a delete call made with on_delete=cascade, listing the ids of every build that was deleted alongside the requested item.
type CascadeDeleteResult struct {
	DeletedBuildIds []string `json:"deleted_build_ids"`
}

// ImageUploadRequest Request body for every image-upload endpoint (keyboard, switch, profile avatar, keycap kit, build). The upload is two-step: this call allocates a slot and returns a presigned S3 PUT URL, then the client PUTs the bytes to that URL with a matching Content-Type.
type ImageUploadRequest struct {
	// ContentType Open vocabulary — validated against the "image_content_type" lookup at request time.
	ContentType string `json:"content_type"`
}

// Keyboard defines model for Keyboard.
type Keyboard struct {
	Brand  string          `json:"brand"`
	Design *KeyboardDesign `json:"design,omitempty"`
	Id     string          `json:"id"`

	// Images Managed via the dedicated image endpoints below, not via PUT on the keyboard itself — see POST/DELETE .../keyboards/{keyboardId}/images[/{imageId}].
	Images *[]KeyboardImage `json:"images,omitempty"`

	// Layout Open vocabulary — validated against the "keyboard_layout" lookup at request time, including that the chosen layout is valid for the keyboard's size.
	Layout *string      `json:"layout,omitempty"`
	Name   string       `json:"name"`
	Notes  *string      `json:"notes,omitempty"`
	Pcb    *KeyboardPCB `json:"pcb,omitempty"`

	// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
	Purchase *Purchase `json:"purchase,omitempty"`

	// Size Open vocabulary — validated against the "keyboard_size" lookup at request time.
	Size *string `json:"size,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// KeyboardDesign defines model for KeyboardDesign.
type KeyboardDesign struct {
	// BottomCase A physical part described by material and color.
	BottomCase *MaterialColor `json:"bottom_case,omitempty"`
	Plates     *[]string      `json:"plates,omitempty"`

	// TopCase A physical part described by material and color.
	TopCase *MaterialColor `json:"top_case,omitempty"`

	// Weight A physical part described by material and color.
	Weight *MaterialColor `json:"weight,omitempty"`
}

// KeyboardImage defines model for KeyboardImage.
type KeyboardImage struct {
	// ImageId Server-generated identifier for this image, unique within the keyboard.
	ImageId string `json:"image_id"`

	// Url A freshly-minted, short-lived presigned S3 GET URL. Generated new on every fetch of the keyboard — do not cache or persist this value, it expires.
	Url string `json:"url"`
}

// KeyboardImageUpload defines model for KeyboardImageUpload.
type KeyboardImageUpload struct {
	// ImageId Server-generated identifier for the newly-created image.
	ImageId string `json:"image_id"`

	// UploadUrl Presigned S3 PUT URL. Short-lived — upload promptly.
	UploadUrl string `json:"upload_url"`
}

// KeyboardInput defines model for KeyboardInput.
type KeyboardInput struct {
	Brand  string          `json:"brand"`
	Design *KeyboardDesign `json:"design,omitempty"`

	// Layout Open vocabulary — validated against the "keyboard_layout" lookup at request time, including that the chosen layout is valid for the keyboard's size.
	Layout *string      `json:"layout,omitempty"`
	Name   string       `json:"name"`
	Notes  *string      `json:"notes,omitempty"`
	Pcb    *KeyboardPCB `json:"pcb,omitempty"`

	// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
	Purchase *Purchase `json:"purchase,omitempty"`

	// Size Open vocabulary — validated against the "keyboard_size" lookup at request time.
	Size *string `json:"size,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// KeyboardListPage defines model for KeyboardListPage.
type KeyboardListPage struct {
	Items      *[]KeyboardSummary `json:"items,omitempty"`
	NextCursor *string            `json:"next_cursor,omitempty"`
}

// KeyboardPCB defines model for KeyboardPCB.
type KeyboardPCB struct {
	// Assembly Open vocabulary — validated against the "keyboard_pcb_assembly_type" lookup at request time.
	Assembly *string `json:"assembly,omitempty"`

	// Connectivity Open vocabulary — validated against the "keyboard_pcb_connectivity_type" lookup at request time.
	Connectivity *string `json:"connectivity,omitempty"`

	// Firmware Open vocabulary — validated against the "keyboard_pcb_firmware" lookup at request time.
	Firmware  *string  `json:"firmware,omitempty"`
	Thickness *float64 `json:"thickness,omitempty"`
}

// KeyboardSummary Reduced shape returned in list responses.
type KeyboardSummary struct {
	Brand *string `json:"brand,omitempty"`
	Id    *string `json:"id,omitempty"`

	// Image First entry of images, if any (a freshly-minted presigned URL, same as on the full Keyboard resource).
	Image       *KeyboardImage `json:"image,omitempty"`
	Layout      *string        `json:"layout,omitempty"`
	Name        *string        `json:"name,omitempty"`
	OrderStatus *string        `json:"order_status,omitempty"`

	// Price Same as Keyboard.purchase.price - omitted for a keyboard the caller doesn't own.
	Price *Money  `json:"price,omitempty"`
	Size  *string `json:"size,omitempty"`
}

// KeycapKit defines model for KeycapKit.
type KeycapKit struct {
	// Image Managed via the dedicated image endpoint, not via PUT on the kit itself — see POST/DELETE .../keycap-sets/{keycapSetId}/kits/{kitId}/image.
	Image *KeycapKitImage `json:"image,omitempty"`

	// KitId Server-generated identifier for this kit, unique within the keycap set.
	KitId string `json:"kit_id"`

	// Name e.g. "Base", "Extension", "Accents".
	Name string `json:"name"`

	// Primary Omit to leave the set's primary kit designation untouched. true makes this kit the set's primary kit, replacing whichever kit held that designation before. false clears the designation, but only if this kit is the current primary - otherwise it's a no-op. Deliberately has no default: a missing field must stay distinguishable from an explicit false.
	Primary *bool `json:"primary,omitempty"`

	// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
	Purchase *Purchase `json:"purchase,omitempty"`
}

// KeycapKitImage defines model for KeycapKitImage.
type KeycapKitImage struct {
	// Url A freshly-minted, short-lived presigned S3 GET URL. Generated new on every fetch — do not cache or persist this value, it expires. A kit has at most one image (its vendor render/product shot) — see POST/DELETE .../kits/{kitId}/image.
	Url string `json:"url"`
}

// KeycapKitImageUpload defines model for KeycapKitImageUpload.
type KeycapKitImageUpload struct {
	// UploadUrl Presigned S3 PUT URL. Short-lived — upload promptly.
	UploadUrl string `json:"upload_url"`
}

// KeycapKitInput defines model for KeycapKitInput.
type KeycapKitInput struct {
	// Name e.g. "Base", "Extension", "Accents".
	Name string `json:"name"`

	// Primary Omit to leave the set's primary kit designation untouched. true makes this kit the set's primary kit, replacing whichever kit held that designation before. false clears the designation, but only if this kit is the current primary - otherwise it's a no-op. Deliberately has no default: a missing field must stay distinguishable from an explicit false.
	Primary *bool `json:"primary,omitempty"`

	// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
	Purchase *Purchase `json:"purchase,omitempty"`
}

// KeycapSet defines model for KeycapSet.
type KeycapSet struct {
	Brand string `json:"brand"`
	Id    string `json:"id"`

	// Kits Managed via the dedicated kit endpoints below, not via PUT on the set itself — see POST/PUT/DELETE .../keycap-sets/{keycapSetId}/kits[/{kitId}].
	Kits *[]KeycapKit `json:"kits,omitempty"`

	// Material Open vocabulary — validated against the "keycap_material" lookup at request time.
	Material *string `json:"material,omitempty"`
	Name     string  `json:"name"`
	Notes    *string `json:"notes,omitempty"`

	// OrderStatus Derived, read-only summary of every kit's purchase.order_status: the least-progressed status among them wins (Planned < Ordered < Shipped < Delivered), so the set isn't shown as Delivered while a kit is still en route. A kit with status Cancelled is excluded from that comparison unless every kit is Cancelled, in which case this is Cancelled too. Null if no kit has an order_status set, or the set has no kits.
	OrderStatus *string `json:"order_status,omitempty"`

	// PrimaryKitId The kit_id, among this set's kits, whose image represents the set in a list view. Null if never set, or if the kit it named no longer exists — match against kits[].kit_id to find that kit's image.
	PrimaryKitId *string `json:"primary_kit_id,omitempty"`

	// Profile Open vocabulary — validated against the "keycap_profile" lookup at request time.
	Profile *string `json:"profile,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// KeycapSetInput defines model for KeycapSetInput.
type KeycapSetInput struct {
	Brand string `json:"brand"`

	// Material Open vocabulary — validated against the "keycap_material" lookup at request time.
	Material *string `json:"material,omitempty"`
	Name     string  `json:"name"`
	Notes    *string `json:"notes,omitempty"`

	// Profile Open vocabulary — validated against the "keycap_profile" lookup at request time.
	Profile *string `json:"profile,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// KeycapSetListPage defines model for KeycapSetListPage.
type KeycapSetListPage struct {
	Items      *[]KeycapSetSummary `json:"items,omitempty"`
	NextCursor *string             `json:"next_cursor,omitempty"`
}

// KeycapSetSummary defines model for KeycapSetSummary.
type KeycapSetSummary struct {
	Brand *string `json:"brand,omitempty"`
	Id    *string `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`

	// OrderStatus Same derived aggregate as KeycapSet.order_status - see there for the bubble-up rule.
	OrderStatus *string `json:"order_status,omitempty"`

	// PrimaryKitImage The primary kit's image, if the set has one designated and it has an image set. Omitted otherwise — including when the designated primary kit no longer exists.
	PrimaryKitImage *KeycapKitImage `json:"primary_kit_image,omitempty"`
	Profile         *string         `json:"profile,omitempty"`

	// TotalCost Total cost of the set's kits with a known purchase price. Kits with no known price are excluded rather than treated as zero, so this may undercount. Omitted for a keycap set the caller doesn't own, same as each kit's purchase.price.
	TotalCost *Money `json:"total_cost,omitempty"`
}

// Lookup A lookup category's approved values. "values" is plain strings except for "keyboard_layout" and "build_case_mount_type", whose entries are objects - see the examples below.
type Lookup struct {
	Category string `json:"category"`

	// Values Examples: ["Amazon","CannonKeys"], [{"name":"WK","sizes":["60%","65%"]}], [{"name":"Gasket Mount","supports_durometer":true}]
	Values []interface{} `json:"values"`
}

// MaterialColor A physical part described by material and color.
type MaterialColor struct {
	// Color Free text.
	Color *string `json:"color,omitempty"`

	// Material Open vocabulary — validated against the relevant *_material lookup at request time.
	Material *string `json:"material,omitempty"`
}

// Money A price in the collection's tracking currency.
type Money = float64

// Problem RFC 9457 Problem Details.
type Problem struct {
	// BlockingBuildIds Present on a 409 response caused by the item still being referenced by one or more builds. Lists the ids of the blocking builds.
	BlockingBuildIds *[]string `json:"blocking_build_ids,omitempty"`
	Detail           *string   `json:"detail,omitempty"`
	Instance         *string   `json:"instance,omitempty"`
	InvalidParams    *[]struct {
		AllowedValues *[]string `json:"allowed_values,omitempty"`
		Name          *string   `json:"name,omitempty"`
		Reason        *string   `json:"reason,omitempty"`
	} `json:"invalid_params,omitempty"`
	Status int    `json:"status"`
	Title  string `json:"title"`
	Type   string `json:"type"`
}

// Profile defines model for Profile.
type Profile struct {
	// Avatar Managed via the dedicated image endpoints, not via a body PUT — see POST/DELETE .../profile/{userId}/image.
	Avatar *ProfileImage `json:"avatar,omitempty"`
	Bio    *string       `json:"bio,omitempty"`

	// DiscordUsername Not verified against Discord's directory, but must match the shape of a Discord @handle: 2-32 chars, lowercase letters, digits, period, or underscore, no leading/trailing period or underscore, no consecutive periods.
	DiscordUsername *string `json:"discord_username,omitempty"`

	// Discoverable Whether this profile appears in GET /v1/profiles and is resolvable by anyone at GET /v1/profile/{identifier}. When false, only the owner can read it. Omitted on a PUT means false (full-replace semantics).
	Discoverable *bool          `json:"discoverable,omitempty"`
	Links        *[]ProfileLink `json:"links,omitempty"`

	// UserId The profile owner's IdP subject. Use it as the {userId} path segment on the collection routes (GET /v1/keyboards/{userId}, /v1/builds/{userId}, etc.). Resolve a profile by username here first, then read that user's collections by this id.
	UserId *string `json:"user_id,omitempty"`

	// Username Lowercase letters, digits, hyphen, period, underscore; 3–32 characters; no leading/trailing period, hyphen, or underscore; no consecutive periods. A Discord-compatible superset, so any Discord @handle (3+ chars) is a valid username. Unique across all profiles, case-sensitively (the charset has no uppercase). Used as /u/{username} in the frontend and as an identifier on GET /v1/profile/{identifier}.
	Username string `json:"username"`
}

// ProfileImage defines model for ProfileImage.
type ProfileImage struct {
	// Url A freshly-minted, short-lived presigned S3 GET URL for the profile's avatar. Generated new on every fetch — do not cache or persist it. Managed via POST/DELETE .../profile/{userId}/image, not via a body PUT.
	Url string `json:"url"`
}

// ProfileImageUpload defines model for ProfileImageUpload.
type ProfileImageUpload struct {
	// UploadUrl Presigned S3 PUT URL for the avatar. Short-lived — upload promptly.
	UploadUrl string `json:"upload_url"`
}

// ProfileInput defines model for ProfileInput.
type ProfileInput struct {
	Bio *string `json:"bio,omitempty"`

	// DiscordUsername Not verified against Discord's directory, but must match the shape of a Discord @handle: 2-32 chars, lowercase letters, digits, period, or underscore, no leading/trailing period or underscore, no consecutive periods.
	DiscordUsername *string `json:"discord_username,omitempty"`

	// Discoverable Whether this profile appears in GET /v1/profiles and is resolvable by anyone at GET /v1/profile/{identifier}. When false, only the owner can read it. Omitted on a PUT means false (full-replace semantics).
	Discoverable *bool          `json:"discoverable,omitempty"`
	Links        *[]ProfileLink `json:"links,omitempty"`

	// Username Lowercase letters, digits, hyphen, period, underscore; 3–32 characters; no leading/trailing period, hyphen, or underscore; no consecutive periods. A Discord-compatible superset, so any Discord @handle (3+ chars) is a valid username. Unique across all profiles, case-sensitively (the charset has no uppercase). Used as /u/{username} in the frontend and as an identifier on GET /v1/profile/{identifier}.
	Username string `json:"username"`
}

// ProfileLink defines model for ProfileLink.
type ProfileLink struct {
	// Name Display label for the link, e.g. "Twitch" or "My Discord".
	Name string `json:"name"`

	// Url An https URL. http, scheme-relative, and non-http(s) schemes are rejected. Enforced by the handler (not a schema pattern) so the rejection names the exact links[i].url that failed.
	Url string `json:"url"`
}

// ProfileListPage defines model for ProfileListPage.
type ProfileListPage struct {
	Items      *[]ProfileSummary `json:"items,omitempty"`
	NextCursor *string           `json:"next_cursor,omitempty"`
}

// ProfileSummary A directory-listing row. Deliberately omits bio and links — those are only on the full GET /v1/profile/{identifier} response.
type ProfileSummary struct {
	Avatar          *ProfileImage `json:"avatar,omitempty"`
	DiscordUsername *string       `json:"discord_username,omitempty"`

	// UserId The profile owner's IdP subject, same value as Profile.user_id on the single-profile response. Present so a client can chain to GET /v1/profile/{user_id} or read the user's collections.
	UserId   *string `json:"user_id,omitempty"`
	Username *string `json:"username,omitempty"`
}

// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
type Purchase struct {
	DeliveryDate *openapi_types.Date `json:"delivery_date,omitempty"`
	OrderDate    *openapi_types.Date `json:"order_date,omitempty"`

	// OrderStatus Open vocabulary — validated against the "order_status" lookup at request time.
	OrderStatus *string `json:"order_status,omitempty"`

	// Price A price in the collection's tracking currency.
	Price *Money `json:"price,omitempty"`

	// Vendor Open vocabulary — validated against the "vendor" lookup at request time.
	Vendor *string `json:"vendor,omitempty"`
}

// Switch defines model for Switch.
type Switch struct {
	Brand        string       `json:"brand"`
	FactoryLubed *bool        `json:"factory_lubed,omitempty"`
	Force        *SwitchForce `json:"force,omitempty"`
	Id           string       `json:"id"`

	// Image Managed via the dedicated image endpoint, not via PUT on the switch itself — see POST/DELETE .../switches/{switchId}/image.
	Image        *SwitchImage    `json:"image,omitempty"`
	Manufacturer *string         `json:"manufacturer,omitempty"`
	Material     *SwitchMaterial `json:"material,omitempty"`
	Name         string          `json:"name"`
	Notes        *string         `json:"notes,omitempty"`

	// Pins PCB mount pin count.
	Pins *int `json:"pins,omitempty"`

	// Purchase Same purchase-lifecycle tracking as Purchase, plus a quantity field since switches are bought in bulk.
	Purchase *SwitchPurchase `json:"purchase,omitempty"`
	Spring   *SwitchSpring   `json:"spring,omitempty"`

	// Type Open vocabulary — validated against the "switch_type" lookup at request time.
	Type string `json:"type"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// SwitchForce defines model for SwitchForce.
type SwitchForce struct {
	// Actuation Actuation force in grams (nominal value).
	Actuation *float64 `json:"actuation,omitempty"`

	// BottomOut Bottom-out force in grams (nominal value).
	BottomOut *float64 `json:"bottom_out,omitempty"`
}

// SwitchImage defines model for SwitchImage.
type SwitchImage struct {
	// Url A freshly-minted, short-lived presigned S3 GET URL. Generated new on every fetch — do not cache or persist this value, it expires. A switch has at most one image (its vendor render/ product shot) — see POST/DELETE .../switches/{switchId}/image.
	Url string `json:"url"`
}

// SwitchImageUpload defines model for SwitchImageUpload.
type SwitchImageUpload struct {
	// UploadUrl Presigned S3 PUT URL. Short-lived — upload promptly.
	UploadUrl string `json:"upload_url"`
}

// SwitchInput defines model for SwitchInput.
type SwitchInput struct {
	Brand        string          `json:"brand"`
	FactoryLubed *bool           `json:"factory_lubed,omitempty"`
	Force        *SwitchForce    `json:"force,omitempty"`
	Manufacturer *string         `json:"manufacturer,omitempty"`
	Material     *SwitchMaterial `json:"material,omitempty"`
	Name         string          `json:"name"`
	Notes        *string         `json:"notes,omitempty"`

	// Pins PCB mount pin count.
	Pins *int `json:"pins,omitempty"`

	// Purchase Same purchase-lifecycle tracking as Purchase, plus a quantity field since switches are bought in bulk.
	Purchase *SwitchPurchase `json:"purchase,omitempty"`
	Spring   *SwitchSpring   `json:"spring,omitempty"`

	// Type Open vocabulary — validated against the "switch_type" lookup at request time.
	Type string `json:"type"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// SwitchListPage defines model for SwitchListPage.
type SwitchListPage struct {
	Items      *[]SwitchSummary `json:"items,omitempty"`
	NextCursor *string          `json:"next_cursor,omitempty"`
}

// SwitchMaterial defines model for SwitchMaterial.
type SwitchMaterial struct {
	// BottomHousing Open vocabulary — validated against the "switch_material" lookup at request time.
	BottomHousing *string `json:"bottom_housing,omitempty"`

	// Stem Open vocabulary — validated against the "switch_material" lookup at request time.
	Stem *string `json:"stem,omitempty"`

	// TopHousing Open vocabulary — validated against the "switch_material" lookup at request time.
	TopHousing *string `json:"top_housing,omitempty"`
}

// SwitchPurchase Same purchase-lifecycle tracking as Purchase, plus a quantity field since switches are bought in bulk.
type SwitchPurchase struct {
	DeliveryDate *openapi_types.Date `json:"delivery_date,omitempty"`
	OrderDate    *openapi_types.Date `json:"order_date,omitempty"`

	// OrderStatus Open vocabulary — validated against the "order_status" lookup at request time.
	OrderStatus *string `json:"order_status,omitempty"`

	// Price A price in the collection's tracking currency.
	Price    *Money `json:"price,omitempty"`
	Quantity *int   `json:"quantity,omitempty"`

	// Vendor Open vocabulary — validated against the "vendor" lookup at request time.
	Vendor *string `json:"vendor,omitempty"`
}

// SwitchSpring defines model for SwitchSpring.
type SwitchSpring struct {
	// Material Open vocabulary — validated against the "switch_spring_material" lookup at request time.
	Material *string `json:"material,omitempty"`

	// PreTravel Pre-travel distance in mm.
	PreTravel *float64 `json:"pre_travel,omitempty"`

	// TotalTravel Total travel distance in mm.
	TotalTravel *float64 `json:"total_travel,omitempty"`
}

// SwitchSummary defines model for SwitchSummary.
type SwitchSummary struct {
	Brand *string `json:"brand,omitempty"`
	Id    *string `json:"id,omitempty"`

	// Image A freshly-minted presigned URL to the switch's image, if it has one set.
	Image       *SwitchImage `json:"image,omitempty"`
	Name        *string      `json:"name,omitempty"`
	OrderStatus *string      `json:"order_status,omitempty"`

	// Price Same as Switch.purchase.price - omitted for a switch the caller doesn't own.
	Price *Money `json:"price,omitempty"`

	// Type Open vocabulary — validated against the "switch_type" lookup at request time.
	Type *string `json:"type,omitempty"`
}

// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
type Visibility string

// BuildId defines model for BuildId.
type BuildId = string

// Cursor defines model for Cursor.
type Cursor = string

// KeyboardId defines model for KeyboardId.
type KeyboardId = string

// KeycapSetId defines model for KeycapSetId.
type KeycapSetId = string

// Limit defines model for Limit.
type Limit = int

// ProfileIdentifier defines model for ProfileIdentifier.
type ProfileIdentifier = string

// SwitchId defines model for SwitchId.
type SwitchId = string

// UserId defines model for UserId.
type UserId = string

// ConflictResponse RFC 9457 Problem Details.
type ConflictResponse = Problem

// NotFoundResponse RFC 9457 Problem Details.
type NotFoundResponse = Problem

// ProblemResponse RFC 9457 Problem Details.
type ProblemResponse = Problem

// ListProfilesParams defines parameters for ListProfiles.
type ListProfilesParams struct {
	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Username Case-sensitive begins-with filter on username. Mutually exclusive with discord_username.
	Username *string `form:"username,omitempty" json:"username,omitempty"`

	// DiscordUsername Case-insensitive begins-with filter on discord_username. Mutually exclusive with username.
	DiscordUsername *string `form:"discord_username,omitempty" json:"discord_username,omitempty"`
}

// ListBuildsParams defines parameters for ListBuilds.
type ListBuildsParams struct {
	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListKeyboardsParams defines parameters for ListKeyboards.
type ListKeyboardsParams struct {
	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// DeleteKeyboardParams defines parameters for DeleteKeyboard.
type DeleteKeyboardParams struct {
	// OnDelete How to handle a keyboard still referenced by one or more builds.
	OnDelete *DeleteKeyboardParamsOnDelete `form:"on_delete,omitempty" json:"on_delete,omitempty"`
}

// DeleteKeyboardParamsOnDelete defines parameters for DeleteKeyboard.
type DeleteKeyboardParamsOnDelete string

// ListKeycapSetsParams defines parameters for ListKeycapSets.
type ListKeycapSetsParams struct {
	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// DeleteKeycapSetParams defines parameters for DeleteKeycapSet.
type DeleteKeycapSetParams struct {
	// OnDelete How to handle a set still referenced by one or more builds.
	OnDelete *DeleteKeycapSetParamsOnDelete `form:"on_delete,omitempty" json:"on_delete,omitempty"`
}

// DeleteKeycapSetParamsOnDelete defines parameters for DeleteKeycapSet.
type DeleteKeycapSetParamsOnDelete string

// DeleteKeycapKitParams defines parameters for DeleteKeycapKit.
type DeleteKeycapKitParams struct {
	// OnDelete How to handle a kit still referenced by one or more builds.
	OnDelete *DeleteKeycapKitParamsOnDelete `form:"on_delete,omitempty" json:"on_delete,omitempty"`
}

// DeleteKeycapKitParamsOnDelete defines parameters for DeleteKeycapKit.
type DeleteKeycapKitParamsOnDelete string

// ListSwitchesParams defines parameters for ListSwitches.
type ListSwitchesParams struct {
	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// DeleteSwitchParams defines parameters for DeleteSwitch.
type DeleteSwitchParams struct {
	// OnDelete How to handle a switch still referenced by one or more builds.
	OnDelete *DeleteSwitchParamsOnDelete `form:"on_delete,omitempty" json:"on_delete,omitempty"`
}

// DeleteSwitchParamsOnDelete defines parameters for DeleteSwitch.
type DeleteSwitchParamsOnDelete string

// CreateProfileJSONRequestBody defines body for CreateProfile for application/json ContentType.
type CreateProfileJSONRequestBody = ProfileInput

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = ProfileInput

// SetProfileImageJSONRequestBody defines body for SetProfileImage for application/json ContentType.
type SetProfileImageJSONRequestBody = ImageUploadRequest

// CreateBuildJSONRequestBody defines body for CreateBuild for application/json ContentType.
type CreateBuildJSONRequestBody = BuildInput

// UpdateBuildJSONRequestBody defines body for UpdateBuild for application/json ContentType.
type UpdateBuildJSONRequestBody = BuildInput

// CreateBuildImageJSONRequestBody defines body for CreateBuildImage for application/json ContentType.
type CreateBuildImageJSONRequestBody = ImageUploadRequest

// CreateKeyboardJSONRequestBody defines body for CreateKeyboard for application/json ContentType.
type CreateKeyboardJSONRequestBody = KeyboardInput

// UpdateKeyboardJSONRequestBody defines body for UpdateKeyboard for application/json ContentType.
type UpdateKeyboardJSONRequestBody = KeyboardInput

// CreateKeyboardImageJSONRequestBody defines body for CreateKeyboardImage for application/json ContentType.
type CreateKeyboardImageJSONRequestBody = ImageUploadRequest

// CreateKeycapSetJSONRequestBody defines body for CreateKeycapSet for application/json ContentType.
type CreateKeycapSetJSONRequestBody = KeycapSetInput

// UpdateKeycapSetJSONRequestBody defines body for UpdateKeycapSet for application/json ContentType.
type UpdateKeycapSetJSONRequestBody = KeycapSetInput

// CreateKeycapKitJSONRequestBody defines body for CreateKeycapKit for application/json ContentType.
type CreateKeycapKitJSONRequestBody = KeycapKitInput

// UpdateKeycapKitJSONRequestBody defines body for UpdateKeycapKit for application/json ContentType.
type UpdateKeycapKitJSONRequestBody = KeycapKitInput

// SetKeycapKitImageJSONRequestBody defines body for SetKeycapKitImage for application/json ContentType.
type SetKeycapKitImageJSONRequestBody = ImageUploadRequest

// CreateSwitchJSONRequestBody defines body for CreateSwitch for application/json ContentType.
type CreateSwitchJSONRequestBody = SwitchInput

// UpdateSwitchJSONRequestBody defines body for UpdateSwitch for application/json ContentType.
type UpdateSwitchJSONRequestBody = SwitchInput

// SetSwitchImageJSONRequestBody defines body for SetSwitchImage for application/json ContentType.
type SetSwitchImageJSONRequestBody = ImageUploadRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3tctu4luCroLgzFXuHltyd7rvVTk3VppN0X0/St11xcu+PxOsLkUcWxhTAC4B21ClXzTvsPuE8yRbO",
	"AUBSIvVhS7aTm1+2JBIfBwfn++NzkqlpqSRIa5Kjz0nJNZ+CBY2ffq5EkR/n7t8cTKZFaYWSyVFyCvoK",
	"9MEFSNDcQs5EDtKKsQDNxkozOwE2ci8PkjQR7o2S20mSJpJPITlKRn7gNNHwj0poyJMjqytIE5NNYMrd",
	"jHZWukeN1UJeJDc3afKi0kbpxdX8XvJ/VMBKfiEkd9+xDJ9kY62mjLNSw5VQlWEaTKmkgSeGSfhkz+mx",
	"uMZ/VKBn9SLp12T5ml7DbKS4vjWULv37PYC6rIffDFavYZbx8hTsHRaW8ZIZsP1LizNstrY3Yirs4qp+",
	"45/EtJoyWU1HoJkaM2FhaphVTIOttOw7qALHa86Zw5hXhU2Ovj9MkymNmxx9d+g+Cek/pWFpQlq4AI1r",
	"O9FqLAo4jgBZXOcrYSegEa/wWaauJegnhh3nJ8xUo/+EzDKCotCsMqDdOgfsLRhVVIifVgswCObmO2Oh",
	"jWVc5mzMi8KwEc8u3e55HIQVSl1WZcpM61s74ZZNeFmChNy9MeU2mzAeRybgs2tVFTkbATMTnqtryNme",
	"kKzUPLMiA1yPvVbsihcVMFPyDAzLFZPKMnUFuuDl/uCj7EaHGoU2xIbTa2GzyW3R1ODbPShqwtCbrei9",
	"Ad21nndz56XGuASHpU8MYQH77//6f/jl3001+jvLCi6m7jkuGc8yMA6bL0GmeMr4nDvEc5H/nY0FFDk+",
	"GxBrwI7dDMLQeXqM4ZWdODBkCJKMFwUin7qWYWEpPud2DMYyYRi/4EIa6zHSPZmpooDM7QsnEZY5kBnG",
	"WS7GY9AgLaLXkqE4PfHENAY7Yhp4bvx9ZUoWs3CJw/Nswg2DT2UhMmGLmUNFDTm7FnaCc9GG2J7SKR4y",
	"Z6aETIxFhiOlftAxjei+csvqGcWdhnK39VoYYJz9cPhDiujs/n2a4uW6UiJnGq6AF+6O4LBc0sjwSRhr",
	"2Khye5dPrJ9n/xm71sKCYXuZBm5hWJW5+5NDARb2GS+u+cywMRcFrQmnZkLScWbcQMqMkJlblF9rxiWT",
	"cAWaTVUuxjPGJS49QBnhOGB/wdWfHB8PDWSVFnbGMiUz0NLtBj6VyoCbiLP3b98gALhsYa07RMkU8cz6",
	"RhFcctDiCnLinDB163dnIGcExvD8zEGKW6vFqLLQSxMqukib3L6bNAlcGkWQF0qOC5HZt/5L912mpAWJ",
	"HISXDpGQ6Q9LrUYFTP/tP427rZ8bk/yLhnFylPyPYS3sDOlXMzyht2jqxftes0EHCJRb2DU3dEYCcjaa",
	"uSNUMqs03ppwV64njjXgcSsJ+I6QbFyIi4ml66+B2MA1aGDwacIrYyEfsFM+Bs/09Kx1/7g5EMZB+yZN",
	"/qLsL6qS+UMBxq8J3D6MqnQGLFdgEIvw2qQOYPGrERTK3S7VQcMcmgwSYr5uyofY0nPJQGtPdKbcunWV",
	"oNnbX16wn3748X+xPf8yewmWi8K459if3707Yc9Pjs3+ADmHnyjKzt08xNFIpqHUYEBa3BDRfRKZ2XtZ",
	"iEtgJH3LsrJpFBNTz/DAfDgb0L+ETISn55fCul/8J4e1XAPLQbpNFeIPx0Ql4pZRxRUeHlL7DJhC8mCY",
	"5njT7YRLNnJvi9x4gSMrhENxR6k0yBx0WDMSOVVZNlZFoa4PqjLghyHiUGpVgraCLjW+c+4opvtEAE+O",
	"EvwinScJaeLI5flUVdKe02/LTxnh9oIb+M298s69cZMmY8WnDYIzUqoAjjdJ5B2EKE3ElF+AWTzB37jk",
	"F5CzK8ERl3PIPR7jGwxkXiohHduAQl0TXXUPn7x/x5SsdSMmrIFijDTaALCT30/fDV++evPq3Ss2GAyG",
	"+JAZfvbK0s2QVvRh+Bn/Oc5vzjzldZxhLagcuxfd5vxuudZ85j4H/FprlKDzvIWxfzegnnt9/dWQjvJa",
	"2FfS6tlbj5Jdy5PK0lEsnFJZeCxqH9LfJiKbBAEtbO6JYTkYcSEH+JZhCh83TDjabKzjw6iILcxiLB+t",
	"t6dTfNK94u/pZiAhYXglPKyyvDjPlLGrRv1NScBXroQRI1EIO1v1yl/rJ29umrz7QyLypDXSWVwaUQ83",
	"Ucf1O/o8RwDySis0M3Qp8yDZlcr4qCq4nuHtuOKFyPGKNSRZ9jHQkTDYx8TrR4zXfNgKp3v97oTGKXAp",
	"5MW4Ktj1BOgmZhNlQDKkLszthZmqLJW2hgnL9ty9jBf2fI4Q+dmemPhOvRY2LviF15YW0ClQsbvufG49",
	"/ftfXMRN38kRiVg4MSQ55+JWWpq7Xu71lFVSOKnTcQsh21aiBSBVulic7DkbazCTYnYwFdKC44cTpe1B",
	"gVKr46jiwunAp0/Zr6/eORF4wH6NK5Nw7SiwE7JnbAy2JhFEkB3Evb6b8WwCTGlWgjYC4S4Macapwwz4",
	"VAoNnrtFDlZp0Qnq1h0KkKQtni09iPdloXi+3eMAB4didkCqi2db3UeAs593nsRJE9Yn7z2sTxun4aBJ",
	"IziFdlraYnZHcNXL6Yeak5cW4fW4JI4mt21D9fglSYKBxUbh2p3PVMg3IC/sBI1XJbcWtHvp48fTrk1s",
	"iS9/48eTXjhshalGbFiPtTalrw76iJj+xLRl/gY6eXF/sCiUay57JOElAvL5lsh0pE1xhXkTT8g06rmI",
	"QIOVsyMpCQ9P39Ok4DNFVGfhJ7KEdPxgxB/QbX5cELjoZPxYy/CieWsXSGCtEy4lO2TTvxPd6TLuXwp7",
	"LtC8qSTQqXDbsK48McwRKpK44lYG9Nr+xqtYvGJh77S+NaEYZfAV0FyTpJ6CDToT7msZmBbvQgtSSwDV",
	"dSDnu7+swq3ssd5QB4JwFdu7f9mkk+6RLuALO1iNY3SkKzDLo8AGhDteyO1R7l6i5B0PW6VLb4SxJ906",
	"RWDDG/DjajrlPTJJ7dGt1/8hbCBNZFUUyVm/4nMaZIr2IttS4F01Nie4CHe0+pZ6W31421vKZvOXWmSw",
	"ptmhH9j+HBc5kcyKKidPVPMiBFmAIdIN8aKiTdKb0gzTkKkLKf7go8I7QAphnOUNrqN5ki8aKLdgn1wm",
	"H21mltvIDOdhGGS7W9mFVh3Q615NpYdgdZwT+fFyYcqCz+ZOZhNi1kO1+rfQkN0XrnXmbp/7Z1k8QNAa",
	"+gUmmuP20tIcWfXTpX55Z2tsrV9E2XiLa2pDKMLMLXyt9W7C+CJgvyB9hSD5iKWgKZfVmGe20qA3EwwC",
	"/9tUKvBvdiHGC24ynsNLdJm/BYPxOvMH8xYDCYKbldzr6DBnU56TIZEpeU4//HtGQ6ZIX8iZj+4rB10C",
	"NsEXdQ/nkaX3csadc9KIHJruVsjR597FIPx758QoRN6WYnqgF0SVOaAtjtUFrYY18C0trwtY+AMbqXyG",
	"+El7Rmw88Ja44J1ie/MuxTTGM/ErbrlOg85xKWxKgNsfMOe/9EMJ46KFDoyF8ijENRQF40WhMjTncGYK",
	"ZYOvu9LSMN6+TN5uiFEm3h5PLsaT9+8o2mU0cyOh25hb92yIp8CQGHfGL8hDfODMbl1n5T3IWxDhiIA0",
	"x1sqOcEnPi0LpLbuxWGJYujyG9RabBceNBkyL4rfx8nRh+WUO7xBltGbdEEKv3/3ZxQSVnhAw3Nm+LkO",
	"hLyjHzSCo9sVukjRFk/hrHEOLxGbOwzOylo1RQ/NSlGMW9CCFy9UoXS0obZJyu2RNgDuHEc9n/rJNpP5",
	"F/2P5e22dg0u/mXD126W3IN7dlc1w3Uf1mMV79BjcVq1TuSb32p9v1WbQC9SkiDnbmiGzSNlWoccejrW",
	"MmZvgejQYL3EJmUC9f0YeNlwydOrjBBY5AsR887tLv6AHhd7kGQ3BNoSx1Y2WheWJy9+xjcqnU3WIJIn",
	"4bmGV2ALoHdDbUblt+LNmhP/V3i0Asi2ZSQM4+3GTtg84IWFcmNgOipm22LX2eg8DHkLK2GmpITMiith",
	"t7mi5rC3WNVY6Ok117DFFYUhN1uInYjsUoLBk4uC+neDPzWofK6qUdEw+FFeynJxpNeu+RbyCm0EE16C",
	"V4cwGJNsYTHmeVt2jo3F4Nv4MJXOQTtDsq16iOYGtuJlLtEueJPjayM9iF7pVYTWhJsfJdpshb2lQCMM",
	"6dadYmYj+eqWfqezJpx65OT7EVlvIaKy5+zSG8+4ZVNlLDqOScfcE9awK5C50j4Q2QWE51Vm3Urtfr9C",
	"KazTJYWNauQtJLslclwD1n0S8GOQTVcLpM2bsrCFbg8UDC4G7GPyMzfwMUnZx+TVJwvSCCXp4/Msczfp",
	"Y3KLkIJSi26y+vtUWGYVK4BfkfGOPOT+BcQhEoQpzL6SVlXZxKVZWF0Bm/JLMPEqdg+QMg1lwTPMoHNx",
	"TA61CTshGBObc4xgrDQMXBKfAZYVwLXxppL4UIo5RXUqk59f0IMhlyQs4qCRxIRuds6kOlDlgL2EQozw",
	"4hUzvCxSMZ/8eOSMZMIYt2zKLZtWxjJj+YzlZB+thJmgu4wSZWXMy6K1t0TrRvja5oLtHP71Ooyju3tT",
	"sn4KHlnXtm+FsLh1rVvueNaxbRmwnWatk/fzpq2MlwcGLBm3/B7yG6RRHwKR2tCy5Xlih9Q7z6rngyAw",
	"7SvF1JQDREtDkkxtOqcAj3D2g+aAR7jzArixB6VWFxqMgZzRj4xPFZnip+xaSMP2TgouHZH7WB0ePs3Y",
	"726k+uPpRJRl/dFh+JX7fR+TUCKIfTqeS2bkpn7K513xcJ2MFUXBQDKtXKaaZytoQ/bLe8FlBkUBaNCG",
	"T+h+9glweLUdpLkWBqlHAcbU8GCi8brTZYk+YH6fNyQ1x7dKDdhfqqJwd16qmsFJ1oSm21/KQn4r2HCv",
	"HWI0r+SizhIJ5XmfUIIpbfhbGs9FmEYAVsquJ5hBiIw2JimZGvBt/229H6SKYenCG6mEDbmluduCc7OA",
	"DmmV7n74TGUv34f0JVyho+tjIT2FbcQXLQfCBhbcJuHYmt0lWFjvrOO4+LLbmWu3b/yo44LuvCU/1pdg",
	"miD82KJtggbcmXGiPXw/Rt85Tmw5NznlU4iZxPziQsMFt+DIdFxji32wA+bzbDQ0yoeMRgVgoE5VwEZ0",
	"73Z6XH/s25biat4gunepW/4iOEHjQumZE/DKUisHPtSMjBOs6b+PCROGlQUX0ld1QKYFpUXIdZlenf+1",
	"N2Mo0HuQlIzMdZ0JGo+FeQuJl3s6vax+7S17SkI6WueFxt00njbJ0YcPyfMp/0O50V9wKZV8DTPnDv8Q",
	"dI7kb68TshO4x5M/Hf5rkiZ/+vFfk7Ob5lO/cnMJlmE2hnt+ITuL8tBvzs5q0WqVJzBuMK69i2i0PVcd",
	"R11OZkZkvGAl16g2ZFqMKL4h0Ho8sMwNsGgMyrrH/UW7g4JPdrArjqShgCsuLfufkSfdLdmMLkoXhLTI",
	"gHlDSF1a4olhVvPs0qkzpB9ls5aX/bvvnw5++HEN+13MM++w0oVs77lk7w6rXKFwLe0QkEV1HqRT87D+",
	"w0/RyscyXhk69FBAxAuqI3D7a8QUjWYUMK/ZVGkfH2QG7A0KUI3wFvdvWFN4qq06rHTq5rjXzkcxG0dm",
	"0PMjosw51o5qs8M5C7kLvYT8vL776y+ulxVp4L4GwBpINz/qgumyERdnhSVuUJOzv9LVcEr+K627CRt9",
	"0XxrYm1pjobD6ewSYGQGQo7VEIsNmOFVHPEA/IgbWXLw17DWuJ8uynRSs7f1FGv/Qp9aTUFCydF6gwQm",
	"66vddCsmS+opDdh7tH0wTlj/mUqL3LCSO00OLqb+orWJBml9hu05O+Xw6rtmRIkfIcXvQ659/BJsNtj3",
	"NZuuoFHsaTSr6y6RwCK0sT6CCSs7dJfGMXTbhWEi7/RZ3nRqKS0A7sp8G4Uuv0kngODx3sGuK+yANa0p",
	"86ZYP1UE+dDHXASTCqcwtpP377Zoom1Cc1sG2gi8ALJ7t9e2buqi1C+U+zPln4Iu+OPhYRylES8gTKZ0",
	"fh6we3H3rvTQFWiqexOEg5f0movfFRoyq/SMjJtobST13kGHHF8YNO1fYf97wmVewBH7/uDp9yybcG1S",
	"5liERgNKAdaC+yoXF2iZKEELlaN9oZI5aDcKYgwrgLsYgqHVXGAVJ3q048nM8d+ssuIK/EOeTzbg8/T7",
	"PvBcgXb20laJOTSVpgv5ruCrqAhTx1WWJdqChWSBHvmfDMp8mMTg6I2bAyNe5cwxf27nnx9+rp1JNwP2",
	"N0d7aB1kU7YTT0V9rRae43101nJ3lVEgceg7BS4Nvcn2xlVRHJCpG5iBKZdWZGa/zwpcCHm5vvLrcfSN",
	"kJckkn46ptd+XOTK/Rj4ph85JrNyArJGkvrcn7Gn//1f/9djGM/ca8+WIE09VAt7nvVhD3seEPrA7Ztb",
	"4U7PVI4QgqXKOXI2j/Rs7+m/Ecrvu3PnPsilrhb4npyCPNPKGMaLIqCRSdG+eGBAGuFWUszYHsXNcN0w",
	"F1ZlSbDaR+aZO9Y5rIafwxQ3QcYeaww6zREHyRxZY5fDlaXIR7pgNC39nw/84I/Dg5/O/N/zwcHZ5+/S",
	"p4c34Yd/WU3uwvkvIXaISGt6pl761JOCj6CI5Nrhb8q81+odhkB/TBjq0L/F4/LeqjZt2NCs1s2kJUO5",
	"kFx87t+U4V2BAw0Fd+dKhZ2kkgfu5z2z7x8gJV2Dg4hzZL2SY6WzWp0gBNNsjwrd0Q1kfpn7wYhO7zsZ",
	"iSr/eTU/swgY80GcDSpdkDAz5sJl4n+UK4/Om9ZWcKptWdT8cLuxp80NvniCNcM7CPkGWl3P+eTUVDh3",
	"kVB4mAhaXyNSGSBriyPYXnJ1JHjpdYsqZJcN5nYieRff7ze03VaAT5lxEjOVFuWG+VUM/HgBAM5bWcBB",
	"GCjulgVder4OWTbhAisfLkDNj3zDlA5yOXSI5T3xg4vQWKpYnjRconOmGXekwWt2UIgxZLOsgGjMSFkw",
	"BUTdpFHQDV0ulBhPrqULsMyAU7UtkNdomJPva8ZyyrqQwfO235O6gk+vn95IptoNH++zDW/iMGiOtLsc",
	"1TRYKe+0VhrjrhWYTmMu3no6Oj1/m8yO5GitkYlIrOtSo5d+cdyow/qT2YoTZBdIafiJISdjQrILZ0ty",
	"LGwqJC+IbmB1gzXMez73ojOK+Wf87YBqFd55rv4z/ALjrSgNbP2QK7ZezBUNC2b4OZRj3n7oVQPmX3Dc",
	"VfM2b80d7fI9lZ6dF9UI8u5yVONwYVcTBLrb66SSNp0Oq8cNfpPdeK+F7LLOv/jZl/0rhWSYwNzyJ/zY",
	"lSy9bugT7aoV2V/ictZ677TcXqVAunS3iNXehcvdm6tXeN4JCNtSEjxId6IjzCFvXxbgRFXGH/6dD/J2",
	"ESHGwvQBp3f5gg8NhP7z6xfeMZJhifCOmoz/OWVlURnG2T8qLq2wMx91SWXeAxdElW+kqosJhlKNquLy",
	"m5S+lpQewNrtrXtsMvxpJPftg91OdJi/BsRTbnknSw3nVvMr6BaIDug3DBV2rl+HrdPpmhI4xcv0jf7O",
	"/cpuP/4SqG8t9GlzJen+8mQeTCjoAvxfW2LCvBdE1Q4I8n1amKJ7T1iDykxw0Hb10QhtNLxA0WzsYRUb",
	"wUL3lZRpuOA6xyhdNWa1nLHvjLxlNSpE9jGhLiXoZMFAYKmaDQmcGsqts7i7dxo/QN56lfwzjBSHAyF9",
	"vxTn+kLDq1RyNlWV8UvGGK5SiytuoTUO2v9GDZ8NFtnQwASa8UvQB25khtEThTB2aCbcnQebQjbhUpgp",
	"G8FMUUMZDDzGaCABmkyNNRRoSMtMpkpqFBR7q9StRrxFDGQ1dWIQAS1J25BI0rCX5KwLTUJvklOyWGND",
	"BOAa9PPKon1jhJ9+CVf9P/72LuloyXCcnxwIYyrI2e/HL1+w//jbO7bnhlBa/EFHRcP6aHFsroP/kgJP",
	"BnOn7eBTNUY7izq1gXDRGKFMCM9sVNI7wzaSxb4RJ8fkUYgSAWrayhkS/PlkvKiz9Zu9csKXpu7qkDbs",
	"fqbuEkThCTEefSQkIv90wN7S/eEamKSaNeiyQlMonmbtYB8MBnjkFA3HRgrrqLQaCNWrw6mpdU8DNdjE",
	"pdn0d++ZRitAMLYe5xSiERvLUdHfAMHojSHXg66KUJ6gEBn4HiBEV5Pfjt8l6dzhXAg7qUaDTE2HWl1U",
	"YECDFHY2vBzlo+GoUKPhlAs5fHP84tVfTl814noS94Tr3eH0EdCGjvO7weHg0D2lSpC8FMlR8nTw3eCQ",
	"fFwTRGQHWiKZ+PECeusWmRjS6Z0s7q5TiAO1YqJIKHbg7TZow/ZDDz+Hd2/m+yAtiRNF0DnGh5fDNbFK",
	"nB71xi93rrnO94eHS3qsLPZWibrxhzqyc04iT9J2BnqSzkekJmfrB6V19GkpivlwWYItNpD54fCwj4vG",
	"jQ/nu8zcpLUzf+N3G7QuOfpwliYmiCAIeMb71pukieUXGMYakAl1zAZ2NVBgJaJhe6lxPQflx8Rau+AR",
	"UDfqaTWxrQtxfgWPN3dFm2VCjZ9hZZOhORj60/5h9Ykt9Ena1XH/CgTvlcHcnSeftlpvfugMou7osNWI",
	"Sl6/x9aZR7MuB2Nd3awrS8x9bxpy2BNT96qrB6HQnxG0H3T8pdmHzLung6ONDMg4tWejNDARPwqEgcI0",
	"hMKI+E5golwrzgrgYxoFjhyhnbTiaU09bsgmi4KWLx4XO/h5VyGx3rTJrB1rJKZIDPISoGz01mvIW+5J",
	"x5pj2umzOj4neo9jtbpCGTBxbl9rzYPHLXKsAagOiobKQJQOyO/rw/ax7CCXs5RhONHUId6AHecwLZW7",
	"rkc1jOsmKCRU+8CRAHiKSA5w/v7why4iQTgRgksXCMUPyx3FjRp8MeMtLgZjH+BuN/2Hw5/uuzFac28U",
	"zh17xdVt4opZPL1Q1BB7c1KrNIaLdO053dVlywKIM98fD2NVrZ757nB3o3CRpr30eljYVIN0+W+Idi1l",
	"TY3A0ppIIAdqdh8k9/aUz9z+QfjoubWbqz7HQJlmkF49Z4Pt0e1TqH7iyGyvq5+mT4oJ8/n2m/vP3KtN",
	"WkTtFXNPo5okEEV1/17zUpFmGYlMOAi3yNicEltTYqBD356eGMqhBDScIKunDpaQd13SX8H23tDtsfIw",
	"xUpeHljGo+Dhn53fvKmbfnC5RHN8feUFmGPeXSuqHxkuNhl2U5aqq6jnCzSM9DHdX0IhkXjg2+HDaI7Z",
	"nA8/b7Z45ZktKHvFD3HEODOQOUsFjg+Nl3/ytM55jBdJ2/F4rjBrky3yQgPPZ9RsN5aK7Wxj27xsP3mt",
	"dW7WMPJBJfkVFwVeO6PakZLOqGUqPeYZJSU0jGtxZWj977qNdKLNC4m7+lnls23fRR8ZcnMzLx7eLNCB",
	"7+6LDoTyfW0qcDu97UuRC17V/MwzmIC0GG0R79gG/J7F+tNdd8LyS5BkoqzNN2sM34X9vuqv6wyOzUTr",
	"2iF1zKnfO/u7m+Hv0cThg0+3K5TQ/VmDJledQgnGt+9UiUEj9qbEM2XcULvc+Ppy+byp9WDcqA/dP/Kp",
	"M662iKXqLiLWqXGcwicBCEO1aZyYiVHQ+IOb10WrKu2DVWFaWt+sfuoxwesb3pjcPZvPZyhgbGvtx1d8",
	"cElBTNgN0oIenAN00fH3Zf4I6fi9yXPkqvmnpeO3xsTbUmHWztFbW7/ETvV3Vi/x6mJH8o25wXapP926",
	"VdR/iYVrGF27fXaurTABNL0gE5CBYM4xAbR4LKfxaaeU3TTm1CwmujJpMgP2FhYc8mWvY8Z5OWe2Ccsg",
	"u01IhtzG5V7+4guPodvTDSOqvXVHOHf2tK/7VwO3gpMGrN0NSj5vnH87fNhP5KZ344lQcgp1piCzGCYs",
	"pmdKIL+0N4phbvWAvVRAsoYPwXWLw1vsK60dLTD37j4TzQ4TNBTJgRiaXvghY8cJMtAWnuDV47mBPBdu",
	"pk01WzewC3EFkvLDfWaLXzoZflAy8gUcnAeZkrHcuVTS+2chb49YlaR+pr6+IAZ8M2FMFSTNxvrIRo1T",
	"nD5tjh7gxy3KmvKJN1Kx69ASJfK1LlpxCnaBUGxf6OnodfIwKmxjIZ2+yHiNsM/JBBkyyNgBJX+2iLAR",
	"u+pYcLb353fvThyOpqG5SbOnCZsAz0HTOYWmNh3I5rM5/YHsuznczvAeCeuZ8EMJaA9Gw0/Bsj2lA6HZ",
	"X5+at0WIflc/EgcMkqldOmiMR+qIBucwBh1vy6BrAOuXOoR+xrhLIGQZ11o4PdCnxm2e8uajkJBCNJW5",
	"AXs+H5WEQpwvzOKiSa7pG+VrMjaqXaShzhRSD87m8wbZWBQWNL1qgigY0/nzmAFN+amDODDSqoXRcBUI",
	"Y16wEVwIaQ4QfKWGsfjkZzPRxTatHA0vZlTC0Ygrss47alrMUKtVdtJgWofoM6hDv5kwLi5XIvtBYx9t",
	"RwSy6D0IGF7zDD1wbtRQTLIp5fs3m3P1xGWcBOTaVHR4I6aCUr5WPPgCN4dPztmVWznkLQiHg5QN/8pv",
	"i+CtkblxbrRT9FT/owJ0THtXdXgiWeaa7l6mkKsWurCM3gWvXuj8WEsXfLZ7BTwmQnSxIFY6rqLGrMtN",
	"9DiCYlZ6WNwGu9e/lDLPhbeRo76XTB+PQzyaMIuic8xSLoSxVG5BjduPhdJbv4dSzOFh79Gvi/7Qk0vC",
	"5PygbK9UxoiRQ9Jp6YJUe8jEz7S1nROJXSJzuxfwUlT2kP5ycHcUzicgq/9ic5XwPaLoEj3Q43CvDugR",
	"+VntwROy5QRoZb936XK9His8wR2J/Dj2g3iraFcrfFV4ng+IkIu+j5E/jAWMW0Ych5/x73G+NMxrbRSr",
	"g7Xa+IWTrIlaZEaqUWtNs9NDxg4sRsf0HsYakTEELGoV66qrygsTJFCCeqinXYesOEXTc5QgftaPD1gz",
	"JHTPx5Psh4rcNF0eDCoYRZIGV44bPhpxw+zek+N+72Fj0abBr5TIjQ9FiT29yKoR1gtTmrQv5LQHFQ7v",
	"58LXVv3mlf8yQlSWYOHtmNBqwYHItudX1V3YVe0zvT0tIdfAY2JT94S1wRW3BZx9aHtNdO/ckcEN6/61",
	"94L8dxPWeJ57uzwum8IM17sHDI2UPgPI0ejgh4/e9UZzEhrFtyfZMwCsxuj9mo57DQkVm2uOAZPcWp5N",
	"qJH5N3P8IzHHN+Tyr9seX29xqTWeMOabMX7Hcu/zPG+Tqi0R67qh91bUk6YHntbq21xtQ1nZ2FH+KDQW",
	"79GeA8iDSo5plz8lNE+uze7RKU0Ld6SR5znkg2DEbedFeUS6VVrUHLLGxJ/dmRbjFOtYF+PDWzQwvo57",
	"/KJtjAvdhJeaGWuofzmWxsvGQYXbWn/3ddkbw2nuSKppt12/Z4Em7m2F4TGc7aOyPV7WB9OFgyvI6PBz",
	"+HfXdsgwT6fapOR5zLyTVqvCkNA94WUJ0sQOdmGM2Euw3ZzFM88j12HJtV/5mFAxbg/zfayd7B3/LuKY",
	"qgCH5i3tji1M5OYZ+5j4TNSPCe0MTHslbgiq9khvIXNopLhSx1K3VS+gCh1GzsFpcX0D18VTUmyo2kyd",
	"jYs00d/N5QUa+eL7vRkvJAI17vMckWqf+5/VNbPKhwk00K0T/h3NcXrcuvHAW/7ceDfo+BqFT8JnfxpJ",
	"6qHXVfBkl0ztBc1PMHwLxq22g2rQ79Rrwy/5WRPTGhVErgFjPkwIsyPqskx4ZXsIjRhjWmMbWqcJMPtf",
	"VKruz25DizjUge97EXP+HaGQsuYFH+zCobCCwq7hVqjp1n15FuKMj9i50BIpdiyErnYxzDH3L8PLsBI1",
	"d6UxRnltl+6GZSJDr8fh8Qmq94fNwfXwGHB50YmwRUn1HhwK8xi+a5/CUvl4E7dCHKjpWWih7Tfnwhfq",
	"XIin+FX7F1q7/OZieIwuhu2T8gdxN2woYLQ156/K6fAoBMkvwfuQ8dJl1+/W/xBqjq7pgQiPb9cHQb3h",
	"v3wnBO1jbS9EhP0X5YcIq27f34isX50vgg51dzoejf9Q3gi/u9XuCH/sj80h4ZfVi4wrqStKCP4Mdu+X",
	"8Mu9rWeCyxm7FDbIgG6kB/dP4HZWuCYa697US+GGv72DIuPl+aWw5sMZA+nLJPbKWvGmb+SmaBZc+Oah",
	"+OaheCweilhr0k9FfdVRefW3+xyHORc5dYzcjT9jFYFez6fhR7lXr0aY83H7NRriya4F27U8G2054Yvx",
	"baxG0x2qpUH82K2DY4nssczF8ejk33vE7IaXYyt4/WiyLLYvOQ+dmLVjL0n7nmzHTYJyaaePZLP70tQX",
	"X4vd3pfX4iH1xdfCT7xEXxR28E9Zdgbt1xGldnXNhp8vxQ60VVx3j/HabwOFrNqQ679tO5u8mNSouzJf",
	"vm6+5QPuBoWm0rd7byu4EvtqMaxNuH4En3gEyrFbxNbj9sRWNWL2HPeYcUma1xR4C/jLak3uVVJDgVfe",
	"qvpgfE+PukQks7505GjmbOqxmOaCasI7lJM14gsjzd0swFB809y/ae7bLxM7egAFPtbjXOfWStUxxDMq",
	"87ozU4B4cOWq0+l3KWy3y+/SVwDzMk2Pyw9Z12YOv+2peLhGJbeq6z0u2fXw/mTXqOuJr0bJE7sRO1dX",
	"Ur5F8IRb7RPjHe1bwOk52eCeQygeSQnjFlS/kd9Afu9mOYjVlO+Esuw5bnG+bDIN9q1q8ldSNbmD/nyl",
	"cZSNbX4LpPyaCievx0O65YnQ3np3IWxhhnXi18KzWwxeOw0b/KJD12gX68WtRYB/OUFrpj6kgLzxq68r",
	"XI0OckdshgZ/EMeD39cKrwMd6qOKUDPhQDoQbznJHH6m/3YdlEaz3CVV3o/w8IFofidbNrf7YW9pcQ/H",
	"+eFsEOC0xJQd7+9mEWg08DdT9jdT9j9HmvwyqrpGPFm4iPcVS+bne8RxZA25Yaci5uoIshYP/zKix5Zj",
	"465Ma14a22XMWL9o0OtDeFwC6H2hb3AdPDzyLjoBtiKB7sbiT8MvsaBuhIBNCeqf1drfhujDkqRtGdnv",
	"gCXsefjxm5n9qzazz9/6r9HG3tjjNwP712VgX4dsz8umXYIp6KtA1CtdJEdJaPHMSzFotnlGCu0nmSfR",
	"sSasOz++aJBE3ahbKRk0HLNhlA6/bzCa32mCCJrF8V838tT3fDtsoZmQubgSuSOql8Ka/bvuL3o/FldA",
	"jbscto+E9L5iD5A0moSIHtJAuKK0Z0VrLcjXbl5cy/Oy1OrKmT54UYG3eYyVZs6Sc1CIS9+637C9K5C5",
	"0iZ1Nxu04IVJY0u2lIHNBhTZKZVstBC8KNSINwxPLOeWp23dlktqKOk0ZZ6bwKqYVIxXdgLSeqLIuHXU",
	"6pnbpAZfhsj3MteqsmAaey6UuqzKzk0HKPoOndRG2c5w+XVnS+oDmrKRUOlcn8qUWmfiCx6H2r3qYtNP",
	"psasFkjMk0YXvrjS8FVyc3bz/wcA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
