// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Visibility.
const (
	Authenticated Visibility = "authenticated"
	Private       Visibility = "private"
	Public        Visibility = "public"
)

// Valid indicates whether the value is a known member of the Visibility enum.
func (e Visibility) Valid() bool {
	switch e {
	case Authenticated:
		return true
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// Defines values for DeleteKeyboardParamsOnDelete.
const (
	DeleteKeyboardParamsOnDeleteBlock   DeleteKeyboardParamsOnDelete = "block"
	DeleteKeyboardParamsOnDeleteCascade DeleteKeyboardParamsOnDelete = "cascade"
	DeleteKeyboardParamsOnDeleteDetach  DeleteKeyboardParamsOnDelete = "detach"
)

// Valid indicates whether the value is a known member of the DeleteKeyboardParamsOnDelete enum.
func (e DeleteKeyboardParamsOnDelete) Valid() bool {
	switch e {
	case DeleteKeyboardParamsOnDeleteBlock:
		return true
	case DeleteKeyboardParamsOnDeleteCascade:
		return true
	case DeleteKeyboardParamsOnDeleteDetach:
		return true
	default:
		return false
	}
}

// Defines values for DeleteKeycapSetParamsOnDelete.
const (
	DeleteKeycapSetParamsOnDeleteBlock   DeleteKeycapSetParamsOnDelete = "block"
	DeleteKeycapSetParamsOnDeleteCascade DeleteKeycapSetParamsOnDelete = "cascade"
	DeleteKeycapSetParamsOnDeleteDetach  DeleteKeycapSetParamsOnDelete = "detach"
)

// Valid indicates whether the value is a known member of the DeleteKeycapSetParamsOnDelete enum.
func (e DeleteKeycapSetParamsOnDelete) Valid() bool {
	switch e {
	case DeleteKeycapSetParamsOnDeleteBlock:
		return true
	case DeleteKeycapSetParamsOnDeleteCascade:
		return true
	case DeleteKeycapSetParamsOnDeleteDetach:
		return true
	default:
		return false
	}
}

// Defines values for DeleteKeycapKitParamsOnDelete.
const (
	DeleteKeycapKitParamsOnDeleteBlock   DeleteKeycapKitParamsOnDelete = "block"
	DeleteKeycapKitParamsOnDeleteCascade DeleteKeycapKitParamsOnDelete = "cascade"
	DeleteKeycapKitParamsOnDeleteDetach  DeleteKeycapKitParamsOnDelete = "detach"
)

// Valid indicates whether the value is a known member of the DeleteKeycapKitParamsOnDelete enum.
func (e DeleteKeycapKitParamsOnDelete) Valid() bool {
	switch e {
	case DeleteKeycapKitParamsOnDeleteBlock:
		return true
	case DeleteKeycapKitParamsOnDeleteCascade:
		return true
	case DeleteKeycapKitParamsOnDeleteDetach:
		return true
	default:
		return false
	}
}

// Defines values for DeleteSwitchParamsOnDelete.
const (
	DeleteSwitchParamsOnDeleteBlock   DeleteSwitchParamsOnDelete = "block"
	DeleteSwitchParamsOnDeleteCascade DeleteSwitchParamsOnDelete = "cascade"
	DeleteSwitchParamsOnDeleteDetach  DeleteSwitchParamsOnDelete = "detach"
)

// Valid indicates whether the value is a known member of the DeleteSwitchParamsOnDelete enum.
func (e DeleteSwitchParamsOnDelete) Valid() bool {
	switch e {
	case DeleteSwitchParamsOnDeleteBlock:
		return true
	case DeleteSwitchParamsOnDeleteCascade:
		return true
	case DeleteSwitchParamsOnDeleteDetach:
		return true
	default:
		return false
	}
}

// Build defines model for Build.
type Build struct {
	BuildDate     *openapi_types.Date `json:"build_date,omitempty"`
	CaseMountType *BuildCaseMountType `json:"case_mount_type,omitempty"`
	Foam          *bool               `json:"foam,omitempty"`
	Id            string              `json:"id"`

	// Images Managed via the dedicated image endpoints below, not via PUT on the build itself — see POST/DELETE .../builds/{buildId}/images[/{imageId}].
	Images *[]BuildImage `json:"images,omitempty"`

	// Keyboard ID of a Keyboard resource.
	Keyboard   string                 `json:"keyboard"`
	KeycapKits *[]BuildKeycapKitEntry `json:"keycap_kits,omitempty"`
	Notes      *string                `json:"notes,omitempty"`

	// Plate Which of the keyboard's design.plates options is installed.
	Plate    *string             `json:"plate,omitempty"`
	Stabs    *BuildStabs         `json:"stabs,omitempty"`
	Switches *[]BuildSwitchEntry `json:"switches,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// BuildCaseMountType defines model for BuildCaseMountType.
type BuildCaseMountType struct {
	// Durometer Open vocabulary — validated against the "build_durometer" lookup at request time. Only meaningful when the chosen mount type supports it (see the build_case_mount_type lookup's supports_durometer flag).
	Durometer *string `json:"durometer,omitempty"`

	// Type Open vocabulary — validated against the "build_case_mount_type" lookup at request time.
	Type *string `json:"type,omitempty"`
}

// BuildImage defines model for BuildImage.
type BuildImage struct {
	// ImageId Server-generated identifier for this image, unique within the build.
	ImageId string `json:"image_id"`

	// Url A freshly-minted, short-lived presigned S3 GET URL. Generated new on every fetch of the build — do not cache or persist this value, it expires.
	Url string `json:"url"`
}

// BuildImageUpload defines model for BuildImageUpload.
type BuildImageUpload struct {
	// ImageId Server-generated identifier for the newly-created image.
	ImageId string `json:"image_id"`

	// UploadUrl Presigned S3 PUT URL. Short-lived — upload promptly.
	UploadUrl string `json:"upload_url"`
}

// BuildInput defines model for BuildInput.
type BuildInput struct {
	BuildDate     *openapi_types.Date `json:"build_date,omitempty"`
	CaseMountType *BuildCaseMountType `json:"case_mount_type,omitempty"`
	Foam          *bool               `json:"foam,omitempty"`

	// Keyboard ID of a Keyboard resource.
	Keyboard   string                 `json:"keyboard"`
	KeycapKits *[]BuildKeycapKitEntry `json:"keycap_kits,omitempty"`
	Notes      *string                `json:"notes,omitempty"`

	// Plate Which of the keyboard's design.plates options is installed.
	Plate    *string             `json:"plate,omitempty"`
	Stabs    *BuildStabs         `json:"stabs,omitempty"`
	Switches *[]BuildSwitchEntry `json:"switches,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// BuildKeycapKitEntry defines model for BuildKeycapKitEntry.
type BuildKeycapKitEntry struct {
	// KeycapSet ID of a KeycapSet resource.
	KeycapSet string `json:"keycap_set"`

	// Kit kit_id of one of that keycap set's kits (see KeycapKit.kit_id).
	Kit string `json:"kit"`
}

// BuildListPage defines model for BuildListPage.
type BuildListPage struct {
	Items      *[]BuildSummary `json:"items,omitempty"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// BuildStabs defines model for BuildStabs.
type BuildStabs struct {
	// MountType Open vocabulary — validated against the "build_stabilizer_mount_type" lookup at request time.
	MountType *string `json:"mount_type,omitempty"`

	// Name Open vocabulary — validated against the "build_stabilizer" lookup at request time.
	Name *string `json:"name,omitempty"`

	// Price A price in the collection's tracking currency.
	Price *Money `json:"price,omitempty"`
}

// BuildSummary Includes a denormalized keyboard brand/name so a build is recognizable in a list view without a follow-up request.
type BuildSummary struct {
	BuildDate *openapi_types.Date `json:"build_date,omitempty"`
	Id        *string             `json:"id,omitempty"`

	// Image First entry of images, if any (a freshly-minted presigned URL, same as on the full Build resource).
	Image *BuildImage `json:"image,omitempty"`

	// Keyboard A build's denormalized keyboard brand/name, for display in a list view.
	Keyboard *BuildSummaryKeyboard `json:"keyboard,omitempty"`
}

// BuildSummaryKeyboard A build's denormalized keyboard brand/name, for display in a list view.
type BuildSummaryKeyboard struct {
	Brand *string `json:"brand,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// BuildSwitchEntry defines model for BuildSwitchEntry.
type BuildSwitchEntry struct {
	Count int `json:"count"`

	// Switch ID of a Switch resource.
	Switch string `json:"switch"`
}

// CascadeDeleteResult Returned by a delete call made with on_delete=cascade, listing the ids of every build that was deleted alongside the requested item.
type CascadeDeleteResult struct {
	DeletedBuildIds []string `json:"deleted_build_ids"`
}

// Keyboard defines model for Keyboard.
type Keyboard struct {
	Brand  string          `json:"brand"`
	Design *KeyboardDesign `json:"design,omitempty"`
	Id     string          `json:"id"`

	// Layout Open vocabulary — validated against the "keyboard_layout" lookup at request time, including that the chosen layout is valid for the keyboard's size.
	Layout *string      `json:"layout,omitempty"`
	Name   string       `json:"name"`
	Notes  *string      `json:"notes,omitempty"`
	Pcb    *KeyboardPCB `json:"pcb,omitempty"`

	// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
	Purchase *Purchase `json:"purchase,omitempty"`

	// Size Open vocabulary — validated against the "keyboard_size" lookup at request time.
	Size *string `json:"size,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// KeyboardDesign defines model for KeyboardDesign.
type KeyboardDesign struct {
	// BottomCase A physical part described by material and color.
	BottomCase *MaterialColor `json:"bottom_case,omitempty"`
	Plates     *[]string      `json:"plates,omitempty"`

	// TopCase A physical part described by material and color.
	TopCase *MaterialColor `json:"top_case,omitempty"`

	// Weight A physical part described by material and color.
	Weight *MaterialColor `json:"weight,omitempty"`
}

// KeyboardInput defines model for KeyboardInput.
type KeyboardInput struct {
	Brand  string          `json:"brand"`
	Design *KeyboardDesign `json:"design,omitempty"`

	// Layout Open vocabulary — validated against the "keyboard_layout" lookup at request time, including that the chosen layout is valid for the keyboard's size.
	Layout *string      `json:"layout,omitempty"`
	Name   string       `json:"name"`
	Notes  *string      `json:"notes,omitempty"`
	Pcb    *KeyboardPCB `json:"pcb,omitempty"`

	// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
	Purchase *Purchase `json:"purchase,omitempty"`

	// Size Open vocabulary — validated against the "keyboard_size" lookup at request time.
	Size *string `json:"size,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// KeyboardListPage defines model for KeyboardListPage.
type KeyboardListPage struct {
	Items      *[]KeyboardSummary `json:"items,omitempty"`
	NextCursor *string            `json:"next_cursor,omitempty"`
}

// KeyboardPCB defines model for KeyboardPCB.
type KeyboardPCB struct {
	// Assembly Open vocabulary — validated against the "keyboard_pcb_assembly_type" lookup at request time.
	Assembly *string `json:"assembly,omitempty"`

	// Connectivity Open vocabulary — validated against the "keyboard_pcb_connectivity_type" lookup at request time.
	Connectivity *string `json:"connectivity,omitempty"`

	// Firmware Open vocabulary — validated against the "keyboard_pcb_firmware" lookup at request time.
	Firmware  *string  `json:"firmware,omitempty"`
	Thickness *float64 `json:"thickness,omitempty"`
}

// KeyboardSummary Reduced shape returned in list responses.
type KeyboardSummary struct {
	Brand       *string `json:"brand,omitempty"`
	Id          *string `json:"id,omitempty"`
	Layout      *string `json:"layout,omitempty"`
	Name        *string `json:"name,omitempty"`
	OrderStatus *string `json:"order_status,omitempty"`
	Size        *string `json:"size,omitempty"`
}

// KeycapKit defines model for KeycapKit.
type KeycapKit struct {
	// Image Managed via the dedicated image endpoint, not via PUT on the kit itself — see POST/DELETE .../keycap-sets/{keycapSetId}/kits/{kitId}/image.
	Image *KeycapKitImage `json:"image,omitempty"`

	// KitId Server-generated identifier for this kit, unique within the keycap set.
	KitId string `json:"kit_id"`

	// Name e.g. "Base", "Extension", "Accents".
	Name string `json:"name"`

	// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
	Purchase *Purchase `json:"purchase,omitempty"`
}

// KeycapKitImage defines model for KeycapKitImage.
type KeycapKitImage struct {
	// Url A freshly-minted, short-lived presigned S3 GET URL. Generated new on every fetch — do not cache or persist this value, it expires. A kit has at most one image (its vendor render/product shot) — see POST/DELETE .../kits/{kitId}/image.
	Url string `json:"url"`
}

// KeycapKitImageUpload defines model for KeycapKitImageUpload.
type KeycapKitImageUpload struct {
	// UploadUrl Presigned S3 PUT URL. Short-lived — upload promptly.
	UploadUrl string `json:"upload_url"`
}

// KeycapKitInput defines model for KeycapKitInput.
type KeycapKitInput struct {
	// Name e.g. "Base", "Extension", "Accents".
	Name string `json:"name"`

	// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
	Purchase *Purchase `json:"purchase,omitempty"`
}

// KeycapSet defines model for KeycapSet.
type KeycapSet struct {
	Brand string `json:"brand"`
	Id    string `json:"id"`

	// Kits Managed via the dedicated kit endpoints below, not via PUT on the set itself — see POST/PUT/DELETE .../keycap-sets/{keycapSetId}/kits[/{kitId}].
	Kits *[]KeycapKit `json:"kits,omitempty"`

	// Material Open vocabulary — validated against the "keycap_material" lookup at request time.
	Material *string `json:"material,omitempty"`
	Name     string  `json:"name"`
	Notes    *string `json:"notes,omitempty"`

	// Profile Open vocabulary — validated against the "keycap_profile" lookup at request time.
	Profile *string `json:"profile,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// KeycapSetInput defines model for KeycapSetInput.
type KeycapSetInput struct {
	Brand string `json:"brand"`

	// Material Open vocabulary — validated against the "keycap_material" lookup at request time.
	Material *string `json:"material,omitempty"`
	Name     string  `json:"name"`
	Notes    *string `json:"notes,omitempty"`

	// Profile Open vocabulary — validated against the "keycap_profile" lookup at request time.
	Profile *string `json:"profile,omitempty"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// KeycapSetListPage defines model for KeycapSetListPage.
type KeycapSetListPage struct {
	Items      *[]KeycapSetSummary `json:"items,omitempty"`
	NextCursor *string             `json:"next_cursor,omitempty"`
}

// KeycapSetSummary defines model for KeycapSetSummary.
type KeycapSetSummary struct {
	Brand   *string `json:"brand,omitempty"`
	Id      *string `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Profile *string `json:"profile,omitempty"`
}

// Lookup A lookup category's approved values. "values" is plain strings except for "keyboard_layout" and "build_case_mount_type", whose entries are objects - see the examples below.
type Lookup struct {
	Category string `json:"category"`

	// Values Examples: ["Amazon","CannonKeys"], [{"name":"WK","sizes":["60%","65%"]}], [{"name":"Gasket Mount","supports_durometer":true}]
	Values []interface{} `json:"values"`
}

// MaterialColor A physical part described by material and color.
type MaterialColor struct {
	// Color Free text.
	Color *string `json:"color,omitempty"`

	// Material Open vocabulary — validated against the relevant *_material lookup at request time.
	Material *string `json:"material,omitempty"`
}

// Money A price in the collection's tracking currency.
type Money = float64

// Problem RFC 9457 Problem Details.
type Problem struct {
	// BlockingBuildIds Present on a 409 response caused by the item still being referenced by one or more builds. Lists the ids of the blocking builds.
	BlockingBuildIds *[]string `json:"blocking_build_ids,omitempty"`
	Detail           *string   `json:"detail,omitempty"`
	Instance         *string   `json:"instance,omitempty"`
	InvalidParams    *[]struct {
		AllowedValues *[]string `json:"allowed_values,omitempty"`
		Name          *string   `json:"name,omitempty"`
		Reason        *string   `json:"reason,omitempty"`
	} `json:"invalid_params,omitempty"`
	Status int    `json:"status"`
	Title  string `json:"title"`
	Type   string `json:"type"`
}

// Purchase Full purchase-lifecycle tracking, used by keyboards and keycap set kits (which get separate order/delivery dates and status).
type Purchase struct {
	DeliveryDate *openapi_types.Date `json:"delivery_date,omitempty"`
	OrderDate    *openapi_types.Date `json:"order_date,omitempty"`

	// OrderStatus Open vocabulary — validated against the "order_status" lookup at request time.
	OrderStatus *string `json:"order_status,omitempty"`

	// Price A price in the collection's tracking currency.
	Price *Money `json:"price,omitempty"`

	// Vendor Open vocabulary — validated against the "vendor" lookup at request time.
	Vendor *string `json:"vendor,omitempty"`
}

// Switch defines model for Switch.
type Switch struct {
	Brand        string          `json:"brand"`
	FactoryLubed *bool           `json:"factory_lubed,omitempty"`
	Force        *SwitchForce    `json:"force,omitempty"`
	Id           string          `json:"id"`
	Manufacturer *string         `json:"manufacturer,omitempty"`
	Material     *SwitchMaterial `json:"material,omitempty"`
	Name         string          `json:"name"`
	Notes        *string         `json:"notes,omitempty"`

	// Pins PCB mount pin count.
	Pins *int `json:"pins,omitempty"`

	// Purchase Same purchase-lifecycle tracking as Purchase, plus a quantity field since switches are bought in bulk.
	Purchase *SwitchPurchase `json:"purchase,omitempty"`
	Spring   *SwitchSpring   `json:"spring,omitempty"`

	// Type Open vocabulary — validated against the "switch_type" lookup at request time.
	Type string `json:"type"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// SwitchForce defines model for SwitchForce.
type SwitchForce struct {
	// Actuation Actuation force in grams (nominal value).
	Actuation *float64 `json:"actuation,omitempty"`

	// BottomOut Bottom-out force in grams (nominal value).
	BottomOut *float64 `json:"bottom_out,omitempty"`
}

// SwitchInput defines model for SwitchInput.
type SwitchInput struct {
	Brand        string          `json:"brand"`
	FactoryLubed *bool           `json:"factory_lubed,omitempty"`
	Force        *SwitchForce    `json:"force,omitempty"`
	Manufacturer *string         `json:"manufacturer,omitempty"`
	Material     *SwitchMaterial `json:"material,omitempty"`
	Name         string          `json:"name"`
	Notes        *string         `json:"notes,omitempty"`

	// Pins PCB mount pin count.
	Pins *int `json:"pins,omitempty"`

	// Purchase Same purchase-lifecycle tracking as Purchase, plus a quantity field since switches are bought in bulk.
	Purchase *SwitchPurchase `json:"purchase,omitempty"`
	Spring   *SwitchSpring   `json:"spring,omitempty"`

	// Type Open vocabulary — validated against the "switch_type" lookup at request time.
	Type string `json:"type"`

	// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
	Visibility Visibility `json:"visibility"`
}

// SwitchListPage defines model for SwitchListPage.
type SwitchListPage struct {
	Items      *[]SwitchSummary `json:"items,omitempty"`
	NextCursor *string          `json:"next_cursor,omitempty"`
}

// SwitchMaterial defines model for SwitchMaterial.
type SwitchMaterial struct {
	// BottomHousing Open vocabulary — validated against the "switch_material" lookup at request time.
	BottomHousing *string `json:"bottom_housing,omitempty"`

	// Stem Open vocabulary — validated against the "switch_material" lookup at request time.
	Stem *string `json:"stem,omitempty"`

	// TopHousing Open vocabulary — validated against the "switch_material" lookup at request time.
	TopHousing *string `json:"top_housing,omitempty"`
}

// SwitchPurchase Same purchase-lifecycle tracking as Purchase, plus a quantity field since switches are bought in bulk.
type SwitchPurchase struct {
	DeliveryDate *openapi_types.Date `json:"delivery_date,omitempty"`
	OrderDate    *openapi_types.Date `json:"order_date,omitempty"`

	// OrderStatus Open vocabulary — validated against the "order_status" lookup at request time.
	OrderStatus *string `json:"order_status,omitempty"`

	// Price A price in the collection's tracking currency.
	Price    *Money `json:"price,omitempty"`
	Quantity *int   `json:"quantity,omitempty"`

	// Vendor Open vocabulary — validated against the "vendor" lookup at request time.
	Vendor *string `json:"vendor,omitempty"`
}

// SwitchSpring defines model for SwitchSpring.
type SwitchSpring struct {
	// Material Open vocabulary — validated against the "switch_spring_material" lookup at request time.
	Material *string `json:"material,omitempty"`

	// PreTravel Pre-travel distance in mm.
	PreTravel *float64 `json:"pre_travel,omitempty"`

	// TotalTravel Total travel distance in mm.
	TotalTravel *float64 `json:"total_travel,omitempty"`
}

// SwitchSummary defines model for SwitchSummary.
type SwitchSummary struct {
	Brand *string `json:"brand,omitempty"`
	Id    *string `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`

	// Type Open vocabulary — validated against the "switch_type" lookup at request time.
	Type *string `json:"type,omitempty"`
}

// Visibility Who can read this item via its GET routes (create/update/delete always require the caller to be the item's owner, regardless of visibility). "public": readable with no authentication at all. "authenticated": readable by any signed-in user, but not anonymous callers. "private": readable only by the owner. There is no per-user allowlist/sharing mechanism beyond these three tiers — visibility is not scoped to specific other users.
type Visibility string

// BuildId defines model for BuildId.
type BuildId = string

// Cursor defines model for Cursor.
type Cursor = string

// KeyboardId defines model for KeyboardId.
type KeyboardId = string

// KeycapSetId defines model for KeycapSetId.
type KeycapSetId = string

// Limit defines model for Limit.
type Limit = int

// SwitchId defines model for SwitchId.
type SwitchId = string

// UserId defines model for UserId.
type UserId = openapi_types.UUID

// ConflictResponse RFC 9457 Problem Details.
type ConflictResponse = Problem

// NotFoundResponse RFC 9457 Problem Details.
type NotFoundResponse = Problem

// ProblemResponse RFC 9457 Problem Details.
type ProblemResponse = Problem

// ListBuildsParams defines parameters for ListBuilds.
type ListBuildsParams struct {
	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateBuildImageJSONBody defines parameters for CreateBuildImage.
type CreateBuildImageJSONBody struct {
	// ContentType Open vocabulary — validated against the "image_content_type" lookup at request time.
	ContentType string `json:"content_type"`
}

// ListKeyboardsParams defines parameters for ListKeyboards.
type ListKeyboardsParams struct {
	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// DeleteKeyboardParams defines parameters for DeleteKeyboard.
type DeleteKeyboardParams struct {
	// OnDelete How to handle a keyboard still referenced by one or more builds.
	OnDelete *DeleteKeyboardParamsOnDelete `form:"on_delete,omitempty" json:"on_delete,omitempty"`
}

// DeleteKeyboardParamsOnDelete defines parameters for DeleteKeyboard.
type DeleteKeyboardParamsOnDelete string

// ListKeycapSetsParams defines parameters for ListKeycapSets.
type ListKeycapSetsParams struct {
	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// DeleteKeycapSetParams defines parameters for DeleteKeycapSet.
type DeleteKeycapSetParams struct {
	// OnDelete How to handle a set still referenced by one or more builds.
	OnDelete *DeleteKeycapSetParamsOnDelete `form:"on_delete,omitempty" json:"on_delete,omitempty"`
}

// DeleteKeycapSetParamsOnDelete defines parameters for DeleteKeycapSet.
type DeleteKeycapSetParamsOnDelete string

// DeleteKeycapKitParams defines parameters for DeleteKeycapKit.
type DeleteKeycapKitParams struct {
	// OnDelete How to handle a kit still referenced by one or more builds.
	OnDelete *DeleteKeycapKitParamsOnDelete `form:"on_delete,omitempty" json:"on_delete,omitempty"`
}

// DeleteKeycapKitParamsOnDelete defines parameters for DeleteKeycapKit.
type DeleteKeycapKitParamsOnDelete string

// SetKeycapKitImageJSONBody defines parameters for SetKeycapKitImage.
type SetKeycapKitImageJSONBody struct {
	// ContentType Open vocabulary — validated against the "image_content_type" lookup at request time.
	ContentType string `json:"content_type"`
}

// ListSwitchesParams defines parameters for ListSwitches.
type ListSwitchesParams struct {
	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous response's next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// DeleteSwitchParams defines parameters for DeleteSwitch.
type DeleteSwitchParams struct {
	// OnDelete How to handle a switch still referenced by one or more builds.
	OnDelete *DeleteSwitchParamsOnDelete `form:"on_delete,omitempty" json:"on_delete,omitempty"`
}

// DeleteSwitchParamsOnDelete defines parameters for DeleteSwitch.
type DeleteSwitchParamsOnDelete string

// CreateBuildJSONRequestBody defines body for CreateBuild for application/json ContentType.
type CreateBuildJSONRequestBody = BuildInput

// UpdateBuildJSONRequestBody defines body for UpdateBuild for application/json ContentType.
type UpdateBuildJSONRequestBody = BuildInput

// CreateBuildImageJSONRequestBody defines body for CreateBuildImage for application/json ContentType.
type CreateBuildImageJSONRequestBody CreateBuildImageJSONBody

// CreateKeyboardJSONRequestBody defines body for CreateKeyboard for application/json ContentType.
type CreateKeyboardJSONRequestBody = KeyboardInput

// UpdateKeyboardJSONRequestBody defines body for UpdateKeyboard for application/json ContentType.
type UpdateKeyboardJSONRequestBody = KeyboardInput

// CreateKeycapSetJSONRequestBody defines body for CreateKeycapSet for application/json ContentType.
type CreateKeycapSetJSONRequestBody = KeycapSetInput

// UpdateKeycapSetJSONRequestBody defines body for UpdateKeycapSet for application/json ContentType.
type UpdateKeycapSetJSONRequestBody = KeycapSetInput

// CreateKeycapKitJSONRequestBody defines body for CreateKeycapKit for application/json ContentType.
type CreateKeycapKitJSONRequestBody = KeycapKitInput

// UpdateKeycapKitJSONRequestBody defines body for UpdateKeycapKit for application/json ContentType.
type UpdateKeycapKitJSONRequestBody = KeycapKitInput

// SetKeycapKitImageJSONRequestBody defines body for SetKeycapKitImage for application/json ContentType.
type SetKeycapKitImageJSONRequestBody SetKeycapKitImageJSONBody

// CreateSwitchJSONRequestBody defines body for CreateSwitch for application/json ContentType.
type CreateSwitchJSONRequestBody = SwitchInput

// UpdateSwitchJSONRequestBody defines body for UpdateSwitch for application/json ContentType.
type UpdateSwitchJSONRequestBody = SwitchInput

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3rctu4kvCroPh9p2Lv0pLnJHO2xqn9kTiZOT7JnHHFzswP2+WCyJaEYxDgAKAVTcpV+xD7hPskW2gA",
	"vEikbpZ8mc2vxDYJNLobfe/m1yiRWS4FCKOjo69RThXNwIDCn94WjKcnqf1vCjpRLDdMiugoOgN1C+pg",
	"BAIUNZASloIwbMhAkaFUxIyBDOzLvSiOmH0jp2YcxZGgGURH0cAvHEcKfi+YgjQ6MqqAONLJGDJqdzTT",
	"3D6qjWJiFN3dxdFxobRU89D8ktPfCyA5HTFB7e9Igk+SoZIZoSRXcMtkoYkCnUuh4YUmAr6Ya/dYCePv",
	"BahpBaT7a7QYpg8wHUiqNsbSjX+/A1E31fLr4eoDTBOan4G5B2AJzYkG0w1aucN6sH1kGTPzUP1Mv7Cs",
	"yIgosgEoIoeEGcg0MZIoMIUSXYTiuF59zxSGtOAmOvrrYRxlbt3o6LtD+xMT/qc4gMaEgREohO1swkwy",
	"3hRpGt/uQJgOS6+Hrc8aVBs8x3IkmJFEF4N/QWLI3ufPJ+/2LdosJBZ1LzSREwGqR07sL5kmGTXJGDQ+",
	"QQsztgdI8DAJ5RyUeyMsGeNzFlbQhjBN6IgyoY39NVP4ZCI5h8RChJswQ+xhNaEkZcMhKBCGFBrUgqWo",
	"e+KFri12RBTQVHu6Eyn4NDBDeJ6MqSbwJecsYYZPiR5TBSmZMDPGvdyByJ5UMZKHEp1DwoYswZViv+jQ",
	"rWh/ZcHqWOV//uu/iTRjUBOmgVDy6vBVTIQ0+N+XsWVReitZShTcAuVMjNyyVLiV4QvTRpNBYc8uXhi/",
	"z/5rMlHMgCZ7iQJqoF/kqf0nBQ4G9gnlEzrVZEgZdzDh1oQJR86EaoiJZiKxQHlYEyqIgFtQJJMpG04J",
	"FQh6wDLisUf+idCfnpz0NSSFYmZKEikSUMKeBr7kUoPdiJLPnz4iAmYYThOqgEgney3vaYeSFBS7hdQJ",
	"X8gs6Bb9YuowGK7N1CKJGqPYoDDQuxTtl6Zw3L/oygylyqixzxbMPjl7he7sy07wo1Y7lmLIWWI++V/a",
	"3yVSGBAolGhueQr1SD9XcsAh+/d/aXvlvtY2/f8KhtFR9P/6lf7su7/q/ql7y23dvLTnDclqEYOqkEyo",
	"duRikJLB1FJTiqRQeIHCtZmMGQdHeSkA32GCDDkbjU1MqLDsZxQDTSaggMCXMS20gbRHzugQvBxV08ZV",
	"pPqAaYv9uzj6pzQ/ykKkj4UYDxPYc2hZqARIKkEjV+ENii3Cyl8NgEt70WSLOLNs07Nn8ls+xpHeCAJK",
	"efmTUWPhykGRTz8ekx9eff8fZM+/TN6BoYxrlFN/Pz8/JW9OT/R+D8W/36g0xxBszn8ZRkcXi0Fz1pvI",
	"CxPdxV+jXMkclGHuErC0RdvEEcvoyD0wq5sFHUFKbhlFbKeQekzjGwREmksmrIwDLidOEtiHTz+fEykq",
	"g5Awo4EPUaBoAHL6y9l5/937j+/P35Ner9fHh3T/q7cQ7/oOoov+V/zPSXp35WWFFWPLqONQYF+0h/On",
	"pUrRaeTEQpApFxYhV+UjEiVcdHd1FzusH1MNP8tCmHN8YBabaaEkms1txikIcisTOig4VVM8+C3lLEXs",
	"1TQquXRm8XW52GVEuJQ3RU5oJQQMy6BHfrHKKwMqmBgNC04mY3BITsZSgyCZhZXY0xBd5LlUxgp+smdR",
	"XtLi2uqPa3z0Gh91u73Q5TsVLGTI6WjfoX6Oa4xHyn1PPgNP9/lbpPwc7TzlHPXnKIbcdM02svOYdlwf",
	"k0Iwq/2samai6fXMIalQfH6zN2SoQI/59CCzVmgaEz2WyhxwVKG5As1GAlJy9pL89P7cquIe+amETMDE",
	"Xi6r7KdkCCYZB/PP3TWL8VTiXUxoMgYrPnNQmiHembbkKCC2nAFfcqZAOwJXGlWxVlQ3Lk7ApDvi1UJC",
	"fM65pOl2yQEWD3x64EwoL5HaSYC7X7dS4rSOayu1ENdnNWpYbLoVSK5klhs+vSe6KnC6sYbyew5fXlJQ",
	"Aw0LCH/RcvCZi7WS2GyKvDt7TJrVlMZASg4UDYfgpc5j9eSd5UhKgptcanZLn4yJjyBGZozOWG41pLIv",
	"XV6etR3C2U3XN8yFKlZXAM4X/sDMe2HUdF4TxJGQxuF1btOcexw3z/XbmFWXLRz/hSYpMlEP39JE4uPa",
	"OhZW1ln7vF02aEMHq53lDJ+0r6A3CWuiwrm3nXi4ZZoNGGdmumy1X6snZzm85IbGep0cPkOdOVb3ZNdg",
	"FrKXi0Xci7/aghI3zFyz1O5iTW7p3cXKhH+hiWVIp1nLo/Tca/trQzGPynB2B18nFj8ybU7bNV1gjjW4",
	"pMgy2nFTqrhZdV8uAvxxJArOo6tudXwWOL0JZFM23deOsNeJcfYHqA2tieB+bhOU9fbPFUuWyumfpYDp",
	"Atsn0HH+3oiEF6mL04Cw2sOCmJaSjAwUFWnfIoFoSWiw3TVRkMiRYH/QAffhAW6tiVsGEzSDZGEIJUPJ",
	"uZwcFHk4qFOU99JhizyW+RP+yJQ2BKxIwUgiehExYUOMROzRGburZmp9/vQxJtqenOrgugwLzgmitBQw",
	"eLelgJUdMe+FlEfAm4IeRl19rno3g0JdTv0Pncr5jSMrqq3FTOBCaCnTOafTGbL35glr32slVrhVqxrv",
	"dXU1JzMSe7VReCwI6QZF2a073B6bK44Zke23iz14bQL7mOqEpvAOg3yfQGOkeha8Txj6DNEgFxDEEB/J",
	"aOpcDiLFtfvDfyZuyRjJ4sKPQFiq7RGde+BuMGqvCdV+wZRQLsVIsxTqUSFrRBvI2i6tf+/aXV6WNjVL",
	"h2fY4XLPr9WGrTr/rhb4KHMy68Q+Vg0HhMXfobxoscylMTJDV3ap+KYGFKP8WHKpSmOzidHN9U+4xte4",
	"6nXmN1tPDc2qfyPzzY42ATYamzVfu1vADl2OUZA9axp/aUnOVTjLE/8ujjidysJsiVJusU4KxYSh3i7T",
	"C7WAj3uVOJ+epXP5xReaaPYHdARwglxeE2kL3KZksCouT4/f4huFSsYrcNZpeM6KdvYHbAn1dqn1rsZW",
	"fCXHrp4AS/2lgLJtGfthvd3Y+3UCzwFKtYZswKfbknHJ4DosuYG1n0ghIDHs1lNzSxDVl90AqiFT2YQq",
	"2CJEYck1tcCYJTcCNFIOvtAs5xAdfdf7Wy32lcpiwGuGu8viL5bhnf7JJ0iLBFKixzQHnwW2RolwZmeZ",
	"zlvH9uzwHyoBvqq1GkdSpaCsa2eKdvEXBNMKdm4ZM1jLvnGvdBo47T7Rqkmc1uzNDTPLcjcuWnGgwej+",
	"11p5yF3/huGvmCkzOk4RreY/Vedd4ENhwGXDaP4NM22x/GYJzJJIjdu/02asH2BOGD5MamCDbAB5g3Qf",
	"U23lRCa1wTCYY5c9ZjS5BZFKRRSIFFQ/VzItEmMhNfvdfNLBDWvF0bui5k1cd+UbnkImYEn4f+aWzx2h",
	"PUIFvVGPXEZvqYbLKCaX0fsvBoRmUrgf3ySJvVuX0QYB0vVNtJkTI8jdZz2DtYWglS/rZbhD+mBV0Wj5",
	"f5XstoZ2+Xj6eQ0ZeRGuxTpJ7kqDbJzjnkHm1ryq4HTe24JJaL6hB7t910bJIeOwlSP5tZ6D4+H4Y4ue",
	"h1twZ65Hc/lujl7VTuw0Bmv8sIK59xHp3KbtPQdYqTOSavpCE5rnSlp9g4pZW7nu/ncZWUc/55QJ4jbT",
	"BL4kkBu0adoiClSk3WUWMZmMpQYMlzPwhX2+yO+AhJoRb/h7IdgWHAywN9yEyJkIrZyMp6k9raOji4vo",
	"TUb/kHb1YyqEFB9gqqOr+CKovOi3D5Ezse3j0d8O/xLF0d++/0t0dVd/6ieqb8AQTGHb5+dKWlwl4d3V",
	"VSVnlwnQ8oAl7G23pRnFaiF1Pp5qllBOcqoMcX8duFBvEHJIsMQuMO/jJO3r/qgsoeCL6e1KFCvgcEuF",
	"If9WCuP7Vei4BFYbhhRLgHg7vKoLfqGJUTS5YWJEXHVkMrVbVT7pX1/2Xn2/gltaVga2OJ+hPm+mPK/F",
	"2eQSYWlGw+etSRDWbsbi3R9K55UktNCO6KFgm2jDOCcDsOdTgPXTiXsEs8+KZFL54h7dIx+xqLgW6cfK",
	"Hw9TeKppRywN8KZ41nbBKLShIoGOPyLLXGMDSVMPzAR+OJcTSK+ru786cJ0yWAH1VZsrMN3sqnN+fC15",
	"ZJhxor0SZ7+6q8GkIO+VahdsIZFdvTU2JtdH/X42vQEY6B4TQ9nH8lDdvy1XPAC/4lqOBP41wFqep00y",
	"ndYs+BnhUXBOgoF/wNkQkmnCobxuMQnMGnSLRhFVK2Z2dRATrIwZgSEaLDMYy7fWN0zBOk9qSlKsjbEv",
	"O0j3O/JM+PTq+WEXlFnz8Yr2m9ty9ZV2l+SPgx69F6xujfsWVp6VKdXVfDXfVLOLdJxb+kepkhablCam",
	"oA5Lcyom/MlaTE7VjKzkIntCZkxQ7owuzPKvoEx81q81FfQW/3YgC7ONvbrpsWXfbUgTI9X0mhcDSNvr",
	"/oYB7cuJ7yiEdogo7NKFAtUqy+uGyvJ1g621G1ePiTaNfvzW11fnTBBM8zdskO/bqhBWjZ24UzWSXDmC",
	"s9J7Z/n2SrJdIcMGaYtd+KdexS1xUx0StuWjepTuxEGdYd6uKoKxLLQn/r0JuVn4RJs2E/nBtjcyf3Qk",
	"dNOv25w6oxksMqcI1SS8HZOcF5pQ8ntBhWFmSoYMeOr7+kKdLzrlA1mMxsYqkEHBb77ZTSvZTQGt7Rb+",
	"U7OqzkpxP1Mhu5VQqr8GTqdseCdzBddG0Vtoz50cuL+RlDl30XJrlq1oRxlpKO9c/dz+lWy+/gKs7z5O",
	"+Ggaue3UvzZ09Gxvg8QmYgU09d1OBjLMd1gP76f350TJorNrOTQte21eb6M2kgxgrj09JgpGVKUcNEYx",
	"KiW/3yOXUV4MOEsuI9cTjnXHWPwoZL3n01ry1BDKuX2n0QzaeHUwxQJgl+A7YMJ3pw8K4/q5hRTTTBba",
	"g4xB11yxW2qgsQ52j/vQjW+yPx+DAsK0hSwHdYBd6hju4Eybvh5TSw+SQTKmgumMDGAqhUUxaIsVDN8x",
	"UNoxQYkFt6QhOpE5pBaJZSd71djtAz0giszaIA5pUdzEBGoLPEvNfKqxSegEP7MiNDRLY9P3m8KgvzcA",
	"qkD9GC7aP347j+L2uQQHTOsCUvKP387Jnn1dKvaHo9NbXIRcFoeHLxMjb0Dgf50DhOIb/Qx8qmLnsTG5",
	"a7NlYihDIy9NTJlBbw2yRPN9uacnLvVf6mJMg0vriHniJJRXZdD1sQRl8CMuFXNci4Fo14ZdduD5eQWJ",
	"zAZMIOdnPfLJXR6rz4Urti1ECor0b7/rIyn7X13X+12/1+shvV3smgwkjgBozGqooMOt3ZSEGl+QMb2F",
	"BYMSsjJdaaF2G5OcmjEpZ8G4vqaAwbK0EL7QxBBV8NA2yFkCvsfax+B/Pjn3bYEVcUbMjItBL5FZX8lR",
	"ARoUCGam/ZtBOugPuBz0M8pE/+PJ8ft/nr2vReEi+wR5c3piPQFQ2pHzu95h7xAtkxwEzVl0FL3sfdc7",
	"jND1GyMXW9Q6eYk/jqCz4FqXCRg/ycJedJfwdVMvXNySHPiiCisNw9L9r+Hdu9mREwuyOq4QJgeFl+Mk",
	"jY4i68F89ODODC/46+Hhgh72+d710iu9qPIwM7ZwFDfLIOs/++qoq9VDyC198JzPJrccbrFB/5U7UJsl",
	"Vx68P9vFj3v4ES9rv1sTdNHRxVUc6aD8EfFWZLfDa2URHWHSKTATenc17qqxwFJGw0kew2oPNxmkbDMD",
	"z4Cq1ghQ57Y2xvkJPN/cl20WGdZ+h6VDHGZw6Kn9ajnF5uZQ7IrcP4HD99LUayvl48a0rIvWlGfLRJNa",
	"DnH1MUBXns1m9INTMp2cdjIMAp3pmh02O+WHYx7Jsr1nvPKxkGn6Jcy+CQ+j+VOf3ePV3QoDeXKpNRvw",
	"KYEstyZeh/x76442h+Q26leP9N1sqbt46YN+mNjd1Q5vSrMzs000kpyO8L57TD8FifjVYq9h911c3c2L",
	"yUEgULgZ/hctF2MJKfyEK7tHLnULH3smzgq7LXRy8muC/og16ZiYHXtUt5OCg1LK4TYmPEbfxs1ccVcV",
	"tHkr0+l22cNnRZrxTyxMmGPM77a7c5cED3MU/CiLR+PIkt0cJUIXahvHLZKO1SyZqn/tHiyGC6DX0OQv",
	"11+3Gmu5zr+KtRpUfjUPnHs+fUwNWhLjnXfyu4kRLzZ7aqOAcGCcG+Okwxwnh3Wc9IR/90ECrEH2KoWZ",
	"Wa3SI3Wjas9a668OX+678W5hu9lZUt6ttsuXVRhhd3SlvNvdPRIOgyM4+E23TH4rRAlvOQKuw2jrYIXD",
	"h7nwlclWv/KPbKgt10LWelvIhptpoeWmQxiLigqruI++wsDZPYXJZwy+PSU99UBs66KOW2HaV4c/LH9x",
	"bm7g9oSqo+H9NVy/mt/2IMx/P2uNpqnjfd9QYuTK94Bgd4cPolkhDcZgXBar8n3dfevgORzUUnH0fiXI",
	"vY+Ers2EThEcY2gytj5ij7wL6sN3fmAYG+F2Kx/5Eklf3Wc1Q7NLx7eSOIRwhqNRcSk/jzUxBeV+ycHU",
	"AKrElClIDJ9ieLk5pSJE2HUtGudvnRvnNmK3IAhGpT0mPOjlkTn4AsI3pydEAc6RdZrLRRwhba5Y5GSo",
	"pDAxGcBQKsD+IsK0LnwctTlFw2pR3OLsZX31gD9qUCeLF8YNpiWTMJ2g1EhLDHPXT7W51Jutq62Oer9M",
	"jRvyVV9vzYRNo+i4DtZ82cMjeA711qr2wZeOizWXrnlsACAwFYJpiNfzV6jk96opiuzhKMzTz+dxmH17",
	"7E5wcG55cQw0BeU4J0y8aGF/X0PsUb5v97DHQiOWGT/5dFMH57GN8Tdp2hSfW1Ig1bTNrfhMCjJ52xD1",
	"bjL7VjyoSgY8Jzfqk0UJzCLkUa3Z+GuLkRXGFVZh6HLUqAPcimuaptA1wd4z0jainWXybXcBz3KLVWKe",
	"VSX09sKeH8ozPuvI59ykioXBzwrrzyj+eVOjVLiu1e/+XFHQD9VIx104mDMDmx7WoqlNUlsYDq2+1PGE",
	"IqK1WZttPLhEjmIHsv++yG6jo2UxRZsvV44xQ/tNSa6dJzCmeQ5ChyheuQbTvlGq2SLltecRuXSNWZcR",
	"2XO93IjzffyMgnaS+dXhD847KVuomn1ThKX6NbmM/Fy1y8gPTNNNSOwSc+PVSqg0YSb2R/UWKlNh5RSs",
	"a9m1cFURFRMO9LbeEFY1dwW7OKVihKHH8n2sIO02nGr3eUZINen+dzmxZuWYipTX2a0V/y0tah0fbCkJ",
	"3v7RFke+WjVT+NlTI4o99tqqmHap1doG97VIDW9nYizCg/y6zmm1yiD8UAPlWoaBfChdFlmvZA+xUdbA",
	"Vdzmvo6AiNnfSjjsoT6U8NYeaJ6HWvh9r5p4iFiISf2C93aR5lgiYVdIdlRy66HyHeWOTzjl0TApdmyF",
	"Lk98zCj3Z5L7WMqbu/IZa189210SZJHN0JkHeXqW6sOxc0iIPAVmnk9tbGqqhnE5O3X6Q/3uim5/eHy7",
	"jr8bWfL8Pf+ZUTHLXP8S98/L+Q9gN/m55NY/XQDAD+jamVxtTPN68BCAP93yGEA5EfBpRQE8WJ3MuFS8",
	"NqeR7ToYEGZGbBgOoGLqBlLWZq89dlAAj7MkHlCDe93QgMaPm2waFQgfzrm4ct9EWBgaKG/6WrEBC+C3",
	"sMC3sMBTCwt4txXKcU4DmU5dVnpufNO+zwfvIIiwTECvFkgIcvMhQwlhz6cdTKiZJ7u2bFcKJzTthOcT",
	"UFjOpzsMKpQfFN9pVGGB8bEorvDkDOAHZO1aaGErjP1kCi63bzr3w4ThB7sn26nCRMN0vgRz7ftSdxg/",
	"sN3el2oG/mM4jDhyeYnDyO7nKT7bC4aVaSVL7eqahXHZW3ZXEe62ErXqGGhl+aKt2hVpFLV6Owm79t2l",
	"8bXLKWS5tFzoZvI39j1J0WrK/djQpofrRlS4z4qvnjdnT8A7tkBsPVvOtuoSkzd4xoQK53plQBvId2NZ",
	"y6/0Vx/o51OyVwgFHK+8kRVhXHV56r7JVjDtLGAzkRb5kzEgb7X6JrTFO1khq1/K3PXS+uyb6/7Ndd+i",
	"6/6eIWcPHsGDR5ytemuFbFnitRVCarqzWAB7dOeqtdLXf+l4vs7XSocJ1cGm6ajzRdW1XpXv9lw8hFGK",
	"rfp6T8t2PXw427X09difxsljuzE7+7UPbW2tRcJC+0L76vot8PSMbfDA7RKPzQOhz6KO1W/iN4jf+0UO",
	"NBhzf5Zd+I0xq/nt5s4hYNr12REFOafBZRCSCHCGt3eHhkxp861j88l0bJ6FCH1D/nxr2XzgYNW3ts3n",
	"HlU7A0P28HOLKP/2V9Rr7TZOGGC5u8K6sMMqVXXlnOvtldSdhQM+64K6maH2C6vpSoQ/o1I6XVEpcG/5",
	"qz9XEZ3/bMpunMrGN1YeVsH4cy1JhTiiPqm6OR0I0sJ4i2Vm/6v7365L5dwu9+ma8ys8fnmcP8mWcwB+",
	"2Q3TAIGcF1e9gKcF8fXy/q5XF+cW/hZf/xZf/7/RMbdIqq5Q5RYu4kNVuPn9nnB1W81u2KmNubyuraHD",
	"n0lN22J23FXAz5tju6xk67YNOjMbT8sCfSj+DQmNx+fe+dTEQhN0huFbuR3UbWDe5ncWaM56zQ9hXJW7",
	"zPJiOXUGnZ15Nwclbruo69Vi0GU733yIO/ji99qgxM38+h9qTXl7/hsc1nQUKbtlaUE5fp50/77nK4Mq",
	"8xC4geX+Wx8+LO4RUv9YSO2jqRaiuAOilQDy06HmYXnTGF/vLamhVMTahwec3YCrJdFkz42q13H55Wkd",
	"E/9Jcx0TMEnPFbEIKQ40CM0MuwUy4nJAa+YsSamhcVNjUjHFc1n9S9Pqg0BdH+55bQ9pjTv3zEQxA/5L",
	"Q7Uzh/n7d1d3/xsAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
