package dynamo

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	kbdbctx "github.com/rogueserenity/kbdb/internal/ctx"
	"github.com/rogueserenity/kbdb/internal/log"
	"github.com/rogueserenity/kbdb/internal/repository"
)

// errEmptyImageID guards AddImage against persisting an image with no
// ImageID - ImageID is meant to be server-generated by the handler
// (uuid.NewString()) before reaching this layer, so an empty value here
// means a caller skipped that step, not a legitimate request.
var errEmptyImageID = errors.New("image id must not be empty")

// errDuplicateImageID guards AddImage against an ImageID collision within
// one build's Images - practically unreachable given uuid.NewString(), but
// caught here rather than silently persisting an ambiguous duplicate.
var errDuplicateImageID = errors.New("image id already exists in this build")

// BuildRepository is the DynamoDB-backed repository.BuildRepository.
type BuildRepository struct {
	client    dynamoAPI
	tableName string
}

var _ repository.BuildRepository = (*BuildRepository)(nil)

// NewBuildRepository returns a BuildRepository backed by client.
func NewBuildRepository(client *dynamodb.Client, tableName string) *BuildRepository {
	return &BuildRepository{client: client, tableName: tableName}
}

// List implements repository.BuildRepository.
func (r *BuildRepository) List(
	ctx context.Context,
	ownerID string,
	visibilities []repository.Visibility,
	limit int,
	cursor string,
) ([]repository.Build, string, error) {
	// No visibility tier is readable, so nothing can match - short-circuit
	// rather than build a Query with an empty IN(...) filter (which the
	// expression builder below would panic constructing).
	if len(visibilities) == 0 {
		return []repository.Build{}, "", nil
	}

	startKey, _, _, err := decodeCursor(cursor)
	if err != nil {
		return nil, "", fmt.Errorf("decoding cursor: %w", err)
	}

	visValues := make([]expression.OperandBuilder, len(visibilities))
	for i, v := range visibilities {
		visValues[i] = expression.Value(v)
	}

	// BuildTable's user_id partition also holds refMarker items (see
	// build_ref.go), which sort after every real Build id (their sort key is
	// "z"-prefixed) so a fresh scan exhausts real builds before reaching any
	// marker. This filter is still needed as a backstop: a single
	// Limit-bounded page can straddle the build/marker boundary once a
	// user's builds are exhausted, and a marker item has no visibility
	// attribute to match anyway.
	builder := expression.NewBuilder().
		WithKeyCondition(expression.Key("user_id").Equal(expression.Value(ownerID))).
		WithFilter(expression.Name("visibility").In(visValues[0], visValues[1:]...).
			And(expression.AttributeNotExists(expression.Name("item_type"))))

	expr, err := builder.Build()
	if err != nil {
		return nil, "", fmt.Errorf("building build list expression: %w", err)
	}

	out, err := r.client.Query(ctx, &dynamodb.QueryInput{
		TableName:                 &r.tableName,
		KeyConditionExpression:    expr.KeyCondition(),
		FilterExpression:          expr.Filter(),
		ExpressionAttributeNames:  expr.Names(),
		ExpressionAttributeValues: expr.Values(),
		ExclusiveStartKey:         startKey,
		Limit:                     queryLimit(limit),
	})
	if err != nil {
		return nil, "", fmt.Errorf("querying builds for owner %q: %w", ownerID, err)
	}

	builds := []repository.Build{}
	if err := attributevalue.UnmarshalListOfMaps(out.Items, &builds); err != nil {
		return nil, "", fmt.Errorf("unmarshalling builds for owner %q: %w", ownerID, err)
	}

	nextCursor, err := encodeCursor(out.LastEvaluatedKey, "", "")
	if err != nil {
		return nil, "", fmt.Errorf("encoding next cursor: %w", err)
	}

	return builds, nextCursor, nil
}

// Get implements repository.BuildRepository.
func (r *BuildRepository) Get(ctx context.Context, ownerID, id string) (*repository.Build, error) {
	return r.get(ctx, ownerID, id, false)
}

// get is Get with an explicit consistency choice. Update uses the
// consistent read for the value it returns to the caller, since that read
// immediately follows its own committed write.
func (r *BuildRepository) get(ctx context.Context, ownerID, id string, consistent bool) (*repository.Build, error) {
	in := &dynamodb.GetItemInput{
		TableName: &r.tableName,
		Key:       buildKey(ownerID, id),
	}
	if consistent {
		in.ConsistentRead = aws.Bool(true)
	}
	out, err := r.client.GetItem(ctx, in)
	if err != nil {
		return nil, fmt.Errorf("getting build %q for owner %q: %w", id, ownerID, err)
	}

	if len(out.Item) == 0 {
		return nil, repository.ErrNotFound
	}

	var b repository.Build
	if err := attributevalue.UnmarshalMap(out.Item, &b); err != nil {
		return nil, fmt.Errorf("unmarshalling build %q for owner %q: %w", id, ownerID, err)
	}

	return &b, nil
}

// Create implements repository.BuildRepository.
func (r *BuildRepository) Create(ctx context.Context, b repository.Build) (*repository.Build, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("creating build %q: %w", b.ID, repository.ErrNoUserID)
	}
	b.UserID = ownerID

	item, err := attributevalue.MarshalMap(b)
	if err != nil {
		return nil, fmt.Errorf("marshalling build %q for owner %q: %w", b.ID, b.UserID, err)
	}
	// AddImage addresses images.<id> in place - DynamoDB won't auto-vivify
	// the parent Map, so seed an empty one.
	if _, ok := item["images"]; !ok {
		item["images"] = &types.AttributeValueMemberM{Value: map[string]types.AttributeValue{}}
	}

	transactItems := []types.TransactWriteItem{
		{
			Put: &types.Put{
				TableName:           &r.tableName,
				Item:                item,
				ConditionExpression: aws.String("attribute_not_exists(id)"),
			},
		},
	}
	for _, m := range deriveRefMarkers(ownerID, b) {
		transactItems = append(transactItems, putMarkerTransactItem(r.tableName, m))
	}

	_, err = r.client.TransactWriteItems(ctx, &dynamodb.TransactWriteItemsInput{TransactItems: transactItems})
	if err != nil {
		if isConditionalCheckFailed(err) {
			return nil, repository.ErrAlreadyExists
		}
		return nil, fmt.Errorf("creating build %q for owner %q: %w", b.ID, b.UserID, err)
	}

	return &b, nil
}

// isConditionalCheckFailed reports whether err is a TransactWriteItems
// failure caused by a ConditionExpression not being met - DynamoDB reports
// this as a TransactionCanceledException wrapping per-item cancellation
// reasons, not the ConditionalCheckFailedException a plain PutItem/DeleteItem
// would return.
func isConditionalCheckFailed(err error) bool {
	txErr, ok := errors.AsType[*types.TransactionCanceledException](err)
	if !ok {
		return false
	}
	for _, reason := range txErr.CancellationReasons {
		if reason.Code != nil && *reason.Code == "ConditionalCheckFailed" {
			return true
		}
	}
	return false
}

const maxBuildMutationAttempts = 3

// buildKey builds the base-table primary key for a build.
func buildKey(ownerID, buildID string) map[string]types.AttributeValue {
	return map[string]types.AttributeValue{
		"user_id": &types.AttributeValueMemberS{Value: ownerID},
		"id":      &types.AttributeValueMemberS{Value: buildID},
	}
}

// Update rewrites the caller's build from the request body and re-diffs its
// ref-markers, in one TransactWriteItems: an Update action on the build item
// (SET body fields + Switches/KeycapKits, images/next unnamed so they carry
// forward, cond attribute_exists(id)) plus a marker Put/Delete per
// reference delta. The pre-Get is for the old marker set, not carry-forward.
// A cancellation is classified: build-item ConditionalCheckFailed means the
// build is gone (ErrNotFound); TransactionConflict retries from a fresh Get.
func (r *BuildRepository) Update(ctx context.Context, b repository.Build) (*repository.Build, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("updating build %q: %w", b.ID, repository.ErrNoUserID)
	}

	update := expression.
		Set(expression.Name("keyboard"), expression.Value(b.Keyboard)).
		Set(expression.Name("switches"), expression.Value(b.Switches)).
		Set(expression.Name("keycap_kits"), expression.Value(b.KeycapKits)).
		Set(expression.Name("visibility"), expression.Value(b.Visibility))
	update = setOrRemovePtr(update, "plate", b.Plate)
	update = setOrRemovePtr(update, "case_mount_type", b.CaseMountType)
	update = setOrRemovePtr(update, "stabs", b.Stabs)
	update = setOrRemovePtr(update, "foam", b.Foam)
	update = setOrRemovePtr(update, "build_date", b.BuildDate)
	update = setOrRemovePtr(update, "notes", b.Notes)

	expr, err := expression.NewBuilder().
		WithUpdate(update).
		WithCondition(expression.AttributeExists(expression.Name("id"))).
		Build()
	if err != nil {
		return nil, fmt.Errorf("building build update expression for build %q: %w", b.ID, err)
	}

	// b carries the desired reference set; the current one comes from a Get
	// each attempt so a TransactionConflict retry re-diffs against fresh
	// state. b.ID is set from the request, b.UserID from ctx.
	b.UserID = ownerID
	newMarkers := deriveRefMarkers(ownerID, b)

	for range maxBuildMutationAttempts {
		existing, err := r.Get(ctx, ownerID, b.ID)
		if err != nil {
			return nil, err
		}
		toAdd, toRemove := diffRefMarkers(deriveRefMarkers(ownerID, *existing), newMarkers)

		transactItems := []types.TransactWriteItem{
			{Update: &types.Update{
				TableName:                 &r.tableName,
				Key:                       buildKey(ownerID, b.ID),
				UpdateExpression:          expr.Update(),
				ConditionExpression:       expr.Condition(),
				ExpressionAttributeNames:  expr.Names(),
				ExpressionAttributeValues: expr.Values(),
			}},
		}
		for _, m := range toAdd {
			transactItems = append(transactItems, putMarkerTransactItem(r.tableName, m))
		}
		for _, m := range toRemove {
			transactItems = append(transactItems, deleteMarkerTransactItem(r.tableName, m))
		}

		_, err = r.client.TransactWriteItems(ctx, &dynamodb.TransactWriteItemsInput{TransactItems: transactItems})
		if err == nil {
			// Consistent read: this immediately follows our own commit, and
			// the value is what the caller gets back as the persisted build.
			return r.get(ctx, ownerID, b.ID, true)
		}

		switch classifyBuildTxConflict(err) {
		case buildTxConflictGone:
			return nil, repository.ErrNotFound
		case buildTxConflictRetry:
			log.FromContext(ctx).Warn("build update retry", log.BuildID, b.ID)
			continue
		case buildTxConflictNone:
			return nil, fmt.Errorf("updating build %q for owner %q: %w", b.ID, ownerID, err)
		}
	}

	return nil, fmt.Errorf("updating build %q owner %q: %w", b.ID, ownerID, repository.ErrMutationConflict)
}

type buildTxConflict int

const (
	buildTxConflictNone buildTxConflict = iota
	buildTxConflictGone
	buildTxConflictRetry
)

// classifyBuildTxConflict maps a build TransactWriteItems cancellation:
// reason 0 (the build item) ConditionalCheckFailed means attribute_exists(id)
// failed - the build is gone; any TransactionConflict is transient
// contention. buildTxConflictNone if err isn't a transaction cancellation.
func classifyBuildTxConflict(err error) buildTxConflict {
	txErr, ok := errors.AsType[*types.TransactionCanceledException](err)
	if !ok {
		return buildTxConflictNone
	}
	for _, reason := range txErr.CancellationReasons {
		if reason.Code != nil && *reason.Code == "TransactionConflict" {
			return buildTxConflictRetry
		}
	}
	if len(txErr.CancellationReasons) > 0 && txErr.CancellationReasons[0].Code != nil &&
		*txErr.CancellationReasons[0].Code == "ConditionalCheckFailed" {
		return buildTxConflictGone
	}
	return buildTxConflictNone
}

// Delete implements repository.BuildRepository. It Gets the build first
// because a TransactWriteItems Delete has no ReturnValues equivalent and the
// deleted build's references must be known to also delete its refMarkers in
// the same transaction. The build-item Delete carries no version condition -
// deleting an already-gone row is idempotent. A concurrent Update between
// the Get and the transaction surfaces as a TransactionConflict, which
// retries from a fresh Get (re-deriving the current marker set).
func (r *BuildRepository) Delete(ctx context.Context, id string) error {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return fmt.Errorf("deleting build %q: %w", id, repository.ErrNoUserID)
	}

	for range maxBuildMutationAttempts {
		existing, err := r.Get(ctx, ownerID, id)
		if errors.Is(err, repository.ErrNotFound) {
			return nil
		}
		if err != nil {
			return err
		}

		transactItems := []types.TransactWriteItem{
			{Delete: &types.Delete{TableName: &r.tableName, Key: buildKey(ownerID, id)}},
		}
		for _, m := range deriveRefMarkers(ownerID, *existing) {
			transactItems = append(transactItems, deleteMarkerTransactItem(r.tableName, m))
		}

		_, err = r.client.TransactWriteItems(ctx, &dynamodb.TransactWriteItemsInput{TransactItems: transactItems})
		if err == nil {
			return nil
		}

		if classifyBuildTxConflict(err) == buildTxConflictRetry {
			log.FromContext(ctx).Warn("build delete retry", log.BuildID, id)
			continue
		}
		return fmt.Errorf("deleting build %q for owner %q: %w", id, ownerID, err)
	}

	return fmt.Errorf("deleting build %q owner %q: %w", id, ownerID, repository.ErrMutationConflict)
}

// AddImage implements repository.BuildRepository. One UpdateItem sets
// images.<id> = {path, seq}. Seq is time.Now().UnixNano(), so a new image
// sorts after every existing one without reading the current max (see
// BuildImageEntry.Seq for the wall-clock caveat). images is not part of any
// ref-marker, so this is a plain UpdateItem, no transaction. On the
// compound-condition failure a consistent GetItem (buildExists) tells
// build-gone (ErrNotFound) from duplicate-id.
func (r *BuildRepository) AddImage(ctx context.Context, buildID string, image repository.BuildImage) error {
	if image.ImageID == "" {
		return fmt.Errorf("adding image to build %q: %w", buildID, errEmptyImageID)
	}

	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return fmt.Errorf("adding image to build %q: %w", buildID, repository.ErrNoUserID)
	}

	imagePath := "images." + image.ImageID
	entry := repository.BuildImageEntry{Path: image.Path, Seq: int(time.Now().UnixNano())}
	update := expression.Set(expression.Name(imagePath), expression.Value(entry))
	cond := expression.AttributeExists(expression.Name("id")).
		And(expression.AttributeNotExists(expression.Name(imagePath)))

	expr, err := expression.NewBuilder().WithUpdate(update).WithCondition(cond).Build()
	if err != nil {
		return fmt.Errorf("building add-image expression for build %q: %w", buildID, err)
	}

	_, err = r.client.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 &r.tableName,
		Key:                       buildKey(ownerID, buildID),
		UpdateExpression:          expr.Update(),
		ConditionExpression:       expr.Condition(),
		ExpressionAttributeNames:  expr.Names(),
		ExpressionAttributeValues: expr.Values(),
	})
	if err != nil {
		if _, ok := errors.AsType[*types.ConditionalCheckFailedException](err); ok {
			exists, existsErr := r.buildExists(ctx, ownerID, buildID)
			if existsErr != nil {
				return fmt.Errorf("classifying add-image conflict for build %q: %w", buildID, existsErr)
			}
			if !exists {
				return repository.ErrNotFound
			}
			return fmt.Errorf("adding image %q to build %q: %w", image.ImageID, buildID, errDuplicateImageID)
		}
		return fmt.Errorf("adding image %q to build %q owner %q: %w", image.ImageID, buildID, ownerID, err)
	}

	return nil
}

// buildExists is a strongly consistent existence check for classifying a
// compound-condition failure.
func (r *BuildRepository) buildExists(ctx context.Context, ownerID, id string) (bool, error) {
	out, err := r.client.GetItem(ctx, &dynamodb.GetItemInput{
		TableName:      &r.tableName,
		Key:            buildKey(ownerID, id),
		ConsistentRead: aws.Bool(true),
	})
	if err != nil {
		return false, err
	}
	return len(out.Item) > 0, nil
}

// DeleteImage implements repository.BuildRepository. One UpdateItem REMOVE
// images.<id> under attribute_exists(images.<id>), ALL_OLD so the removed
// entry's path is the returned key. A missing id (condition fails but the
// build exists) is a nil-nil success. No transaction - images aren't
// ref-markers.
func (r *BuildRepository) DeleteImage(ctx context.Context, buildID, imageID string) (*repository.BuildImageKey, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("deleting image from build %q: %w", buildID, repository.ErrNoUserID)
	}

	imagePath := "images." + imageID
	expr, err := expression.NewBuilder().
		WithUpdate(expression.Remove(expression.Name(imagePath))).
		WithCondition(
			expression.AttributeExists(expression.Name("id")).
				And(expression.AttributeExists(expression.Name(imagePath))),
		).
		Build()
	if err != nil {
		return nil, fmt.Errorf("building delete-image expression for build %q: %w", buildID, err)
	}

	out, err := r.client.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 &r.tableName,
		Key:                       buildKey(ownerID, buildID),
		UpdateExpression:          expr.Update(),
		ConditionExpression:       expr.Condition(),
		ExpressionAttributeNames:  expr.Names(),
		ExpressionAttributeValues: expr.Values(),
		ReturnValues:              types.ReturnValueAllOld,
	})
	if err != nil {
		if _, ok := errors.AsType[*types.ConditionalCheckFailedException](err); ok {
			exists, existsErr := r.buildExists(ctx, ownerID, buildID)
			if existsErr != nil {
				return nil, fmt.Errorf("classifying delete-image conflict for build %q: %w", buildID, existsErr)
			}
			if !exists {
				return nil, repository.ErrNotFound
			}
			return nil, nil //nolint:nilnil // no such image already absent is a valid, expected result
		}
		return nil, fmt.Errorf("deleting image %q from build %q owner %q: %w", imageID, buildID, ownerID, err)
	}

	var old repository.Build
	if err := attributevalue.UnmarshalMap(out.Attributes, &old); err != nil {
		return nil, fmt.Errorf("unmarshalling pre-delete build %q for owner %q: %w", buildID, ownerID, err)
	}
	entry, ok := old.Images[imageID]
	if !ok {
		return nil, nil //nolint:nilnil // no such image already absent is a valid, expected result
	}
	return &entry.Path, nil
}
