package dynamo

import (
	"context"
	"errors"
	"fmt"
	"math"
	"slices"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	kbdbctx "github.com/rogueserenity/kbdb/internal/ctx"
	"github.com/rogueserenity/kbdb/internal/log"
	"github.com/rogueserenity/kbdb/internal/repository"
)

// errEmptyImageID guards AddImage against persisting an image with no
// ImageID - ImageID is meant to be server-generated by the handler
// (uuid.NewString()) before reaching this layer, so an empty value here
// means a caller skipped that step, not a legitimate request.
var errEmptyImageID = errors.New("image id must not be empty")

// errDuplicateImageID guards AddImage against an ImageID collision within
// one build's Images - practically unreachable given uuid.NewString(), but
// caught here rather than silently persisting an ambiguous duplicate.
var errDuplicateImageID = errors.New("image id already exists in this build")

// errImageMissingAfterAdd means AddImage's just-appended image isn't
// present by ImageID in the build mutateBuild returned - should be
// unreachable in practice.
var errImageMissingAfterAdd = errors.New("image not found in build after AddImage")

// errImageAlreadyAbsent signals DeleteImage's mutateBuild closure found no
// matching image - DeleteImage treats this as success, not an error.
var errImageAlreadyAbsent = errors.New("image already absent from build")

// BuildRepository is the DynamoDB-backed repository.BuildRepository.
type BuildRepository struct {
	client    dynamoAPI
	tableName string
}

var _ repository.BuildRepository = (*BuildRepository)(nil)

// NewBuildRepository returns a BuildRepository backed by client.
func NewBuildRepository(client *dynamodb.Client, tableName string) *BuildRepository {
	return &BuildRepository{client: client, tableName: tableName}
}

// List implements repository.BuildRepository.
func (r *BuildRepository) List(
	ctx context.Context,
	ownerID string,
	visibilities []repository.Visibility,
	limit int,
	cursor string,
) ([]repository.Build, string, error) {
	// No visibility tier is readable, so nothing can match - short-circuit
	// rather than build a Query with an empty IN(...) filter (which the
	// expression builder below would panic constructing).
	if len(visibilities) == 0 {
		return []repository.Build{}, "", nil
	}

	startKey, err := decodeCursor(cursor)
	if err != nil {
		return nil, "", fmt.Errorf("decoding cursor: %w", err)
	}

	// limit is validated by the handler against api/openapi.yaml's Limit
	// parameter (1-100) before reaching here; List's exported signature
	// accepts any int, so clamp defensively rather than trust that.
	if limit < 1 {
		limit = 1
	} else if limit > math.MaxInt32 {
		limit = math.MaxInt32
	}

	visValues := make([]expression.OperandBuilder, len(visibilities))
	for i, v := range visibilities {
		visValues[i] = expression.Value(v)
	}

	// BuildTable's user_id partition also holds refMarker items (see
	// build_ref.go), which sort after every real Build id (their sort key is
	// "z"-prefixed) so a fresh scan exhausts real builds before reaching any
	// marker. This filter is still needed as a backstop: a single
	// Limit-bounded page can straddle the build/marker boundary once a
	// user's builds are exhausted, and a marker item has no visibility
	// attribute to match anyway.
	builder := expression.NewBuilder().
		WithKeyCondition(expression.Key("user_id").Equal(expression.Value(ownerID))).
		WithFilter(expression.Name("visibility").In(visValues[0], visValues[1:]...).
			And(expression.AttributeNotExists(expression.Name("item_type"))))

	expr, err := builder.Build()
	if err != nil {
		return nil, "", fmt.Errorf("building build list expression: %w", err)
	}

	out, err := r.client.Query(ctx, &dynamodb.QueryInput{
		TableName:                 &r.tableName,
		KeyConditionExpression:    expr.KeyCondition(),
		FilterExpression:          expr.Filter(),
		ExpressionAttributeNames:  expr.Names(),
		ExpressionAttributeValues: expr.Values(),
		ExclusiveStartKey:         startKey,
		Limit:                     aws.Int32(int32(limit)),
	})
	if err != nil {
		return nil, "", fmt.Errorf("querying builds for owner %q: %w", ownerID, err)
	}

	builds := []repository.Build{}
	if err := attributevalue.UnmarshalListOfMaps(out.Items, &builds); err != nil {
		return nil, "", fmt.Errorf("unmarshalling builds for owner %q: %w", ownerID, err)
	}

	nextCursor, err := encodeCursor(out.LastEvaluatedKey)
	if err != nil {
		return nil, "", fmt.Errorf("encoding next cursor: %w", err)
	}

	return builds, nextCursor, nil
}

// Get implements repository.BuildRepository.
func (r *BuildRepository) Get(ctx context.Context, ownerID, id string) (*repository.Build, error) {
	out, err := r.client.GetItem(ctx, &dynamodb.GetItemInput{
		TableName: &r.tableName,
		Key: map[string]types.AttributeValue{
			"user_id": &types.AttributeValueMemberS{Value: ownerID},
			"id":      &types.AttributeValueMemberS{Value: id},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("getting build %q for owner %q: %w", id, ownerID, err)
	}

	if len(out.Item) == 0 {
		return nil, repository.ErrNotFound
	}

	var b repository.Build
	if err := attributevalue.UnmarshalMap(out.Item, &b); err != nil {
		return nil, fmt.Errorf("unmarshalling build %q for owner %q: %w", id, ownerID, err)
	}

	return &b, nil
}

// Create implements repository.BuildRepository.
func (r *BuildRepository) Create(ctx context.Context, b repository.Build) (*repository.Build, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("creating build %q: %w", b.ID, repository.ErrNoUserID)
	}
	b.UserID = ownerID

	item, err := attributevalue.MarshalMap(b)
	if err != nil {
		return nil, fmt.Errorf("marshalling build %q for owner %q: %w", b.ID, b.UserID, err)
	}

	transactItems := []types.TransactWriteItem{
		{
			Put: &types.Put{
				TableName:           &r.tableName,
				Item:                item,
				ConditionExpression: aws.String("attribute_not_exists(id)"),
			},
		},
	}
	for _, m := range deriveRefMarkers(ownerID, b) {
		transactItems = append(transactItems, putMarkerTransactItem(r.tableName, m))
	}

	_, err = r.client.TransactWriteItems(ctx, &dynamodb.TransactWriteItemsInput{TransactItems: transactItems})
	if err != nil {
		if isConditionalCheckFailed(err) {
			return nil, repository.ErrAlreadyExists
		}
		return nil, fmt.Errorf("creating build %q for owner %q: %w", b.ID, b.UserID, err)
	}

	return &b, nil
}

// isConditionalCheckFailed reports whether err is a TransactWriteItems
// failure caused by a ConditionExpression not being met - DynamoDB reports
// this as a TransactionCanceledException wrapping per-item cancellation
// reasons, not the ConditionalCheckFailedException a plain PutItem/DeleteItem
// would return.
func isConditionalCheckFailed(err error) bool {
	var txErr *types.TransactionCanceledException
	if !errors.As(err, &txErr) {
		return false
	}
	for _, reason := range txErr.CancellationReasons {
		if reason.Code != nil && *reason.Code == "ConditionalCheckFailed" {
			return true
		}
	}
	return false
}

// Update goes through mutateBuild rather than a naive whole-item PutItem:
// b (built from the request body) never has Images or Version set, so
// overwriting the stored item wholesale would wipe every image and desync
// Version from mutateBuild's CAS loop.
func (r *BuildRepository) Update(ctx context.Context, b repository.Build) (*repository.Build, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("updating build %q: %w", b.ID, repository.ErrNoUserID)
	}

	updated, err := r.mutateBuild(ctx, ownerID, b.ID, func(existing *repository.Build) error {
		existing.Keyboard = b.Keyboard
		existing.Plate = b.Plate
		existing.CaseMountType = b.CaseMountType
		existing.Stabs = b.Stabs
		existing.Foam = b.Foam
		existing.Switches = b.Switches
		existing.KeycapKits = b.KeycapKits
		existing.BuildDate = b.BuildDate
		existing.Notes = b.Notes
		existing.Visibility = b.Visibility
		return nil
	})
	if errors.Is(err, repository.ErrNotFound) {
		return nil, repository.ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("updating build %q for owner %q: %w", b.ID, ownerID, err)
	}

	return updated, nil
}

// Delete implements repository.BuildRepository. It Gets the build first
// (rather than a plain DeleteItem with ReturnValues: ALL_OLD) because a
// TransactWriteItems Delete has no ReturnValues equivalent, and the deleted
// build's Images/references must be known up front to also delete its
// refMarkers in the same transaction. The base item's delete is
// CAS-conditioned on the version this Get saw: without that, a concurrent
// Update landing between the Get and the transact-write could change the
// build's references out from under this call, leaving a refMarker
// orphaned - deleted for a reference that's no longer current, or never
// deleted for a reference the concurrent Update just added. On a lost race,
// retry from a fresh Get, mirroring mutateBuild's CAS loop.
func (r *BuildRepository) Delete(ctx context.Context, id string) error {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return fmt.Errorf("deleting build %q: %w", id, repository.ErrNoUserID)
	}

	for range maxBuildMutationAttempts {
		existing, err := r.Get(ctx, ownerID, id)
		if err != nil {
			return err
		}

		expr, err := expression.NewBuilder().
			WithCondition(expression.Name("version").Equal(expression.Value(existing.Version))).
			Build()
		if err != nil {
			return fmt.Errorf("building build delete condition for build %q: %w", id, err)
		}

		transactItems := []types.TransactWriteItem{
			{
				Delete: &types.Delete{
					TableName: &r.tableName,
					Key: map[string]types.AttributeValue{
						"user_id": &types.AttributeValueMemberS{Value: ownerID},
						"id":      &types.AttributeValueMemberS{Value: id},
					},
					ConditionExpression:       expr.Condition(),
					ExpressionAttributeNames:  expr.Names(),
					ExpressionAttributeValues: expr.Values(),
				},
			},
		}
		for _, m := range deriveRefMarkers(ownerID, *existing) {
			transactItems = append(transactItems, deleteMarkerTransactItem(r.tableName, m))
		}

		_, err = r.client.TransactWriteItems(ctx, &dynamodb.TransactWriteItemsInput{TransactItems: transactItems})
		if err == nil {
			return nil
		}

		if !isConditionalCheckFailed(err) {
			return fmt.Errorf("deleting build %q for owner %q: %w", id, ownerID, err)
		}
		// Lost the CAS race - another writer updated Version first. Loop
		// and retry from a fresh Get.
		log.FromContext(ctx).Warn("build delete CAS retry", log.BuildID, id, "attempted_version", existing.Version)
	}

	return fmt.Errorf("deleting build %q owner %q: %w", id, ownerID, repository.ErrMutationConflict)
}

const maxBuildMutationAttempts = 3

// mutateBuild is a hand-rolled Version-based CAS retry loop: DynamoDB can't
// address a List element by an inner field like image_id, so image
// mutations must decode/mutate/re-encode the whole Images slice, and the Go
// SDK has no built-in optimistic-locking primitive. Mirrors
// [(*KeycapSetRepository).mutateSet].
func (r *BuildRepository) mutateBuild(
	ctx context.Context,
	ownerID, buildID string,
	mutate func(b *repository.Build) error,
) (*repository.Build, error) {
	for range maxBuildMutationAttempts {
		b, err := r.Get(ctx, ownerID, buildID)
		if err != nil {
			return nil, err
		}
		oldMarkers := deriveRefMarkers(ownerID, *b)

		if err := mutate(b); err != nil {
			return nil, err
		}

		expectedVersion := b.Version
		b.Version++

		item, err := attributevalue.MarshalMap(*b)
		if err != nil {
			return nil, fmt.Errorf("marshalling build %q for owner %q: %w", buildID, ownerID, err)
		}

		expr, err := expression.NewBuilder().
			WithCondition(expression.Name("version").Equal(expression.Value(expectedVersion))).
			Build()
		if err != nil {
			return nil, fmt.Errorf("building build mutation condition for build %q: %w", buildID, err)
		}

		transactItems := []types.TransactWriteItem{
			{
				Put: &types.Put{
					TableName:                 &r.tableName,
					Item:                      item,
					ConditionExpression:       expr.Condition(),
					ExpressionAttributeNames:  expr.Names(),
					ExpressionAttributeValues: expr.Values(),
				},
			},
		}
		toAdd, toRemove := diffRefMarkers(oldMarkers, deriveRefMarkers(ownerID, *b))
		for _, m := range toAdd {
			transactItems = append(transactItems, putMarkerTransactItem(r.tableName, m))
		}
		for _, m := range toRemove {
			transactItems = append(transactItems, deleteMarkerTransactItem(r.tableName, m))
		}

		_, err = r.client.TransactWriteItems(ctx, &dynamodb.TransactWriteItemsInput{TransactItems: transactItems})
		if err == nil {
			return b, nil
		}

		if !isConditionalCheckFailed(err) {
			return nil, fmt.Errorf("mutating build %q owner %q: %w", buildID, ownerID, err)
		}
		// Lost the CAS race - another writer updated Version first. Loop
		// and retry from a fresh Get.
		log.FromContext(ctx).Warn("build CAS retry", log.BuildID, buildID, "attempted_version", expectedVersion)
	}

	return nil, fmt.Errorf("mutating build %q owner %q: %w", buildID, ownerID, repository.ErrMutationConflict)
}

// AddImage implements repository.BuildRepository.
func (r *BuildRepository) AddImage(ctx context.Context, buildID string, image repository.BuildImage) (*repository.BuildImage, error) {
	if image.ImageID == "" {
		return nil, fmt.Errorf("adding image to build %q: %w", buildID, errEmptyImageID)
	}

	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("adding image to build %q: %w", buildID, repository.ErrNoUserID)
	}

	updated, err := r.mutateBuild(ctx, ownerID, buildID, func(b *repository.Build) error {
		if slices.ContainsFunc(b.Images, func(existing repository.BuildImage) bool { return existing.ImageID == image.ImageID }) {
			return fmt.Errorf("adding image %q to build %q: %w", image.ImageID, buildID, errDuplicateImageID)
		}
		b.Images = append(b.Images, image)
		return nil
	})
	if err != nil {
		return nil, err
	}

	idx := slices.IndexFunc(updated.Images, func(i repository.BuildImage) bool { return i.ImageID == image.ImageID })
	if idx == -1 {
		return nil, fmt.Errorf("adding image %q to build %q: %w", image.ImageID, buildID, errImageMissingAfterAdd)
	}

	return &updated.Images[idx], nil
}

// DeleteImage implements repository.BuildRepository.
func (r *BuildRepository) DeleteImage(ctx context.Context, buildID, imageID string) (*repository.BuildImageKey, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("deleting image from build %q: %w", buildID, repository.ErrNoUserID)
	}

	var removed *repository.BuildImageKey
	_, err := r.mutateBuild(ctx, ownerID, buildID, func(b *repository.Build) error {
		idx := slices.IndexFunc(b.Images, func(existing repository.BuildImage) bool { return existing.ImageID == imageID })
		if idx == -1 {
			return errImageAlreadyAbsent
		}
		key := b.Images[idx].Path
		removed = &key
		b.Images = slices.Delete(b.Images, idx, idx+1)
		return nil
	})
	if errors.Is(err, errImageAlreadyAbsent) {
		return nil, nil //nolint:nilnil // no such image already absent is a valid, expected result
	}
	if err != nil {
		return nil, err
	}

	return removed, nil
}
