package dynamo

import (
	"context"
	"errors"
	"fmt"
	"slices"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	kbdbctx "github.com/rogueserenity/kbdb/internal/ctx"
	"github.com/rogueserenity/kbdb/internal/log"
	"github.com/rogueserenity/kbdb/internal/repository"
)

// errEmptyKeyboardImageID guards AddImage against persisting an image with
// no ImageID - ImageID is meant to be server-generated by the handler
// (uuid.NewString()) before reaching this layer, so an empty value here
// means a caller skipped that step, not a legitimate request.
var errEmptyKeyboardImageID = errors.New("image id must not be empty")

// errDuplicateKeyboardImageID guards AddImage against an ImageID collision
// within one keyboard's Images - practically unreachable given
// uuid.NewString(), but caught here rather than silently persisting an
// ambiguous duplicate.
var errDuplicateKeyboardImageID = errors.New("image id already exists for this keyboard")

// errKeyboardImageAlreadyAbsent signals DeleteImage's mutateKeyboard
// closure found no matching image - DeleteImage treats this as success,
// not an error.
var errKeyboardImageAlreadyAbsent = errors.New("image already absent from keyboard")

// KeyboardRepository is the DynamoDB-backed repository.KeyboardRepository.
type KeyboardRepository struct {
	client    dynamoAPI
	tableName string
}

var _ repository.KeyboardRepository = (*KeyboardRepository)(nil)

// NewKeyboardRepository returns a KeyboardRepository backed by client.
func NewKeyboardRepository(client *dynamodb.Client, tableName string) *KeyboardRepository {
	return &KeyboardRepository{client: client, tableName: tableName}
}

// List implements repository.KeyboardRepository.
func (r *KeyboardRepository) List(
	ctx context.Context,
	ownerID string,
	visibilities []repository.Visibility,
	limit int,
	cursor string,
) ([]repository.Keyboard, string, error) {
	// No visibility tier is readable, so nothing can match - short-circuit
	// rather than build a Query with an empty IN(...) filter (which the
	// expression builder below would panic constructing).
	if len(visibilities) == 0 {
		return []repository.Keyboard{}, "", nil
	}

	startKey, err := decodeCursor(cursor)
	if err != nil {
		return nil, "", fmt.Errorf("decoding cursor: %w", err)
	}

	visValues := make([]expression.OperandBuilder, len(visibilities))
	for i, v := range visibilities {
		visValues[i] = expression.Value(v)
	}

	builder := expression.NewBuilder().
		WithKeyCondition(expression.Key("user_id").Equal(expression.Value(ownerID))).
		WithFilter(expression.Name("visibility").In(visValues[0], visValues[1:]...))

	expr, err := builder.Build()
	if err != nil {
		return nil, "", fmt.Errorf("building keyboard list expression: %w", err)
	}

	out, err := r.client.Query(ctx, &dynamodb.QueryInput{
		TableName:                 &r.tableName,
		KeyConditionExpression:    expr.KeyCondition(),
		FilterExpression:          expr.Filter(),
		ExpressionAttributeNames:  expr.Names(),
		ExpressionAttributeValues: expr.Values(),
		ExclusiveStartKey:         startKey,
		Limit:                     queryLimit(limit),
	})
	if err != nil {
		return nil, "", fmt.Errorf("querying keyboards for owner %q: %w", ownerID, err)
	}

	keyboards := []repository.Keyboard{}
	if err := attributevalue.UnmarshalListOfMaps(out.Items, &keyboards); err != nil {
		return nil, "", fmt.Errorf("unmarshalling keyboards for owner %q: %w", ownerID, err)
	}

	nextCursor, err := encodeCursor(out.LastEvaluatedKey)
	if err != nil {
		return nil, "", fmt.Errorf("encoding next cursor: %w", err)
	}

	return keyboards, nextCursor, nil
}

// Get implements repository.KeyboardRepository.
func (r *KeyboardRepository) Get(ctx context.Context, ownerID, id string) (*repository.Keyboard, error) {
	out, err := r.client.GetItem(ctx, &dynamodb.GetItemInput{
		TableName: &r.tableName,
		Key: map[string]types.AttributeValue{
			"user_id": &types.AttributeValueMemberS{Value: ownerID},
			"id":      &types.AttributeValueMemberS{Value: id},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("getting keyboard %q for owner %q: %w", id, ownerID, err)
	}

	if len(out.Item) == 0 {
		return nil, repository.ErrNotFound
	}

	var kb repository.Keyboard
	if err := attributevalue.UnmarshalMap(out.Item, &kb); err != nil {
		return nil, fmt.Errorf("unmarshalling keyboard %q for owner %q: %w", id, ownerID, err)
	}

	return &kb, nil
}

// Create implements repository.KeyboardRepository.
func (r *KeyboardRepository) Create(ctx context.Context, kb repository.Keyboard) (*repository.Keyboard, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("creating keyboard %q: %w", kb.ID, repository.ErrNoUserID)
	}
	kb.UserID = ownerID

	item, err := attributevalue.MarshalMap(kb)
	if err != nil {
		return nil, fmt.Errorf("marshalling keyboard %q for owner %q: %w", kb.ID, kb.UserID, err)
	}

	_, err = r.client.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           &r.tableName,
		Item:                item,
		ConditionExpression: aws.String("attribute_not_exists(id)"),
	})
	if err != nil {
		if _, ok := errors.AsType[*types.ConditionalCheckFailedException](err); ok {
			return nil, repository.ErrAlreadyExists
		}
		return nil, fmt.Errorf("creating keyboard %q for owner %q: %w", kb.ID, kb.UserID, err)
	}

	return &kb, nil
}

// Update goes through mutateKeyboard rather than a naive whole-item
// PutItem: kb (built from the request body) never has Images or Version
// set, so overwriting the stored item wholesale would wipe every image
// and desync Version from mutateKeyboard's CAS loop.
func (r *KeyboardRepository) Update(ctx context.Context, kb repository.Keyboard) (*repository.Keyboard, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("updating keyboard %q: %w", kb.ID, repository.ErrNoUserID)
	}

	updated, err := r.mutateKeyboard(ctx, ownerID, kb.ID, func(existing *repository.Keyboard) error {
		existing.Brand = kb.Brand
		existing.Name = kb.Name
		existing.Size = kb.Size
		existing.Layout = kb.Layout
		existing.Design = kb.Design
		existing.PCB = kb.PCB
		existing.Purchase = kb.Purchase
		existing.Notes = kb.Notes
		existing.Visibility = kb.Visibility
		return nil
	})
	if errors.Is(err, repository.ErrNotFound) {
		return nil, repository.ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("updating keyboard %q for owner %q: %w", kb.ID, ownerID, err)
	}

	return updated, nil
}

// Delete implements repository.KeyboardRepository. Idempotent: a
// nonexistent id is not an error.
func (r *KeyboardRepository) Delete(ctx context.Context, id string) error {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return fmt.Errorf("deleting keyboard %q: %w", id, repository.ErrNoUserID)
	}

	_, err := r.client.DeleteItem(ctx, &dynamodb.DeleteItemInput{
		TableName: &r.tableName,
		Key: map[string]types.AttributeValue{
			"user_id": &types.AttributeValueMemberS{Value: ownerID},
			"id":      &types.AttributeValueMemberS{Value: id},
		},
	})
	if err != nil {
		return fmt.Errorf("deleting keyboard %q for owner %q: %w", id, ownerID, err)
	}

	return nil
}

const maxKeyboardMutationAttempts = 3

// mutateKeyboard is a hand-rolled Version-based CAS retry loop: DynamoDB
// can't address a List element by an inner field like image_id, so image
// mutations must decode/mutate/re-encode the whole Images slice, and the Go
// SDK has no built-in optimistic-locking primitive. Mirrors
// [(*KeycapSetRepository).mutateSet]/[(*BuildRepository).mutateBuild], minus
// Build's refMarker transaction bookkeeping - a keyboard has no analogous
// cross-entity reference set to maintain here.
func (r *KeyboardRepository) mutateKeyboard(
	ctx context.Context,
	ownerID, keyboardID string,
	mutate func(kb *repository.Keyboard) error,
) (*repository.Keyboard, error) {
	for range maxKeyboardMutationAttempts {
		kb, err := r.Get(ctx, ownerID, keyboardID)
		if err != nil {
			return nil, err
		}

		if err := mutate(kb); err != nil {
			return nil, err
		}

		expectedVersion := kb.Version
		kb.Version++
		kb.UserID = ownerID

		item, err := attributevalue.MarshalMap(*kb)
		if err != nil {
			return nil, fmt.Errorf("marshalling keyboard %q for owner %q: %w", keyboardID, ownerID, err)
		}

		// expectedVersion is 0 both for a real version:0 item and for a
		// pre-Version item with no version attribute at all (Get/UnmarshalMap
		// defaults a missing attribute to the zero value) - attribute_not_exists
		// covers the latter, since DynamoDB never matches an equality condition
		// against an absent attribute.
		versionCondition := expression.Name("version").Equal(expression.Value(expectedVersion))
		if expectedVersion == 0 {
			versionCondition = versionCondition.Or(expression.AttributeNotExists(expression.Name("version")))
		}
		expr, err := expression.NewBuilder().
			WithCondition(versionCondition).
			Build()
		if err != nil {
			return nil, fmt.Errorf("building keyboard mutation condition for keyboard %q: %w", keyboardID, err)
		}

		_, err = r.client.PutItem(ctx, &dynamodb.PutItemInput{
			TableName:                 &r.tableName,
			Item:                      item,
			ConditionExpression:       expr.Condition(),
			ExpressionAttributeNames:  expr.Names(),
			ExpressionAttributeValues: expr.Values(),
		})
		if err == nil {
			return kb, nil
		}

		if _, ok := errors.AsType[*types.ConditionalCheckFailedException](err); !ok {
			return nil, fmt.Errorf("mutating keyboard %q owner %q: %w", keyboardID, ownerID, err)
		}
		// Lost the CAS race - another writer updated Version first. Loop
		// and retry from a fresh Get.
		log.FromContext(ctx).Warn("keyboard CAS retry", log.KeyboardID, keyboardID, "attempted_version", expectedVersion)
	}

	return nil, fmt.Errorf("mutating keyboard %q owner %q: %w", keyboardID, ownerID, repository.ErrMutationConflict)
}

// AddImage implements repository.KeyboardRepository.
func (r *KeyboardRepository) AddImage(ctx context.Context, keyboardID string, image repository.KeyboardImage) error {
	if image.ImageID == "" {
		return fmt.Errorf("adding image to keyboard %q: %w", keyboardID, errEmptyKeyboardImageID)
	}

	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return fmt.Errorf("adding image to keyboard %q: %w", keyboardID, repository.ErrNoUserID)
	}

	_, err := r.mutateKeyboard(ctx, ownerID, keyboardID, func(kb *repository.Keyboard) error {
		if slices.ContainsFunc(kb.Images, func(existing repository.KeyboardImage) bool { return existing.ImageID == image.ImageID }) {
			return fmt.Errorf("adding image %q to keyboard %q: %w", image.ImageID, keyboardID, errDuplicateKeyboardImageID)
		}
		kb.Images = append(kb.Images, image)
		return nil
	})
	return err
}

// DeleteImage implements repository.KeyboardRepository.
func (r *KeyboardRepository) DeleteImage(ctx context.Context, keyboardID, imageID string) (*repository.KeyboardImageKey, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("deleting image from keyboard %q: %w", keyboardID, repository.ErrNoUserID)
	}

	var removed *repository.KeyboardImageKey
	_, err := r.mutateKeyboard(ctx, ownerID, keyboardID, func(kb *repository.Keyboard) error {
		idx := slices.IndexFunc(kb.Images, func(existing repository.KeyboardImage) bool { return existing.ImageID == imageID })
		if idx == -1 {
			return errKeyboardImageAlreadyAbsent
		}
		key := kb.Images[idx].Path
		removed = &key
		kb.Images = slices.Delete(kb.Images, idx, idx+1)
		return nil
	})
	if errors.Is(err, errKeyboardImageAlreadyAbsent) {
		return nil, nil //nolint:nilnil // no such image already absent is a valid, expected result
	}
	if err != nil {
		return nil, err
	}

	return removed, nil
}
