package dynamo

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	kbdbctx "github.com/rogueserenity/kbdb/internal/ctx"
	"github.com/rogueserenity/kbdb/internal/repository"
)

// errEmptyKeyboardImageID guards AddImage against persisting an image with
// no ImageID - ImageID is meant to be server-generated by the handler
// (uuid.NewString()) before reaching this layer, so an empty value here
// means a caller skipped that step, not a legitimate request.
var errEmptyKeyboardImageID = errors.New("image id must not be empty")

// errDuplicateKeyboardImageID guards AddImage against an ImageID collision
// within one keyboard's Images - practically unreachable given
// uuid.NewString(), but caught here rather than silently persisting an
// ambiguous duplicate.
var errDuplicateKeyboardImageID = errors.New("image id already exists for this keyboard")

// KeyboardRepository is the DynamoDB-backed repository.KeyboardRepository.
type KeyboardRepository struct {
	client    dynamoAPI
	tableName string
}

var _ repository.KeyboardRepository = (*KeyboardRepository)(nil)

// NewKeyboardRepository returns a KeyboardRepository backed by client.
func NewKeyboardRepository(client *dynamodb.Client, tableName string) *KeyboardRepository {
	return &KeyboardRepository{client: client, tableName: tableName}
}

// List implements repository.KeyboardRepository.
func (r *KeyboardRepository) List(
	ctx context.Context,
	ownerID string,
	visibilities []repository.Visibility,
	limit int,
	cursor string,
) ([]repository.Keyboard, string, error) {
	// No visibility tier is readable, so nothing can match - short-circuit
	// rather than build a Query with an empty IN(...) filter (which the
	// expression builder below would panic constructing).
	if len(visibilities) == 0 {
		return []repository.Keyboard{}, "", nil
	}

	startKey, err := decodeCursor(cursor)
	if err != nil {
		return nil, "", fmt.Errorf("decoding cursor: %w", err)
	}

	visValues := make([]expression.OperandBuilder, len(visibilities))
	for i, v := range visibilities {
		visValues[i] = expression.Value(v)
	}

	builder := expression.NewBuilder().
		WithKeyCondition(expression.Key("user_id").Equal(expression.Value(ownerID))).
		WithFilter(expression.Name("visibility").In(visValues[0], visValues[1:]...))

	expr, err := builder.Build()
	if err != nil {
		return nil, "", fmt.Errorf("building keyboard list expression: %w", err)
	}

	out, err := r.client.Query(ctx, &dynamodb.QueryInput{
		TableName:                 &r.tableName,
		KeyConditionExpression:    expr.KeyCondition(),
		FilterExpression:          expr.Filter(),
		ExpressionAttributeNames:  expr.Names(),
		ExpressionAttributeValues: expr.Values(),
		ExclusiveStartKey:         startKey,
		Limit:                     queryLimit(limit),
	})
	if err != nil {
		return nil, "", fmt.Errorf("querying keyboards for owner %q: %w", ownerID, err)
	}

	keyboards := []repository.Keyboard{}
	if err := attributevalue.UnmarshalListOfMaps(out.Items, &keyboards); err != nil {
		return nil, "", fmt.Errorf("unmarshalling keyboards for owner %q: %w", ownerID, err)
	}

	nextCursor, err := encodeCursor(out.LastEvaluatedKey)
	if err != nil {
		return nil, "", fmt.Errorf("encoding next cursor: %w", err)
	}

	return keyboards, nextCursor, nil
}

// Get implements repository.KeyboardRepository.
func (r *KeyboardRepository) Get(ctx context.Context, ownerID, id string) (*repository.Keyboard, error) {
	out, err := r.client.GetItem(ctx, &dynamodb.GetItemInput{
		TableName: &r.tableName,
		Key: map[string]types.AttributeValue{
			"user_id": &types.AttributeValueMemberS{Value: ownerID},
			"id":      &types.AttributeValueMemberS{Value: id},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("getting keyboard %q for owner %q: %w", id, ownerID, err)
	}

	if len(out.Item) == 0 {
		return nil, repository.ErrNotFound
	}

	var kb repository.Keyboard
	if err := attributevalue.UnmarshalMap(out.Item, &kb); err != nil {
		return nil, fmt.Errorf("unmarshalling keyboard %q for owner %q: %w", id, ownerID, err)
	}

	return &kb, nil
}

// Create implements repository.KeyboardRepository.
func (r *KeyboardRepository) Create(ctx context.Context, kb repository.Keyboard) (*repository.Keyboard, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("creating keyboard %q: %w", kb.ID, repository.ErrNoUserID)
	}
	kb.UserID = ownerID

	item, err := attributevalue.MarshalMap(kb)
	if err != nil {
		return nil, fmt.Errorf("marshalling keyboard %q for owner %q: %w", kb.ID, kb.UserID, err)
	}
	// AddImage addresses images.<id> in place - DynamoDB won't auto-vivify
	// the parent Map, so seed an empty one.
	if _, ok := item["images"]; !ok {
		item["images"] = &types.AttributeValueMemberM{Value: map[string]types.AttributeValue{}}
	}

	_, err = r.client.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           &r.tableName,
		Item:                item,
		ConditionExpression: aws.String("attribute_not_exists(id)"),
	})
	if err != nil {
		if _, ok := errors.AsType[*types.ConditionalCheckFailedException](err); ok {
			return nil, repository.ErrAlreadyExists
		}
		return nil, fmt.Errorf("creating keyboard %q for owner %q: %w", kb.ID, kb.UserID, err)
	}

	return &kb, nil
}

// keyboardKey builds the base-table primary key for a keyboard.
func keyboardKey(ownerID, keyboardID string) map[string]types.AttributeValue {
	return map[string]types.AttributeValue{
		"user_id": &types.AttributeValueMemberS{Value: ownerID},
		"id":      &types.AttributeValueMemberS{Value: keyboardID},
	}
}

// Update rewrites the caller's keyboard from the request body with a single
// UpdateItem. images isn't named, so it carries forward.
// id is the sort key, so a failed attribute_exists(id) can only mean the
// keyboard is gone -> ErrNotFound.
func (r *KeyboardRepository) Update(ctx context.Context, kb repository.Keyboard) (*repository.Keyboard, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("updating keyboard %q: %w", kb.ID, repository.ErrNoUserID)
	}

	update := expression.
		Set(expression.Name("brand"), expression.Value(kb.Brand)).
		Set(expression.Name("name"), expression.Value(kb.Name)).
		Set(expression.Name("design"), expression.Value(kb.Design)).
		Set(expression.Name("pcb"), expression.Value(kb.PCB)).
		Set(expression.Name("purchase"), expression.Value(kb.Purchase)).
		Set(expression.Name("visibility"), expression.Value(kb.Visibility))
	update = setOrRemovePtr(update, "size", kb.Size)
	update = setOrRemovePtr(update, "layout", kb.Layout)
	update = setOrRemovePtr(update, "notes", kb.Notes)

	expr, err := expression.NewBuilder().
		WithUpdate(update).
		WithCondition(expression.AttributeExists(expression.Name("id"))).
		Build()
	if err != nil {
		return nil, fmt.Errorf("building keyboard update expression for keyboard %q: %w", kb.ID, err)
	}

	out, err := r.client.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 &r.tableName,
		Key:                       keyboardKey(ownerID, kb.ID),
		UpdateExpression:          expr.Update(),
		ConditionExpression:       expr.Condition(),
		ExpressionAttributeNames:  expr.Names(),
		ExpressionAttributeValues: expr.Values(),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if _, ok := errors.AsType[*types.ConditionalCheckFailedException](err); ok {
			return nil, repository.ErrNotFound
		}
		return nil, fmt.Errorf("updating keyboard %q for owner %q: %w", kb.ID, ownerID, err)
	}

	var updated repository.Keyboard
	if err := attributevalue.UnmarshalMap(out.Attributes, &updated); err != nil {
		return nil, fmt.Errorf("unmarshalling updated keyboard %q for owner %q: %w", kb.ID, ownerID, err)
	}

	return &updated, nil
}

// Delete implements repository.KeyboardRepository. Idempotent: a
// nonexistent id is not an error.
func (r *KeyboardRepository) Delete(ctx context.Context, id string) error {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return fmt.Errorf("deleting keyboard %q: %w", id, repository.ErrNoUserID)
	}

	_, err := r.client.DeleteItem(ctx, &dynamodb.DeleteItemInput{
		TableName: &r.tableName,
		Key:       keyboardKey(ownerID, id),
	})
	if err != nil {
		return fmt.Errorf("deleting keyboard %q for owner %q: %w", id, ownerID, err)
	}

	return nil
}

// AddImage implements repository.KeyboardRepository. One UpdateItem sets
// images.<id> = {path, seq}. Seq is time.Now().UnixNano(), so a new image
// sorts after every existing one without reading the current max (see
// KeyboardImageEntry.Seq for the wall-clock caveat). The condition rejects
// a missing keyboard or a duplicate id server-side; on failure a
// consistent GetItem (keyboardExists) tells the two apart.
func (r *KeyboardRepository) AddImage(ctx context.Context, keyboardID string, image repository.KeyboardImage) error {
	if image.ImageID == "" {
		return fmt.Errorf("adding image to keyboard %q: %w", keyboardID, errEmptyKeyboardImageID)
	}

	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return fmt.Errorf("adding image to keyboard %q: %w", keyboardID, repository.ErrNoUserID)
	}

	imagePath := "images." + image.ImageID
	entry := repository.KeyboardImageEntry{Path: image.Path, Seq: int(time.Now().UnixNano())}
	update := expression.Set(expression.Name(imagePath), expression.Value(entry))
	cond := expression.AttributeExists(expression.Name("id")).
		And(expression.AttributeNotExists(expression.Name(imagePath)))

	expr, err := expression.NewBuilder().WithUpdate(update).WithCondition(cond).Build()
	if err != nil {
		return fmt.Errorf("building add-image expression for keyboard %q: %w", keyboardID, err)
	}

	_, err = r.client.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 &r.tableName,
		Key:                       keyboardKey(ownerID, keyboardID),
		UpdateExpression:          expr.Update(),
		ConditionExpression:       expr.Condition(),
		ExpressionAttributeNames:  expr.Names(),
		ExpressionAttributeValues: expr.Values(),
	})
	if err != nil {
		if _, ok := errors.AsType[*types.ConditionalCheckFailedException](err); ok {
			exists, existsErr := r.keyboardExists(ctx, ownerID, keyboardID)
			if existsErr != nil {
				return fmt.Errorf("classifying add-image conflict for keyboard %q: %w", keyboardID, existsErr)
			}
			if !exists {
				return repository.ErrNotFound
			}
			return fmt.Errorf("adding image %q to keyboard %q: %w", image.ImageID, keyboardID, errDuplicateKeyboardImageID)
		}
		return fmt.Errorf("adding image %q to keyboard %q owner %q: %w", image.ImageID, keyboardID, ownerID, err)
	}

	return nil
}

// keyboardExists is a strongly consistent existence check for classifying a
// compound-condition failure (attribute_exists(id) AND attribute_...(images.<id>)).
func (r *KeyboardRepository) keyboardExists(ctx context.Context, ownerID, id string) (bool, error) {
	out, err := r.client.GetItem(ctx, &dynamodb.GetItemInput{
		TableName:      &r.tableName,
		Key:            keyboardKey(ownerID, id),
		ConsistentRead: aws.Bool(true),
	})
	if err != nil {
		return false, err
	}
	return len(out.Item) > 0, nil
}

// DeleteImage implements repository.KeyboardRepository. REMOVE images.<id>
// under attribute_exists(images.<id>), with ALL_OLD so the removed entry's
// path is the returned key. A missing id (condition fails but the keyboard
// exists) is a nil-nil success.
func (r *KeyboardRepository) DeleteImage(ctx context.Context, keyboardID, imageID string) (*repository.KeyboardImageKey, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("deleting image from keyboard %q: %w", keyboardID, repository.ErrNoUserID)
	}

	imagePath := "images." + imageID
	expr, err := expression.NewBuilder().
		WithUpdate(expression.Remove(expression.Name(imagePath))).
		WithCondition(
			expression.AttributeExists(expression.Name("id")).
				And(expression.AttributeExists(expression.Name(imagePath))),
		).
		Build()
	if err != nil {
		return nil, fmt.Errorf("building delete-image expression for keyboard %q: %w", keyboardID, err)
	}

	out, err := r.client.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 &r.tableName,
		Key:                       keyboardKey(ownerID, keyboardID),
		UpdateExpression:          expr.Update(),
		ConditionExpression:       expr.Condition(),
		ExpressionAttributeNames:  expr.Names(),
		ExpressionAttributeValues: expr.Values(),
		ReturnValues:              types.ReturnValueAllOld,
	})
	if err != nil {
		if _, ok := errors.AsType[*types.ConditionalCheckFailedException](err); ok {
			return r.classifyDeleteImageConflict(ctx, ownerID, keyboardID)
		}
		return nil, fmt.Errorf("deleting image %q from keyboard %q owner %q: %w", imageID, keyboardID, ownerID, err)
	}

	var old repository.Keyboard
	if err := attributevalue.UnmarshalMap(out.Attributes, &old); err != nil {
		return nil, fmt.Errorf("unmarshalling pre-delete keyboard %q for owner %q: %w", keyboardID, ownerID, err)
	}
	entry, ok := old.Images[imageID]
	if !ok {
		return nil, nil //nolint:nilnil // no such image already absent is a valid, expected result
	}
	return &entry.Path, nil
}

// classifyDeleteImageConflict: keyboard gone -> ErrNotFound; keyboard
// present means the image id simply wasn't there -> nil-nil (idempotent).
func (r *KeyboardRepository) classifyDeleteImageConflict(ctx context.Context, ownerID, keyboardID string) (*repository.KeyboardImageKey, error) {
	exists, err := r.keyboardExists(ctx, ownerID, keyboardID)
	if err != nil {
		return nil, fmt.Errorf("classifying delete-image conflict for keyboard %q: %w", keyboardID, err)
	}
	if !exists {
		return nil, repository.ErrNotFound
	}
	return nil, nil //nolint:nilnil // no such image already absent is a valid, expected result
}
