package dynamo

import (
	"context"
	"errors"
	"fmt"
	"math"
	"slices"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	kbdbctx "github.com/rogueserenity/kbdb/internal/ctx"
	"github.com/rogueserenity/kbdb/internal/repository"
)

// errEmptyKitID guards AddKit against persisting a kit with no KitID -
// KitID is meant to be server-generated by the handler (uuid.NewString())
// before reaching this layer, so an empty value here means a caller skipped
// that step, not a legitimate request.
var errEmptyKitID = errors.New("kit id must not be empty")

// errDuplicateKitID guards AddKit against a KitID collision within one
// set's Kits - practically unreachable given uuid.NewString(), but caught
// here rather than silently persisting an ambiguous duplicate.
var errDuplicateKitID = errors.New("kit id already exists in this set")

type KeycapSetRepository struct {
	client    dynamoAPI
	tableName string
}

var _ repository.KeycapSetRepository = (*KeycapSetRepository)(nil)

func NewKeycapSetRepository(client *dynamodb.Client, tableName string) *KeycapSetRepository {
	return &KeycapSetRepository{client: client, tableName: tableName}
}

func (r *KeycapSetRepository) List(
	ctx context.Context,
	ownerID string,
	visibilities []repository.Visibility,
	limit int,
	cursor string,
) ([]repository.KeycapSet, string, error) {
	// No visibility tier is readable, so nothing can match - short-circuit
	// rather than build a Query with an empty IN(...) filter (which the
	// expression builder below would panic constructing).
	if len(visibilities) == 0 {
		return []repository.KeycapSet{}, "", nil
	}

	startKey, err := decodeCursor(cursor)
	if err != nil {
		return nil, "", fmt.Errorf("decoding cursor: %w", err)
	}

	// limit is validated by the handler against api/openapi.yaml's Limit
	// parameter (1-100) before reaching here; List's exported signature
	// accepts any int, so clamp defensively rather than trust that.
	if limit < 1 {
		limit = 1
	} else if limit > math.MaxInt32 {
		limit = math.MaxInt32
	}

	visValues := make([]expression.OperandBuilder, len(visibilities))
	for i, v := range visibilities {
		visValues[i] = expression.Value(v)
	}

	builder := expression.NewBuilder().
		WithKeyCondition(expression.Key("user_id").Equal(expression.Value(ownerID))).
		WithFilter(expression.Name("visibility").In(visValues[0], visValues[1:]...))

	expr, err := builder.Build()
	if err != nil {
		return nil, "", fmt.Errorf("building keycap set list expression: %w", err)
	}

	out, err := r.client.Query(ctx, &dynamodb.QueryInput{
		TableName:                 &r.tableName,
		KeyConditionExpression:    expr.KeyCondition(),
		FilterExpression:          expr.Filter(),
		ExpressionAttributeNames:  expr.Names(),
		ExpressionAttributeValues: expr.Values(),
		ExclusiveStartKey:         startKey,
		Limit:                     aws.Int32(int32(limit)),
	})
	if err != nil {
		return nil, "", fmt.Errorf("querying keycap sets for owner %q: %w", ownerID, err)
	}

	sets := []repository.KeycapSet{}
	if err := attributevalue.UnmarshalListOfMaps(out.Items, &sets); err != nil {
		return nil, "", fmt.Errorf("unmarshalling keycap sets for owner %q: %w", ownerID, err)
	}

	nextCursor, err := encodeCursor(out.LastEvaluatedKey)
	if err != nil {
		return nil, "", fmt.Errorf("encoding next cursor: %w", err)
	}

	return sets, nextCursor, nil
}

func (r *KeycapSetRepository) Get(ctx context.Context, ownerID, id string) (*repository.KeycapSet, error) {
	out, err := r.client.GetItem(ctx, &dynamodb.GetItemInput{
		TableName: &r.tableName,
		Key: map[string]types.AttributeValue{
			"user_id": &types.AttributeValueMemberS{Value: ownerID},
			"id":      &types.AttributeValueMemberS{Value: id},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("getting keycap set %q for owner %q: %w", id, ownerID, err)
	}

	if len(out.Item) == 0 {
		return nil, repository.ErrNotFound
	}

	var ks repository.KeycapSet
	if err := attributevalue.UnmarshalMap(out.Item, &ks); err != nil {
		return nil, fmt.Errorf("unmarshalling keycap set %q for owner %q: %w", id, ownerID, err)
	}

	return &ks, nil
}

func (r *KeycapSetRepository) Create(ctx context.Context, ks repository.KeycapSet) (*repository.KeycapSet, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("creating keycap set %q: %w", ks.ID, errNoUserID)
	}
	ks.UserID = ownerID

	item, err := attributevalue.MarshalMap(ks)
	if err != nil {
		return nil, fmt.Errorf("marshalling keycap set %q for owner %q: %w", ks.ID, ks.UserID, err)
	}

	_, err = r.client.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           &r.tableName,
		Item:                item,
		ConditionExpression: aws.String("attribute_not_exists(id)"),
	})
	if err != nil {
		var condErr *types.ConditionalCheckFailedException
		if errors.As(err, &condErr) {
			return nil, repository.ErrAlreadyExists
		}
		return nil, fmt.Errorf("creating keycap set %q for owner %q: %w", ks.ID, ks.UserID, err)
	}

	return &ks, nil
}

// Update replaces ks's own fields (Brand, Name, Profile, Material, Notes,
// Visibility) on the stored set, going through the same version-CAS
// read-modify-write as kit mutations (mutateSet) rather than a naive
// whole-item PutItem - ks (built from the request body) never has Kits or
// Version set, so overwriting the stored item wholesale would silently
// wipe every kit on the set and desync Version from mutateSet's CAS loop.
func (r *KeycapSetRepository) Update(ctx context.Context, ks repository.KeycapSet) (*repository.KeycapSet, error) {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("updating keycap set %q: %w", ks.ID, errNoUserID)
	}

	updated, err := r.mutateSet(ctx, ownerID, ks.ID, func(existing *repository.KeycapSet) error {
		existing.Brand = ks.Brand
		existing.Name = ks.Name
		existing.Profile = ks.Profile
		existing.Material = ks.Material
		existing.Notes = ks.Notes
		existing.Visibility = ks.Visibility
		return nil
	})
	if errors.Is(err, repository.ErrNotFound) {
		return nil, repository.ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("updating keycap set %q for owner %q: %w", ks.ID, ownerID, err)
	}

	return updated, nil
}

func (r *KeycapSetRepository) Delete(ctx context.Context, id string) error {
	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return fmt.Errorf("deleting keycap set %q: %w", id, errNoUserID)
	}

	_, err := r.client.DeleteItem(ctx, &dynamodb.DeleteItemInput{
		TableName: &r.tableName,
		Key: map[string]types.AttributeValue{
			"user_id": &types.AttributeValueMemberS{Value: ownerID},
			"id":      &types.AttributeValueMemberS{Value: id},
		},
	})
	if err != nil {
		return fmt.Errorf("deleting keycap set %q for owner %q: %w", id, ownerID, err)
	}

	return nil
}

const maxSetMutationAttempts = 3

// mutateSet performs a bounded read-modify-write of the whole setID item
// under a Version-based CAS loop: Get the set, run mutate against the
// in-memory struct, increment Version, and PutItem with a
// ConditionExpression requiring the version to still match what was read.
// On a CAS miss (another writer won the race), re-Get and retry.
//
// Both AddKit and Update go through this rather than a flat PutItem:
// DynamoDB can't address a List element by an inner field like kit_id, so
// kit mutations must decode/mutate/re-encode the whole Kits slice in Go;
// Update must preserve Kits/Version across an edit to the set's own fields.
// The Go SDK has no built-in optimistic-locking primitive (unlike Java's
// DynamoDBMapper), hence the hand-rolled loop.
func (r *KeycapSetRepository) mutateSet(
	ctx context.Context,
	ownerID, setID string,
	mutate func(ks *repository.KeycapSet) error,
) (*repository.KeycapSet, error) {
	for range maxSetMutationAttempts {
		ks, err := r.Get(ctx, ownerID, setID)
		if err != nil {
			return nil, err
		}

		if err := mutate(ks); err != nil {
			return nil, err
		}

		expectedVersion := ks.Version
		ks.Version++

		item, err := attributevalue.MarshalMap(*ks)
		if err != nil {
			return nil, fmt.Errorf("marshalling keycap set %q for owner %q: %w", setID, ownerID, err)
		}

		expr, err := expression.NewBuilder().
			WithCondition(expression.Name("version").Equal(expression.Value(expectedVersion))).
			Build()
		if err != nil {
			return nil, fmt.Errorf("building set mutation condition for set %q: %w", setID, err)
		}

		_, err = r.client.PutItem(ctx, &dynamodb.PutItemInput{
			TableName:                 &r.tableName,
			Item:                      item,
			ConditionExpression:       expr.Condition(),
			ExpressionAttributeNames:  expr.Names(),
			ExpressionAttributeValues: expr.Values(),
		})
		if err == nil {
			return ks, nil
		}

		var condErr *types.ConditionalCheckFailedException
		if !errors.As(err, &condErr) {
			return nil, fmt.Errorf("mutating set %q owner %q: %w", setID, ownerID, err)
		}
		// Lost the CAS race - another writer updated Version first. Loop
		// and retry from a fresh Get.
	}

	return nil, fmt.Errorf("mutating set %q owner %q: %w", setID, ownerID, repository.ErrMutationConflict)
}

func (r *KeycapSetRepository) AddKit(ctx context.Context, setID string, kit repository.KeycapKit) (*repository.KeycapKit, error) {
	if kit.KitID == "" {
		return nil, fmt.Errorf("adding kit to keycap set %q: %w", setID, errEmptyKitID)
	}

	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("adding kit to keycap set %q: %w", setID, errNoUserID)
	}

	updated, err := r.mutateSet(ctx, ownerID, setID, func(ks *repository.KeycapSet) error {
		if slices.ContainsFunc(ks.Kits, func(existing repository.KeycapKit) bool { return existing.KitID == kit.KitID }) {
			return fmt.Errorf("adding kit %q to keycap set %q: %w", kit.KitID, setID, errDuplicateKitID)
		}
		ks.Kits = append(ks.Kits, kit)
		return nil
	})
	if err != nil {
		return nil, err
	}

	idx := slices.IndexFunc(updated.Kits, func(k repository.KeycapKit) bool { return k.KitID == kit.KitID })
	if idx == -1 {
		return nil, fmt.Errorf("adding kit %q to keycap set %q: %w", kit.KitID, setID, errKitMissingAfterAdd)
	}

	return &updated.Kits[idx], nil
}

func (r *KeycapSetRepository) UpdateKit(ctx context.Context, setID string, kit repository.KeycapKit) (*repository.KeycapKit, error) {
	if kit.KitID == "" {
		return nil, fmt.Errorf("updating kit in keycap set %q: %w", setID, errEmptyKitID)
	}

	ownerID, ok := kbdbctx.UserID(ctx)
	if !ok {
		return nil, fmt.Errorf("updating kit in keycap set %q: %w", setID, errNoUserID)
	}

	updated, err := r.mutateSet(ctx, ownerID, setID, func(ks *repository.KeycapSet) error {
		idx := slices.IndexFunc(ks.Kits, func(existing repository.KeycapKit) bool { return existing.KitID == kit.KitID })
		if idx == -1 {
			return repository.ErrNotFound
		}
		ks.Kits[idx] = kit
		return nil
	})
	if err != nil {
		return nil, err
	}

	idx := slices.IndexFunc(updated.Kits, func(k repository.KeycapKit) bool { return k.KitID == kit.KitID })
	if idx == -1 {
		return nil, fmt.Errorf("updating kit %q in keycap set %q: %w", kit.KitID, setID, errKitMissingAfterAdd)
	}

	return &updated.Kits[idx], nil
}
