// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockS3PresignAPI creates a new instance of MockS3PresignAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3PresignAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3PresignAPI {
	mock := &MockS3PresignAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3PresignAPI is an autogenerated mock type for the s3PresignAPI type
type MockS3PresignAPI struct {
	mock.Mock
}

type MockS3PresignAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3PresignAPI) EXPECT() *MockS3PresignAPI_Expecter {
	return &MockS3PresignAPI_Expecter{mock: &_m.Mock}
}

// PresignGetObject provides a mock function for the type MockS3PresignAPI
func (_mock *MockS3PresignAPI) PresignGetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PresignGetObject")
	}

	var r0 *v4.PresignedHTTPRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) *v4.PresignedHTTPRequest); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v4.PresignedHTTPRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3PresignAPI_PresignGetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignGetObject'
type MockS3PresignAPI_PresignGetObject_Call struct {
	*mock.Call
}

// PresignGetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.GetObjectInput
//   - optFns ...func(*s3.PresignOptions)
func (_e *MockS3PresignAPI_Expecter) PresignGetObject(ctx any, params any, optFns ...any) *MockS3PresignAPI_PresignGetObject_Call {
	return &MockS3PresignAPI_PresignGetObject_Call{Call: _e.mock.On("PresignGetObject",
		append([]any{ctx, params}, optFns...)...)}
}

func (_c *MockS3PresignAPI_PresignGetObject_Call) Run(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions))) *MockS3PresignAPI_PresignGetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.GetObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.GetObjectInput)
		}
		var arg2 []func(*s3.PresignOptions)
		var variadicArgs []func(*s3.PresignOptions)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.PresignOptions))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3PresignAPI_PresignGetObject_Call) Return(presignedHTTPRequest *v4.PresignedHTTPRequest, err error) *MockS3PresignAPI_PresignGetObject_Call {
	_c.Call.Return(presignedHTTPRequest, err)
	return _c
}

func (_c *MockS3PresignAPI_PresignGetObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)) *MockS3PresignAPI_PresignGetObject_Call {
	_c.Call.Return(run)
	return _c
}

// PresignPutObject provides a mock function for the type MockS3PresignAPI
func (_mock *MockS3PresignAPI) PresignPutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PresignPutObject")
	}

	var r0 *v4.PresignedHTTPRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.PresignOptions)) *v4.PresignedHTTPRequest); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v4.PresignedHTTPRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.PutObjectInput, ...func(*s3.PresignOptions)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3PresignAPI_PresignPutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignPutObject'
type MockS3PresignAPI_PresignPutObject_Call struct {
	*mock.Call
}

// PresignPutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.PutObjectInput
//   - optFns ...func(*s3.PresignOptions)
func (_e *MockS3PresignAPI_Expecter) PresignPutObject(ctx any, params any, optFns ...any) *MockS3PresignAPI_PresignPutObject_Call {
	return &MockS3PresignAPI_PresignPutObject_Call{Call: _e.mock.On("PresignPutObject",
		append([]any{ctx, params}, optFns...)...)}
}

func (_c *MockS3PresignAPI_PresignPutObject_Call) Run(run func(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.PresignOptions))) *MockS3PresignAPI_PresignPutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.PutObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.PutObjectInput)
		}
		var arg2 []func(*s3.PresignOptions)
		var variadicArgs []func(*s3.PresignOptions)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.PresignOptions))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3PresignAPI_PresignPutObject_Call) Return(presignedHTTPRequest *v4.PresignedHTTPRequest, err error) *MockS3PresignAPI_PresignPutObject_Call {
	_c.Call.Return(presignedHTTPRequest, err)
	return _c
}

func (_c *MockS3PresignAPI_PresignPutObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)) *MockS3PresignAPI_PresignPutObject_Call {
	_c.Call.Return(run)
	return _c
}
